// Code generated by nuzur go-code-gen. DO NOT EDIT.

package enums

import (
	"encoding/json"
	"github.com/guregu/null/v6"
	"log"
)

//go:generate go run github.com/dmarkham/enumer -type=AgentNodeStatus -json
type AgentNodeStatus int64

const (
	AGENT_NODE_STATUS_INVALID = iota
	AGENT_NODE_STATUS_NOT_STARTED
	AGENT_NODE_STATUS_IN_PROGRESS
	AGENT_NODE_STATUS_SUCCEEDED
	AGENT_NODE_STATUS_BLOCKED_ON_USER_DECISION
	AGENT_NODE_STATUS_BLOCKED_ON_MISSING_DATA
	AGENT_NODE_STATUS_BLOCKED_ON_PROVIDER_OUTAGE
	AGENT_NODE_STATUS_FAILED
	AGENT_NODE_STATUS_CANCELLED
	AGENT_NODE_STATUS_SKIPPED
)

func (e AgentNodeStatus) ToInt64() int64 {
	return int64(e)
}

func (e AgentNodeStatus) ToNullInt() null.Int {
	return null.NewInt(int64(e), true)
}

func AgentNodeStatusFromString(in string) AgentNodeStatus {
	switch in {
	case "invalid":
		return AGENT_NODE_STATUS_INVALID
	case "not_started":
		return AGENT_NODE_STATUS_NOT_STARTED
	case "in_progress":
		return AGENT_NODE_STATUS_IN_PROGRESS
	case "succeeded":
		return AGENT_NODE_STATUS_SUCCEEDED
	case "blocked_on_user_decision":
		return AGENT_NODE_STATUS_BLOCKED_ON_USER_DECISION
	case "blocked_on_missing_data":
		return AGENT_NODE_STATUS_BLOCKED_ON_MISSING_DATA
	case "blocked_on_provider_outage":
		return AGENT_NODE_STATUS_BLOCKED_ON_PROVIDER_OUTAGE
	case "failed":
		return AGENT_NODE_STATUS_FAILED
	case "cancelled":
		return AGENT_NODE_STATUS_CANCELLED
	case "skipped":
		return AGENT_NODE_STATUS_SKIPPED
	}
	return AGENT_NODE_STATUS_INVALID
}

func AgentNodeStatusFromPointerString(in *string) AgentNodeStatus {
	if in == nil {
		return AGENT_NODE_STATUS_INVALID
	}
	return AgentNodeStatusFromString(*in)
}

func (e AgentNodeStatus) String() string {
	switch e {
	case AGENT_NODE_STATUS_INVALID:
		return "invalid"
	case AGENT_NODE_STATUS_NOT_STARTED:
		return "not_started"
	case AGENT_NODE_STATUS_IN_PROGRESS:
		return "in_progress"
	case AGENT_NODE_STATUS_SUCCEEDED:
		return "succeeded"
	case AGENT_NODE_STATUS_BLOCKED_ON_USER_DECISION:
		return "blocked_on_user_decision"
	case AGENT_NODE_STATUS_BLOCKED_ON_MISSING_DATA:
		return "blocked_on_missing_data"
	case AGENT_NODE_STATUS_BLOCKED_ON_PROVIDER_OUTAGE:
		return "blocked_on_provider_outage"
	case AGENT_NODE_STATUS_FAILED:
		return "failed"
	case AGENT_NODE_STATUS_CANCELLED:
		return "cancelled"
	case AGENT_NODE_STATUS_SKIPPED:
		return "skipped"
	}

	return "invalid"
}

func (e AgentNodeStatus) StringPtr() *string {
	val := e.String()
	return &val
}

func AgentNodeStatusSliceToJSON(in []AgentNodeStatus) json.RawMessage {
	res := make([]int64, len(in))
	for i, e := range in {
		res[i] = int64(e)
	}
	jr, err := json.Marshal(res)
	if err != nil {
		log.Printf("error marshaling AgentNodeStatus slice to json: %v", err)
		// the empty ARRAY, not a zero-length RawMessage: the latter reaches the
		// driver as an empty string, which no JSON column accepts
		return json.RawMessage("[]")
	}
	return jr
}

func JSONToAgentNodeStatusSlice(in []byte) []AgentNodeStatus {
	res := []int64{}
	// an absent column (NULL / empty / JSON null) is not a decode failure
	if len(in) == 0 || string(in) == "null" {
		return nil
	}
	err := json.Unmarshal(in, &res)
	if err != nil {
		log.Printf("error unmarshaling AgentNodeStatus slice to int slice: %v", err)
		return nil
	}
	if len(res) == 0 {
		return nil
	}
	finalRes := []AgentNodeStatus{}
	for _, r := range res {
		finalRes = append(finalRes, AgentNodeStatus(r))
	}
	return finalRes
}
