// Code generated by nuzur go-code-gen. DO NOT EDIT.

package enums

import (
	"encoding/json"
	"github.com/guregu/null/v6"
	"log"
)

//go:generate go run github.com/dmarkham/enumer -type=AgentEventType -json
type AgentEventType int64

const (
	AGENT_EVENT_TYPE_INVALID = iota
	AGENT_EVENT_TYPE_RUN_STARTED
	AGENT_EVENT_TYPE_RUN_UPDATED
	AGENT_EVENT_TYPE_RUN_FINISHED
	AGENT_EVENT_TYPE_PLAN_DECLARED
	AGENT_EVENT_TYPE_NODE_ADDED
	AGENT_EVENT_TYPE_NODE_UPDATED
	AGENT_EVENT_TYPE_NODE_STATUS_CHANGED
	AGENT_EVENT_TYPE_NODE_REMOVED
	AGENT_EVENT_TYPE_EDGE_ADDED
	AGENT_EVENT_TYPE_EDGE_UPDATED
	AGENT_EVENT_TYPE_EDGE_REMOVED
	AGENT_EVENT_TYPE_ARTIFACT_ADDED
	AGENT_EVENT_TYPE_INTERVENTION_REQUESTED
	AGENT_EVENT_TYPE_INTERVENTION_DELIVERED
	AGENT_EVENT_TYPE_INTERVENTION_RESOLVED
	AGENT_EVENT_TYPE_HEARTBEAT
	AGENT_EVENT_TYPE_AGENT_MESSAGE
)

func (e AgentEventType) ToInt64() int64 {
	return int64(e)
}

func (e AgentEventType) ToNullInt() null.Int {
	return null.NewInt(int64(e), true)
}

func AgentEventTypeFromString(in string) AgentEventType {
	switch in {
	case "invalid":
		return AGENT_EVENT_TYPE_INVALID
	case "run_started":
		return AGENT_EVENT_TYPE_RUN_STARTED
	case "run_updated":
		return AGENT_EVENT_TYPE_RUN_UPDATED
	case "run_finished":
		return AGENT_EVENT_TYPE_RUN_FINISHED
	case "plan_declared":
		return AGENT_EVENT_TYPE_PLAN_DECLARED
	case "node_added":
		return AGENT_EVENT_TYPE_NODE_ADDED
	case "node_updated":
		return AGENT_EVENT_TYPE_NODE_UPDATED
	case "node_status_changed":
		return AGENT_EVENT_TYPE_NODE_STATUS_CHANGED
	case "node_removed":
		return AGENT_EVENT_TYPE_NODE_REMOVED
	case "edge_added":
		return AGENT_EVENT_TYPE_EDGE_ADDED
	case "edge_updated":
		return AGENT_EVENT_TYPE_EDGE_UPDATED
	case "edge_removed":
		return AGENT_EVENT_TYPE_EDGE_REMOVED
	case "artifact_added":
		return AGENT_EVENT_TYPE_ARTIFACT_ADDED
	case "intervention_requested":
		return AGENT_EVENT_TYPE_INTERVENTION_REQUESTED
	case "intervention_delivered":
		return AGENT_EVENT_TYPE_INTERVENTION_DELIVERED
	case "intervention_resolved":
		return AGENT_EVENT_TYPE_INTERVENTION_RESOLVED
	case "heartbeat":
		return AGENT_EVENT_TYPE_HEARTBEAT
	case "agent_message":
		return AGENT_EVENT_TYPE_AGENT_MESSAGE
	}
	return AGENT_EVENT_TYPE_INVALID
}

func AgentEventTypeFromPointerString(in *string) AgentEventType {
	if in == nil {
		return AGENT_EVENT_TYPE_INVALID
	}
	return AgentEventTypeFromString(*in)
}

func (e AgentEventType) String() string {
	switch e {
	case AGENT_EVENT_TYPE_INVALID:
		return "invalid"
	case AGENT_EVENT_TYPE_RUN_STARTED:
		return "run_started"
	case AGENT_EVENT_TYPE_RUN_UPDATED:
		return "run_updated"
	case AGENT_EVENT_TYPE_RUN_FINISHED:
		return "run_finished"
	case AGENT_EVENT_TYPE_PLAN_DECLARED:
		return "plan_declared"
	case AGENT_EVENT_TYPE_NODE_ADDED:
		return "node_added"
	case AGENT_EVENT_TYPE_NODE_UPDATED:
		return "node_updated"
	case AGENT_EVENT_TYPE_NODE_STATUS_CHANGED:
		return "node_status_changed"
	case AGENT_EVENT_TYPE_NODE_REMOVED:
		return "node_removed"
	case AGENT_EVENT_TYPE_EDGE_ADDED:
		return "edge_added"
	case AGENT_EVENT_TYPE_EDGE_UPDATED:
		return "edge_updated"
	case AGENT_EVENT_TYPE_EDGE_REMOVED:
		return "edge_removed"
	case AGENT_EVENT_TYPE_ARTIFACT_ADDED:
		return "artifact_added"
	case AGENT_EVENT_TYPE_INTERVENTION_REQUESTED:
		return "intervention_requested"
	case AGENT_EVENT_TYPE_INTERVENTION_DELIVERED:
		return "intervention_delivered"
	case AGENT_EVENT_TYPE_INTERVENTION_RESOLVED:
		return "intervention_resolved"
	case AGENT_EVENT_TYPE_HEARTBEAT:
		return "heartbeat"
	case AGENT_EVENT_TYPE_AGENT_MESSAGE:
		return "agent_message"
	}

	return "invalid"
}

func (e AgentEventType) StringPtr() *string {
	val := e.String()
	return &val
}

func AgentEventTypeSliceToJSON(in []AgentEventType) json.RawMessage {
	res := make([]int64, len(in))
	for i, e := range in {
		res[i] = int64(e)
	}
	jr, err := json.Marshal(res)
	if err != nil {
		log.Printf("error marshaling AgentEventType slice to json: %v", err)
		// the empty ARRAY, not a zero-length RawMessage: the latter reaches the
		// driver as an empty string, which no JSON column accepts
		return json.RawMessage("[]")
	}
	return jr
}

func JSONToAgentEventTypeSlice(in []byte) []AgentEventType {
	res := []int64{}
	// an absent column (NULL / empty / JSON null) is not a decode failure
	if len(in) == 0 || string(in) == "null" {
		return nil
	}
	err := json.Unmarshal(in, &res)
	if err != nil {
		log.Printf("error unmarshaling AgentEventType slice to int slice: %v", err)
		return nil
	}
	if len(res) == 0 {
		return nil
	}
	finalRes := []AgentEventType{}
	for _, r := range res {
		finalRes = append(finalRes, AgentEventType(r))
	}
	return finalRes
}
