// Code generated by nuzur go-code-gen. DO NOT EDIT.

package enums

import (
	"encoding/json"
	"github.com/guregu/null/v6"
	"log"
)

//go:generate go run github.com/dmarkham/enumer -type=AgentNodeType -json
type AgentNodeType int64

const (
	AGENT_NODE_TYPE_INVALID = iota
	AGENT_NODE_TYPE_PLAN_STEP
	AGENT_NODE_TYPE_TOOL_CALL
	AGENT_NODE_TYPE_REASONING
	AGENT_NODE_TYPE_DECISION
	AGENT_NODE_TYPE_USER_INTERACTION
	AGENT_NODE_TYPE_SUBAGENT_CALL
	AGENT_NODE_TYPE_EXTERNAL_CALL
	AGENT_NODE_TYPE_OTHER
)

func (e AgentNodeType) ToInt64() int64 {
	return int64(e)
}

func (e AgentNodeType) ToNullInt() null.Int {
	return null.NewInt(int64(e), true)
}

func AgentNodeTypeFromString(in string) AgentNodeType {
	switch in {
	case "invalid":
		return AGENT_NODE_TYPE_INVALID
	case "plan_step":
		return AGENT_NODE_TYPE_PLAN_STEP
	case "tool_call":
		return AGENT_NODE_TYPE_TOOL_CALL
	case "reasoning":
		return AGENT_NODE_TYPE_REASONING
	case "decision":
		return AGENT_NODE_TYPE_DECISION
	case "user_interaction":
		return AGENT_NODE_TYPE_USER_INTERACTION
	case "subagent_call":
		return AGENT_NODE_TYPE_SUBAGENT_CALL
	case "external_call":
		return AGENT_NODE_TYPE_EXTERNAL_CALL
	case "other":
		return AGENT_NODE_TYPE_OTHER
	}
	return AGENT_NODE_TYPE_INVALID
}

func AgentNodeTypeFromPointerString(in *string) AgentNodeType {
	if in == nil {
		return AGENT_NODE_TYPE_INVALID
	}
	return AgentNodeTypeFromString(*in)
}

func (e AgentNodeType) String() string {
	switch e {
	case AGENT_NODE_TYPE_INVALID:
		return "invalid"
	case AGENT_NODE_TYPE_PLAN_STEP:
		return "plan_step"
	case AGENT_NODE_TYPE_TOOL_CALL:
		return "tool_call"
	case AGENT_NODE_TYPE_REASONING:
		return "reasoning"
	case AGENT_NODE_TYPE_DECISION:
		return "decision"
	case AGENT_NODE_TYPE_USER_INTERACTION:
		return "user_interaction"
	case AGENT_NODE_TYPE_SUBAGENT_CALL:
		return "subagent_call"
	case AGENT_NODE_TYPE_EXTERNAL_CALL:
		return "external_call"
	case AGENT_NODE_TYPE_OTHER:
		return "other"
	}

	return "invalid"
}

func (e AgentNodeType) StringPtr() *string {
	val := e.String()
	return &val
}

func AgentNodeTypeSliceToJSON(in []AgentNodeType) json.RawMessage {
	res := make([]int64, len(in))
	for i, e := range in {
		res[i] = int64(e)
	}
	jr, err := json.Marshal(res)
	if err != nil {
		log.Printf("error marshaling AgentNodeType slice to json: %v", err)
		// the empty ARRAY, not a zero-length RawMessage: the latter reaches the
		// driver as an empty string, which no JSON column accepts
		return json.RawMessage("[]")
	}
	return jr
}

func JSONToAgentNodeTypeSlice(in []byte) []AgentNodeType {
	res := []int64{}
	// an absent column (NULL / empty / JSON null) is not a decode failure
	if len(in) == 0 || string(in) == "null" {
		return nil
	}
	err := json.Unmarshal(in, &res)
	if err != nil {
		log.Printf("error unmarshaling AgentNodeType slice to int slice: %v", err)
		return nil
	}
	if len(res) == 0 {
		return nil
	}
	finalRes := []AgentNodeType{}
	for _, r := range res {
		finalRes = append(finalRes, AgentNodeType(r))
	}
	return finalRes
}
