// Code generated by nuzur go-code-gen. DO NOT EDIT.

package enums

import (
	"encoding/json"
	"github.com/guregu/null/v6"
	"log"
)

//go:generate go run github.com/dmarkham/enumer -type=AgentEdgeType -json
type AgentEdgeType int64

const (
	AGENT_EDGE_TYPE_INVALID = iota
	AGENT_EDGE_TYPE_DEPENDENCY
	AGENT_EDGE_TYPE_TRANSITION
	AGENT_EDGE_TYPE_CONDITIONAL
	AGENT_EDGE_TYPE_RETRY
	AGENT_EDGE_TYPE_FALLBACK
	AGENT_EDGE_TYPE_SUBAGENT_SPAWN
)

func (e AgentEdgeType) ToInt64() int64 {
	return int64(e)
}

func (e AgentEdgeType) ToNullInt() null.Int {
	return null.NewInt(int64(e), true)
}

func AgentEdgeTypeFromString(in string) AgentEdgeType {
	switch in {
	case "invalid":
		return AGENT_EDGE_TYPE_INVALID
	case "dependency":
		return AGENT_EDGE_TYPE_DEPENDENCY
	case "transition":
		return AGENT_EDGE_TYPE_TRANSITION
	case "conditional":
		return AGENT_EDGE_TYPE_CONDITIONAL
	case "retry":
		return AGENT_EDGE_TYPE_RETRY
	case "fallback":
		return AGENT_EDGE_TYPE_FALLBACK
	case "subagent_spawn":
		return AGENT_EDGE_TYPE_SUBAGENT_SPAWN
	}
	return AGENT_EDGE_TYPE_INVALID
}

func AgentEdgeTypeFromPointerString(in *string) AgentEdgeType {
	if in == nil {
		return AGENT_EDGE_TYPE_INVALID
	}
	return AgentEdgeTypeFromString(*in)
}

func (e AgentEdgeType) String() string {
	switch e {
	case AGENT_EDGE_TYPE_INVALID:
		return "invalid"
	case AGENT_EDGE_TYPE_DEPENDENCY:
		return "dependency"
	case AGENT_EDGE_TYPE_TRANSITION:
		return "transition"
	case AGENT_EDGE_TYPE_CONDITIONAL:
		return "conditional"
	case AGENT_EDGE_TYPE_RETRY:
		return "retry"
	case AGENT_EDGE_TYPE_FALLBACK:
		return "fallback"
	case AGENT_EDGE_TYPE_SUBAGENT_SPAWN:
		return "subagent_spawn"
	}

	return "invalid"
}

func (e AgentEdgeType) StringPtr() *string {
	val := e.String()
	return &val
}

func AgentEdgeTypeSliceToJSON(in []AgentEdgeType) json.RawMessage {
	res := make([]int64, len(in))
	for i, e := range in {
		res[i] = int64(e)
	}
	jr, err := json.Marshal(res)
	if err != nil {
		log.Printf("error marshaling AgentEdgeType slice to json: %v", err)
		// the empty ARRAY, not a zero-length RawMessage: the latter reaches the
		// driver as an empty string, which no JSON column accepts
		return json.RawMessage("[]")
	}
	return jr
}

func JSONToAgentEdgeTypeSlice(in []byte) []AgentEdgeType {
	res := []int64{}
	// an absent column (NULL / empty / JSON null) is not a decode failure
	if len(in) == 0 || string(in) == "null" {
		return nil
	}
	err := json.Unmarshal(in, &res)
	if err != nil {
		log.Printf("error unmarshaling AgentEdgeType slice to int slice: %v", err)
		return nil
	}
	if len(res) == 0 {
		return nil
	}
	finalRes := []AgentEdgeType{}
	for _, r := range res {
		finalRes = append(finalRes, AgentEdgeType(r))
	}
	return finalRes
}
