// Code generated by nuzur go-code-gen. DO NOT EDIT.

package enums

import (
	"encoding/json"
	"github.com/guregu/null/v6"
	"log"
)

//go:generate go run github.com/dmarkham/enumer -type=AgentRunStatus -json
type AgentRunStatus int64

const (
	AGENT_RUN_STATUS_INVALID = iota
	AGENT_RUN_STATUS_IN_PROGRESS
	AGENT_RUN_STATUS_FAILED
	AGENT_RUN_STATUS_BLOCKED_ON_USER_DECISION
	AGENT_RUN_STATUS_BLOCKED_ON_MISSING_DATA
	AGENT_RUN_STATUS_BLOCKED_ON_PROVIDER_OUTAGE
	AGENT_RUN_STATUS_SUCCEEDED
	AGENT_RUN_STATUS_PENDING
	AGENT_RUN_STATUS_CANCELLED
)

func (e AgentRunStatus) ToInt64() int64 {
	return int64(e)
}

func (e AgentRunStatus) ToNullInt() null.Int {
	return null.NewInt(int64(e), true)
}

func AgentRunStatusFromString(in string) AgentRunStatus {
	switch in {
	case "invalid":
		return AGENT_RUN_STATUS_INVALID
	case "in_progress":
		return AGENT_RUN_STATUS_IN_PROGRESS
	case "failed":
		return AGENT_RUN_STATUS_FAILED
	case "blocked_on_user_decision":
		return AGENT_RUN_STATUS_BLOCKED_ON_USER_DECISION
	case "blocked_on_missing_data":
		return AGENT_RUN_STATUS_BLOCKED_ON_MISSING_DATA
	case "blocked_on_provider_outage":
		return AGENT_RUN_STATUS_BLOCKED_ON_PROVIDER_OUTAGE
	case "succeeded":
		return AGENT_RUN_STATUS_SUCCEEDED
	case "pending":
		return AGENT_RUN_STATUS_PENDING
	case "cancelled":
		return AGENT_RUN_STATUS_CANCELLED
	}
	return AGENT_RUN_STATUS_INVALID
}

func AgentRunStatusFromPointerString(in *string) AgentRunStatus {
	if in == nil {
		return AGENT_RUN_STATUS_INVALID
	}
	return AgentRunStatusFromString(*in)
}

func (e AgentRunStatus) String() string {
	switch e {
	case AGENT_RUN_STATUS_INVALID:
		return "invalid"
	case AGENT_RUN_STATUS_IN_PROGRESS:
		return "in_progress"
	case AGENT_RUN_STATUS_FAILED:
		return "failed"
	case AGENT_RUN_STATUS_BLOCKED_ON_USER_DECISION:
		return "blocked_on_user_decision"
	case AGENT_RUN_STATUS_BLOCKED_ON_MISSING_DATA:
		return "blocked_on_missing_data"
	case AGENT_RUN_STATUS_BLOCKED_ON_PROVIDER_OUTAGE:
		return "blocked_on_provider_outage"
	case AGENT_RUN_STATUS_SUCCEEDED:
		return "succeeded"
	case AGENT_RUN_STATUS_PENDING:
		return "pending"
	case AGENT_RUN_STATUS_CANCELLED:
		return "cancelled"
	}

	return "invalid"
}

func (e AgentRunStatus) StringPtr() *string {
	val := e.String()
	return &val
}

func AgentRunStatusSliceToJSON(in []AgentRunStatus) json.RawMessage {
	res := make([]int64, len(in))
	for i, e := range in {
		res[i] = int64(e)
	}
	jr, err := json.Marshal(res)
	if err != nil {
		log.Printf("error marshaling AgentRunStatus slice to json: %v", err)
		// the empty ARRAY, not a zero-length RawMessage: the latter reaches the
		// driver as an empty string, which no JSON column accepts
		return json.RawMessage("[]")
	}
	return jr
}

func JSONToAgentRunStatusSlice(in []byte) []AgentRunStatus {
	res := []int64{}
	// an absent column (NULL / empty / JSON null) is not a decode failure
	if len(in) == 0 || string(in) == "null" {
		return nil
	}
	err := json.Unmarshal(in, &res)
	if err != nil {
		log.Printf("error unmarshaling AgentRunStatus slice to int slice: %v", err)
		return nil
	}
	if len(res) == 0 {
		return nil
	}
	finalRes := []AgentRunStatus{}
	for _, r := range res {
		finalRes = append(finalRes, AgentRunStatus(r))
	}
	return finalRes
}
