// Code generated by nuzur go-code-gen. DO NOT EDIT.

package enums

import (
	"encoding/json"
	"github.com/guregu/null/v6"
	"log"
)

//go:generate go run github.com/dmarkham/enumer -type=AgentEventStatus -json
type AgentEventStatus int64

const (
	AGENT_EVENT_STATUS_INVALID = iota
	AGENT_EVENT_STATUS_RECORDED
	AGENT_EVENT_STATUS_DISCARDED
)

func (e AgentEventStatus) ToInt64() int64 {
	return int64(e)
}

func (e AgentEventStatus) ToNullInt() null.Int {
	return null.NewInt(int64(e), true)
}

func AgentEventStatusFromString(in string) AgentEventStatus {
	switch in {
	case "invalid":
		return AGENT_EVENT_STATUS_INVALID
	case "recorded":
		return AGENT_EVENT_STATUS_RECORDED
	case "discarded":
		return AGENT_EVENT_STATUS_DISCARDED
	}
	return AGENT_EVENT_STATUS_INVALID
}

func AgentEventStatusFromPointerString(in *string) AgentEventStatus {
	if in == nil {
		return AGENT_EVENT_STATUS_INVALID
	}
	return AgentEventStatusFromString(*in)
}

func (e AgentEventStatus) String() string {
	switch e {
	case AGENT_EVENT_STATUS_INVALID:
		return "invalid"
	case AGENT_EVENT_STATUS_RECORDED:
		return "recorded"
	case AGENT_EVENT_STATUS_DISCARDED:
		return "discarded"
	}

	return "invalid"
}

func (e AgentEventStatus) StringPtr() *string {
	val := e.String()
	return &val
}

func AgentEventStatusSliceToJSON(in []AgentEventStatus) json.RawMessage {
	res := make([]int64, len(in))
	for i, e := range in {
		res[i] = int64(e)
	}
	jr, err := json.Marshal(res)
	if err != nil {
		log.Printf("error marshaling AgentEventStatus slice to json: %v", err)
		// the empty ARRAY, not a zero-length RawMessage: the latter reaches the
		// driver as an empty string, which no JSON column accepts
		return json.RawMessage("[]")
	}
	return jr
}

func JSONToAgentEventStatusSlice(in []byte) []AgentEventStatus {
	res := []int64{}
	// an absent column (NULL / empty / JSON null) is not a decode failure
	if len(in) == 0 || string(in) == "null" {
		return nil
	}
	err := json.Unmarshal(in, &res)
	if err != nil {
		log.Printf("error unmarshaling AgentEventStatus slice to int slice: %v", err)
		return nil
	}
	if len(res) == 0 {
		return nil
	}
	finalRes := []AgentEventStatus{}
	for _, r := range res {
		finalRes = append(finalRes, AgentEventStatus(r))
	}
	return finalRes
}
