// Code generated by nuzur go-code-gen. DO NOT EDIT.

package enums

import (
	"encoding/json"
	"github.com/guregu/null/v6"
	"log"
)

//go:generate go run github.com/dmarkham/enumer -type=AgentEdgeStatus -json
type AgentEdgeStatus int64

const (
	AGENT_EDGE_STATUS_INVALID = iota
	AGENT_EDGE_STATUS_PENDING
	AGENT_EDGE_STATUS_TRAVERSED
	AGENT_EDGE_STATUS_SKIPPED
	AGENT_EDGE_STATUS_REMOVED
)

func (e AgentEdgeStatus) ToInt64() int64 {
	return int64(e)
}

func (e AgentEdgeStatus) ToNullInt() null.Int {
	return null.NewInt(int64(e), true)
}

func AgentEdgeStatusFromString(in string) AgentEdgeStatus {
	switch in {
	case "invalid":
		return AGENT_EDGE_STATUS_INVALID
	case "pending":
		return AGENT_EDGE_STATUS_PENDING
	case "traversed":
		return AGENT_EDGE_STATUS_TRAVERSED
	case "skipped":
		return AGENT_EDGE_STATUS_SKIPPED
	case "removed":
		return AGENT_EDGE_STATUS_REMOVED
	}
	return AGENT_EDGE_STATUS_INVALID
}

func AgentEdgeStatusFromPointerString(in *string) AgentEdgeStatus {
	if in == nil {
		return AGENT_EDGE_STATUS_INVALID
	}
	return AgentEdgeStatusFromString(*in)
}

func (e AgentEdgeStatus) String() string {
	switch e {
	case AGENT_EDGE_STATUS_INVALID:
		return "invalid"
	case AGENT_EDGE_STATUS_PENDING:
		return "pending"
	case AGENT_EDGE_STATUS_TRAVERSED:
		return "traversed"
	case AGENT_EDGE_STATUS_SKIPPED:
		return "skipped"
	case AGENT_EDGE_STATUS_REMOVED:
		return "removed"
	}

	return "invalid"
}

func (e AgentEdgeStatus) StringPtr() *string {
	val := e.String()
	return &val
}

func AgentEdgeStatusSliceToJSON(in []AgentEdgeStatus) json.RawMessage {
	res := make([]int64, len(in))
	for i, e := range in {
		res[i] = int64(e)
	}
	jr, err := json.Marshal(res)
	if err != nil {
		log.Printf("error marshaling AgentEdgeStatus slice to json: %v", err)
		// the empty ARRAY, not a zero-length RawMessage: the latter reaches the
		// driver as an empty string, which no JSON column accepts
		return json.RawMessage("[]")
	}
	return jr
}

func JSONToAgentEdgeStatusSlice(in []byte) []AgentEdgeStatus {
	res := []int64{}
	// an absent column (NULL / empty / JSON null) is not a decode failure
	if len(in) == 0 || string(in) == "null" {
		return nil
	}
	err := json.Unmarshal(in, &res)
	if err != nil {
		log.Printf("error unmarshaling AgentEdgeStatus slice to int slice: %v", err)
		return nil
	}
	if len(res) == 0 {
		return nil
	}
	finalRes := []AgentEdgeStatus{}
	for _, r := range res {
		finalRes = append(finalRes, AgentEdgeStatus(r))
	}
	return finalRes
}
