// Code generated by nuzur go-code-gen. DO NOT EDIT.

package enums

import (
	"encoding/json"
	"github.com/guregu/null/v6"
	"log"
)

//go:generate go run github.com/dmarkham/enumer -type=ArtifactStatus -json
type ArtifactStatus int64

const (
	ARTIFACT_STATUS_INVALID = iota
	ARTIFACT_STATUS_ACTIVE
	ARTIFACT_STATUS_INACTIVE
)

func (e ArtifactStatus) ToInt64() int64 {
	return int64(e)
}

func (e ArtifactStatus) ToNullInt() null.Int {
	return null.NewInt(int64(e), true)
}

func ArtifactStatusFromString(in string) ArtifactStatus {
	switch in {
	case "invalid":
		return ARTIFACT_STATUS_INVALID
	case "active":
		return ARTIFACT_STATUS_ACTIVE
	case "inactive":
		return ARTIFACT_STATUS_INACTIVE
	}
	return ARTIFACT_STATUS_INVALID
}

func ArtifactStatusFromPointerString(in *string) ArtifactStatus {
	if in == nil {
		return ARTIFACT_STATUS_INVALID
	}
	return ArtifactStatusFromString(*in)
}

func (e ArtifactStatus) String() string {
	switch e {
	case ARTIFACT_STATUS_INVALID:
		return "invalid"
	case ARTIFACT_STATUS_ACTIVE:
		return "active"
	case ARTIFACT_STATUS_INACTIVE:
		return "inactive"
	}

	return "invalid"
}

func (e ArtifactStatus) StringPtr() *string {
	val := e.String()
	return &val
}

func ArtifactStatusSliceToJSON(in []ArtifactStatus) json.RawMessage {
	res := make([]int64, len(in))
	for i, e := range in {
		res[i] = int64(e)
	}
	jr, err := json.Marshal(res)
	if err != nil {
		log.Printf("error marshaling ArtifactStatus slice to json: %v", err)
		// the empty ARRAY, not a zero-length RawMessage: the latter reaches the
		// driver as an empty string, which no JSON column accepts
		return json.RawMessage("[]")
	}
	return jr
}

func JSONToArtifactStatusSlice(in []byte) []ArtifactStatus {
	res := []int64{}
	// an absent column (NULL / empty / JSON null) is not a decode failure
	if len(in) == 0 || string(in) == "null" {
		return nil
	}
	err := json.Unmarshal(in, &res)
	if err != nil {
		log.Printf("error unmarshaling ArtifactStatus slice to int slice: %v", err)
		return nil
	}
	if len(res) == 0 {
		return nil
	}
	finalRes := []ArtifactStatus{}
	for _, r := range res {
		finalRes = append(finalRes, ArtifactStatus(r))
	}
	return finalRes
}
