// Code generated by nuzur go-code-gen. DO NOT EDIT.

package enums

import (
	"encoding/json"
	"github.com/guregu/null/v6"
	"log"
)

//go:generate go run github.com/dmarkham/enumer -type=ArtifactType -json
type ArtifactType int64

const (
	ARTIFACT_TYPE_INVALID = iota
	ARTIFACT_TYPE_FILE
	ARTIFACT_TYPE_IMAGE
	ARTIFACT_TYPE_VIDEO
	ARTIFACT_TYPE_AUDIO
	ARTIFACT_TYPE_LINK
	ARTIFACT_TYPE_TEXT
	ARTIFACT_TYPE_STRUCTURED_DATA
)

func (e ArtifactType) ToInt64() int64 {
	return int64(e)
}

func (e ArtifactType) ToNullInt() null.Int {
	return null.NewInt(int64(e), true)
}

func ArtifactTypeFromString(in string) ArtifactType {
	switch in {
	case "invalid":
		return ARTIFACT_TYPE_INVALID
	case "file":
		return ARTIFACT_TYPE_FILE
	case "image":
		return ARTIFACT_TYPE_IMAGE
	case "video":
		return ARTIFACT_TYPE_VIDEO
	case "audio":
		return ARTIFACT_TYPE_AUDIO
	case "link":
		return ARTIFACT_TYPE_LINK
	case "text":
		return ARTIFACT_TYPE_TEXT
	case "structured_data":
		return ARTIFACT_TYPE_STRUCTURED_DATA
	}
	return ARTIFACT_TYPE_INVALID
}

func ArtifactTypeFromPointerString(in *string) ArtifactType {
	if in == nil {
		return ARTIFACT_TYPE_INVALID
	}
	return ArtifactTypeFromString(*in)
}

func (e ArtifactType) String() string {
	switch e {
	case ARTIFACT_TYPE_INVALID:
		return "invalid"
	case ARTIFACT_TYPE_FILE:
		return "file"
	case ARTIFACT_TYPE_IMAGE:
		return "image"
	case ARTIFACT_TYPE_VIDEO:
		return "video"
	case ARTIFACT_TYPE_AUDIO:
		return "audio"
	case ARTIFACT_TYPE_LINK:
		return "link"
	case ARTIFACT_TYPE_TEXT:
		return "text"
	case ARTIFACT_TYPE_STRUCTURED_DATA:
		return "structured_data"
	}

	return "invalid"
}

func (e ArtifactType) StringPtr() *string {
	val := e.String()
	return &val
}

func ArtifactTypeSliceToJSON(in []ArtifactType) json.RawMessage {
	res := make([]int64, len(in))
	for i, e := range in {
		res[i] = int64(e)
	}
	jr, err := json.Marshal(res)
	if err != nil {
		log.Printf("error marshaling ArtifactType slice to json: %v", err)
		// the empty ARRAY, not a zero-length RawMessage: the latter reaches the
		// driver as an empty string, which no JSON column accepts
		return json.RawMessage("[]")
	}
	return jr
}

func JSONToArtifactTypeSlice(in []byte) []ArtifactType {
	res := []int64{}
	// an absent column (NULL / empty / JSON null) is not a decode failure
	if len(in) == 0 || string(in) == "null" {
		return nil
	}
	err := json.Unmarshal(in, &res)
	if err != nil {
		log.Printf("error unmarshaling ArtifactType slice to int slice: %v", err)
		return nil
	}
	if len(res) == 0 {
		return nil
	}
	finalRes := []ArtifactType{}
	for _, r := range res {
		finalRes = append(finalRes, ArtifactType(r))
	}
	return finalRes
}
