// Code generated by nuzur go-code-gen. DO NOT EDIT.

package enums

import (
	"encoding/json"
	"github.com/guregu/null/v6"
	"log"
)

//go:generate go run github.com/dmarkham/enumer -type=ClientStatus -json
type ClientStatus int64

const (
	CLIENT_STATUS_INVALID = iota
	CLIENT_STATUS_ACTIVE
	CLIENT_STATUS_INACTIVE
)

func (e ClientStatus) ToInt64() int64 {
	return int64(e)
}

func (e ClientStatus) ToNullInt() null.Int {
	return null.NewInt(int64(e), true)
}

func ClientStatusFromString(in string) ClientStatus {
	switch in {
	case "invalid":
		return CLIENT_STATUS_INVALID
	case "active":
		return CLIENT_STATUS_ACTIVE
	case "inactive":
		return CLIENT_STATUS_INACTIVE
	}
	return CLIENT_STATUS_INVALID
}

func ClientStatusFromPointerString(in *string) ClientStatus {
	if in == nil {
		return CLIENT_STATUS_INVALID
	}
	return ClientStatusFromString(*in)
}

func (e ClientStatus) String() string {
	switch e {
	case CLIENT_STATUS_INVALID:
		return "invalid"
	case CLIENT_STATUS_ACTIVE:
		return "active"
	case CLIENT_STATUS_INACTIVE:
		return "inactive"
	}

	return "invalid"
}

func (e ClientStatus) StringPtr() *string {
	val := e.String()
	return &val
}

func ClientStatusSliceToJSON(in []ClientStatus) json.RawMessage {
	res := make([]int64, len(in))
	for i, e := range in {
		res[i] = int64(e)
	}
	jr, err := json.Marshal(res)
	if err != nil {
		log.Printf("error marshaling ClientStatus slice to json: %v", err)
		// the empty ARRAY, not a zero-length RawMessage: the latter reaches the
		// driver as an empty string, which no JSON column accepts
		return json.RawMessage("[]")
	}
	return jr
}

func JSONToClientStatusSlice(in []byte) []ClientStatus {
	res := []int64{}
	// an absent column (NULL / empty / JSON null) is not a decode failure
	if len(in) == 0 || string(in) == "null" {
		return nil
	}
	err := json.Unmarshal(in, &res)
	if err != nil {
		log.Printf("error unmarshaling ClientStatus slice to int slice: %v", err)
		return nil
	}
	if len(res) == 0 {
		return nil
	}
	finalRes := []ClientStatus{}
	for _, r := range res {
		finalRes = append(finalRes, ClientStatus(r))
	}
	return finalRes
}
