// Code generated by nuzur go-code-gen. DO NOT EDIT.

package enums

import (
	"encoding/json"
	"github.com/guregu/null/v6"
	"log"
)

//go:generate go run github.com/dmarkham/enumer -type=ClientIndustry -json
type ClientIndustry int64

const (
	CLIENT_INDUSTRY_INVALID = iota
	CLIENT_INDUSTRY_FINTECH
	CLIENT_INDUSTRY_FURNITURE
)

func (e ClientIndustry) ToInt64() int64 {
	return int64(e)
}

func (e ClientIndustry) ToNullInt() null.Int {
	return null.NewInt(int64(e), true)
}

func ClientIndustryFromString(in string) ClientIndustry {
	switch in {
	case "invalid":
		return CLIENT_INDUSTRY_INVALID
	case "fintech":
		return CLIENT_INDUSTRY_FINTECH
	case "furniture":
		return CLIENT_INDUSTRY_FURNITURE
	}
	return CLIENT_INDUSTRY_INVALID
}

func ClientIndustryFromPointerString(in *string) ClientIndustry {
	if in == nil {
		return CLIENT_INDUSTRY_INVALID
	}
	return ClientIndustryFromString(*in)
}

func (e ClientIndustry) String() string {
	switch e {
	case CLIENT_INDUSTRY_INVALID:
		return "invalid"
	case CLIENT_INDUSTRY_FINTECH:
		return "fintech"
	case CLIENT_INDUSTRY_FURNITURE:
		return "furniture"
	}

	return "invalid"
}

func (e ClientIndustry) StringPtr() *string {
	val := e.String()
	return &val
}

func ClientIndustrySliceToJSON(in []ClientIndustry) json.RawMessage {
	res := make([]int64, len(in))
	for i, e := range in {
		res[i] = int64(e)
	}
	jr, err := json.Marshal(res)
	if err != nil {
		log.Printf("error marshaling ClientIndustry slice to json: %v", err)
		// the empty ARRAY, not a zero-length RawMessage: the latter reaches the
		// driver as an empty string, which no JSON column accepts
		return json.RawMessage("[]")
	}
	return jr
}

func JSONToClientIndustrySlice(in []byte) []ClientIndustry {
	res := []int64{}
	// an absent column (NULL / empty / JSON null) is not a decode failure
	if len(in) == 0 || string(in) == "null" {
		return nil
	}
	err := json.Unmarshal(in, &res)
	if err != nil {
		log.Printf("error unmarshaling ClientIndustry slice to int slice: %v", err)
		return nil
	}
	if len(res) == 0 {
		return nil
	}
	finalRes := []ClientIndustry{}
	for _, r := range res {
		finalRes = append(finalRes, ClientIndustry(r))
	}
	return finalRes
}
