// Code generated by nuzur go-code-gen. DO NOT EDIT.

package enums

import (
	"encoding/json"
	"github.com/guregu/null/v6"
	"log"
)

//go:generate go run github.com/dmarkham/enumer -type=InterventionStatus -json
type InterventionStatus int64

const (
	INTERVENTION_STATUS_INVALID = iota
	INTERVENTION_STATUS_REGISTERED
	INTERVENTION_STATUS_FAILED
	INTERVENTION_STATUS_SUCCEEDED
	INTERVENTION_STATUS_PICKED_UP_BY_AGENT
	INTERVENTION_STATUS_EXPIRED
	INTERVENTION_STATUS_WITHDRAWN
)

func (e InterventionStatus) ToInt64() int64 {
	return int64(e)
}

func (e InterventionStatus) ToNullInt() null.Int {
	return null.NewInt(int64(e), true)
}

func InterventionStatusFromString(in string) InterventionStatus {
	switch in {
	case "invalid":
		return INTERVENTION_STATUS_INVALID
	case "registered":
		return INTERVENTION_STATUS_REGISTERED
	case "failed":
		return INTERVENTION_STATUS_FAILED
	case "succeeded":
		return INTERVENTION_STATUS_SUCCEEDED
	case "picked_up_by_agent":
		return INTERVENTION_STATUS_PICKED_UP_BY_AGENT
	case "expired":
		return INTERVENTION_STATUS_EXPIRED
	case "withdrawn":
		return INTERVENTION_STATUS_WITHDRAWN
	}
	return INTERVENTION_STATUS_INVALID
}

func InterventionStatusFromPointerString(in *string) InterventionStatus {
	if in == nil {
		return INTERVENTION_STATUS_INVALID
	}
	return InterventionStatusFromString(*in)
}

func (e InterventionStatus) String() string {
	switch e {
	case INTERVENTION_STATUS_INVALID:
		return "invalid"
	case INTERVENTION_STATUS_REGISTERED:
		return "registered"
	case INTERVENTION_STATUS_FAILED:
		return "failed"
	case INTERVENTION_STATUS_SUCCEEDED:
		return "succeeded"
	case INTERVENTION_STATUS_PICKED_UP_BY_AGENT:
		return "picked_up_by_agent"
	case INTERVENTION_STATUS_EXPIRED:
		return "expired"
	case INTERVENTION_STATUS_WITHDRAWN:
		return "withdrawn"
	}

	return "invalid"
}

func (e InterventionStatus) StringPtr() *string {
	val := e.String()
	return &val
}

func InterventionStatusSliceToJSON(in []InterventionStatus) json.RawMessage {
	res := make([]int64, len(in))
	for i, e := range in {
		res[i] = int64(e)
	}
	jr, err := json.Marshal(res)
	if err != nil {
		log.Printf("error marshaling InterventionStatus slice to json: %v", err)
		// the empty ARRAY, not a zero-length RawMessage: the latter reaches the
		// driver as an empty string, which no JSON column accepts
		return json.RawMessage("[]")
	}
	return jr
}

func JSONToInterventionStatusSlice(in []byte) []InterventionStatus {
	res := []int64{}
	// an absent column (NULL / empty / JSON null) is not a decode failure
	if len(in) == 0 || string(in) == "null" {
		return nil
	}
	err := json.Unmarshal(in, &res)
	if err != nil {
		log.Printf("error unmarshaling InterventionStatus slice to int slice: %v", err)
		return nil
	}
	if len(res) == 0 {
		return nil
	}
	finalRes := []InterventionStatus{}
	for _, r := range res {
		finalRes = append(finalRes, InterventionStatus(r))
	}
	return finalRes
}
