// Code generated by nuzur go-code-gen. DO NOT EDIT.

package enums

import (
	"encoding/json"
	"github.com/guregu/null/v6"
	"log"
)

//go:generate go run github.com/dmarkham/enumer -type=InterventionType -json
type InterventionType int64

const (
	INTERVENTION_TYPE_INVALID = iota
	INTERVENTION_TYPE_STOP
	INTERVENTION_TYPE_STEER
)

func (e InterventionType) ToInt64() int64 {
	return int64(e)
}

func (e InterventionType) ToNullInt() null.Int {
	return null.NewInt(int64(e), true)
}

func InterventionTypeFromString(in string) InterventionType {
	switch in {
	case "invalid":
		return INTERVENTION_TYPE_INVALID
	case "stop":
		return INTERVENTION_TYPE_STOP
	case "steer":
		return INTERVENTION_TYPE_STEER
	}
	return INTERVENTION_TYPE_INVALID
}

func InterventionTypeFromPointerString(in *string) InterventionType {
	if in == nil {
		return INTERVENTION_TYPE_INVALID
	}
	return InterventionTypeFromString(*in)
}

func (e InterventionType) String() string {
	switch e {
	case INTERVENTION_TYPE_INVALID:
		return "invalid"
	case INTERVENTION_TYPE_STOP:
		return "stop"
	case INTERVENTION_TYPE_STEER:
		return "steer"
	}

	return "invalid"
}

func (e InterventionType) StringPtr() *string {
	val := e.String()
	return &val
}

func InterventionTypeSliceToJSON(in []InterventionType) json.RawMessage {
	res := make([]int64, len(in))
	for i, e := range in {
		res[i] = int64(e)
	}
	jr, err := json.Marshal(res)
	if err != nil {
		log.Printf("error marshaling InterventionType slice to json: %v", err)
		// the empty ARRAY, not a zero-length RawMessage: the latter reaches the
		// driver as an empty string, which no JSON column accepts
		return json.RawMessage("[]")
	}
	return jr
}

func JSONToInterventionTypeSlice(in []byte) []InterventionType {
	res := []int64{}
	// an absent column (NULL / empty / JSON null) is not a decode failure
	if len(in) == 0 || string(in) == "null" {
		return nil
	}
	err := json.Unmarshal(in, &res)
	if err != nil {
		log.Printf("error unmarshaling InterventionType slice to int slice: %v", err)
		return nil
	}
	if len(res) == 0 {
		return nil
	}
	finalRes := []InterventionType{}
	for _, r := range res {
		finalRes = append(finalRes, InterventionType(r))
	}
	return finalRes
}
