// Code generated by nuzur go-code-gen. DO NOT EDIT.

package enums

import (
	"encoding/json"
	"github.com/guregu/null/v6"
	"log"
)

//go:generate go run github.com/dmarkham/enumer -type=InterventionInteractionStatus -json
type InterventionInteractionStatus int64

const (
	INTERVENTION_INTERACTION_STATUS_INVALID = iota
	INTERVENTION_INTERACTION_STATUS_IN_PROGRESS
	INTERVENTION_INTERACTION_STATUS_COMPLETED
	INTERVENTION_INTERACTION_STATUS_FAILED
)

func (e InterventionInteractionStatus) ToInt64() int64 {
	return int64(e)
}

func (e InterventionInteractionStatus) ToNullInt() null.Int {
	return null.NewInt(int64(e), true)
}

func InterventionInteractionStatusFromString(in string) InterventionInteractionStatus {
	switch in {
	case "invalid":
		return INTERVENTION_INTERACTION_STATUS_INVALID
	case "in_progress":
		return INTERVENTION_INTERACTION_STATUS_IN_PROGRESS
	case "completed":
		return INTERVENTION_INTERACTION_STATUS_COMPLETED
	case "failed":
		return INTERVENTION_INTERACTION_STATUS_FAILED
	}
	return INTERVENTION_INTERACTION_STATUS_INVALID
}

func InterventionInteractionStatusFromPointerString(in *string) InterventionInteractionStatus {
	if in == nil {
		return INTERVENTION_INTERACTION_STATUS_INVALID
	}
	return InterventionInteractionStatusFromString(*in)
}

func (e InterventionInteractionStatus) String() string {
	switch e {
	case INTERVENTION_INTERACTION_STATUS_INVALID:
		return "invalid"
	case INTERVENTION_INTERACTION_STATUS_IN_PROGRESS:
		return "in_progress"
	case INTERVENTION_INTERACTION_STATUS_COMPLETED:
		return "completed"
	case INTERVENTION_INTERACTION_STATUS_FAILED:
		return "failed"
	}

	return "invalid"
}

func (e InterventionInteractionStatus) StringPtr() *string {
	val := e.String()
	return &val
}

func InterventionInteractionStatusSliceToJSON(in []InterventionInteractionStatus) json.RawMessage {
	res := make([]int64, len(in))
	for i, e := range in {
		res[i] = int64(e)
	}
	jr, err := json.Marshal(res)
	if err != nil {
		log.Printf("error marshaling InterventionInteractionStatus slice to json: %v", err)
		// the empty ARRAY, not a zero-length RawMessage: the latter reaches the
		// driver as an empty string, which no JSON column accepts
		return json.RawMessage("[]")
	}
	return jr
}

func JSONToInterventionInteractionStatusSlice(in []byte) []InterventionInteractionStatus {
	res := []int64{}
	// an absent column (NULL / empty / JSON null) is not a decode failure
	if len(in) == 0 || string(in) == "null" {
		return nil
	}
	err := json.Unmarshal(in, &res)
	if err != nil {
		log.Printf("error unmarshaling InterventionInteractionStatus slice to int slice: %v", err)
		return nil
	}
	if len(res) == 0 {
		return nil
	}
	finalRes := []InterventionInteractionStatus{}
	for _, r := range res {
		finalRes = append(finalRes, InterventionInteractionStatus(r))
	}
	return finalRes
}
