// Code generated by nuzur go-code-gen. DO NOT EDIT.

package intervention_interaction

import (
	"github.com/nextwave/donald/entity/validation"
)

// Validate checks this InterventionInteraction against the schema's field type and
// type-config rules, aggregating every problem into a single *validation.Error.
// It mirrors the change-request data validation enforced in
// product/module/datavalidation, so data written through this API is held to
// the same rules. Generated by go-code-gen — do not edit.
func (e InterventionInteraction) Validate() error {
	c := validation.NewCollector()
	if e.Name == "" {
		c.Require("intervention_interaction.name")
	} else {
		c.Field("intervention_interaction.name", validation.String(e.Name, 0, 255, ""))

	}
	if e.Status.ToInt64() != 0 {
		c.Field("intervention_interaction.status", validation.EnumMember(e.Status.ToInt64(), []int64{0, 1, 2, 3}, "intervention_interaction_status"))

	}

	return c.Result()
}
