// Code generated by nuzur go-code-gen. DO NOT EDIT.

package intervention_interaction

import (
	entitytypes "github.com/nextwave/donald/entity/types"
)

func (e InterventionInteraction) FieldIdentifierToTypeMap() map[string]entitytypes.FieldType {
	return map[string]entitytypes.FieldType{
		"name":            entitytypes.StringFieldType,
		"user_message":    entitytypes.StringFieldType,
		"agent_response":  entitytypes.StringFieldType,
		"followup_prompt": entitytypes.StringFieldType,
		"occurred_at":     entitytypes.TimestampFieldType,
		"status":          entitytypes.SingleEnumFieldType,
	}
}

func (e InterventionInteraction) OrderedFieldIdentifiers() []string {
	res := []string{}
	res = append(res, "name")
	res = append(res, "user_message")
	res = append(res, "agent_response")
	res = append(res, "followup_prompt")
	res = append(res, "occurred_at")
	res = append(res, "status")

	return res
}

func (e InterventionInteraction) DependantFieldIdentifierToTypeMap() map[string]map[string]entitytypes.FieldType {
	res := make(map[string]map[string]entitytypes.FieldType)

	return res
}

func (e InterventionInteraction) EntityIdentifier() string {
	return "intervention_interaction"
}

func (e InterventionInteraction) PrimaryKeyIdentifiers() []string {
	return []string{}
}

func (e InterventionInteraction) ArrayFieldIdentifierToType() map[string]entitytypes.FieldType {
	res := make(map[string]entitytypes.FieldType)

	return res
}
