// Code generated by nuzur go-code-gen. DO NOT EDIT.

package intervention_interaction

import (
	"encoding/json"
	"log"

	"github.com/guregu/null/v6"
	"github.com/nextwave/donald/enums"

	"github.com/nextwave/donald/entity/mapper"
)

type InterventionInteraction struct {
	Name           string                              `json:"name"`
	UserMessage    null.String                         `json:"user_message"`
	AgentResponse  null.String                         `json:"agent_response"`
	FollowupPrompt null.String                         `json:"followup_prompt"`
	OccurredAt     null.Time                           `json:"occurred_at"`
	Status         enums.InterventionInteractionStatus `json:"status"`
}

func (e InterventionInteraction) String() string {
	res, _ := json.Marshal(e)
	return string(res)
}

func (e InterventionInteraction) PrimaryKeyValues() []string {
	return []string{}
}

// The parameter is a plain []byte rather than json.RawMessage so that both a
// json.RawMessage and the mapper.JSON a repository model holds can be passed
// without a conversion at the call site.
func InterventionInteractionFromJSON(data []byte) InterventionInteraction {
	entity := InterventionInteraction{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		if err2 := mapper.FlexibleUnmarshal(data, &entity); err2 != nil {
			log.Printf("flexible unmarshal error InterventionInteractionFromJSON: %v\n", err2)
		}
	}
	return entity
}

func InterventionInteractionSliceFromJSON(data []byte) []InterventionInteraction {
	entity := []InterventionInteraction{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		entity = []InterventionInteraction{}
		var rawSlice []json.RawMessage
		if err2 := json.Unmarshal(data, &rawSlice); err2 == nil {
			for _, raw := range rawSlice {
				item := InterventionInteraction{}
				if err3 := mapper.FlexibleUnmarshal(raw, &item); err3 != nil {
					log.Printf("flexible unmarshal error InterventionInteractionSliceFromJSON item: %v\n", err3)
				}
				entity = append(entity, item)
			}
		}
	}
	return entity
}

func (e InterventionInteraction) ToJSON() json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error InterventionInteractionToJSON: %v\n", err)
		return json.RawMessage("null")
	}
	return res
}

func InterventionInteractionToJSON(e InterventionInteraction) json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error InterventionInteractionToJSON: %v\n", err)
		return json.RawMessage("null")
	}
	return res
}

// InterventionInteractionSliceToJSON serializes a ONE_TO_MANY embed for its JSON column.
// An absent embed is the EMPTY ARRAY, never a zero-length json.RawMessage: a
// zero-length value reaches the driver as the empty string, which is not valid
// JSON, so a create that simply omitted an optional array embed was rejected by
// the database ("invalid input syntax for type json", MySQL error 3140) and
// surfaced as a 500. "[]" is also exactly what an explicit `"field": []` stores,
// so the omitted and the explicitly-empty request round-trip to the same value.
func InterventionInteractionSliceToJSON(e []InterventionInteraction) json.RawMessage {
	if e == nil {
		return json.RawMessage("[]")
	}
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error InterventionInteractionSliceToJSON: %v\n", err)
		return json.RawMessage("[]")
	}
	return res
}
