// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nextwave/donald/entity/agent_run"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchAgentRunByUUIDRequest struct {
	UUID uuid.UUID
}

func (r FetchAgentRunByUUIDRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("uuid", r.UUID.String())

	return nil
}

type FetchAgentRunByUUIDResponse struct {
	Results []main_entity.AgentRun
}
