// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nextwave/donald/entity/agent_run"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchAgentRunByClientUUIDAndRunKeyRequest struct {
	ClientUUID uuid.UUID
	RunKey     string

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchAgentRunByClientUUIDAndRunKeyRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("client_uuid", r.ClientUUID.String())

	return nil
}

type FetchAgentRunByClientUUIDAndRunKeyResponse struct {
	Results []main_entity.AgentRun
}
