// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nextwave/donald/entity/agent_run"

	"github.com/gofrs/uuid"
	"github.com/nextwave/donald/enums"
	"go.uber.org/zap/zapcore"
)

type FetchAgentRunByClientUUIDAndStatusRequest struct {
	ClientUUID uuid.UUID
	Status     enums.AgentRunStatus

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchAgentRunByClientUUIDAndStatusRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("client_uuid", r.ClientUUID.String())

	return nil
}

type FetchAgentRunByClientUUIDAndStatusResponse struct {
	Results []main_entity.AgentRun
}
