// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nextwave/donald/entity/agent_run"

	"github.com/gofrs/uuid"
)

type UpsertRequest struct {
	AgentRun main_entity.AgentRun
}

type UpsertResponse struct {
	UUID uuid.UUID
}
