// Code generated by nuzur go-code-gen. DO NOT EDIT.

package main

import (
	donaldconfig "github.com/nextwave/donald/config"
	"github.com/nextwave/donald/core"
	"go.uber.org/fx"
	"go.uber.org/zap"

	restserver "github.com/nextwave/donald/rest/server"

	"github.com/nextwave/donald/app"

	"github.com/nextwave/donald/info"

	"github.com/nextwave/donald/storage"
)

func main() {
	fx.New(
		fx.Provide(
			zap.NewProduction,
			donaldconfig.New,
			core.New,

			app.ProvideCustomRoutes,
		),

		fx.Invoke(info.Register),

		fx.Invoke(storage.Register),

		fx.Invoke(app.RegisterWorkers),

		fx.Invoke(restserver.New),
	).Run()
}
