// Code generated by nuzur go-code-gen. DO NOT EDIT.

package agent_event

import (
	entitytypes "github.com/nextwave/donald/entity/types"

	"github.com/nextwave/donald/entity/agent_event_payload"
)

func (e AgentEvent) FieldIdentifierToTypeMap() map[string]entitytypes.FieldType {
	return map[string]entitytypes.FieldType{
		"uuid":            entitytypes.StringFieldType,
		"run_uuid":        entitytypes.StringFieldType,
		"sequence":        entitytypes.IntFieldType,
		"event_type":      entitytypes.SingleEnumFieldType,
		"node_uuid":       entitytypes.StringFieldType,
		"agent_label":     entitytypes.StringFieldType,
		"idempotency_key": entitytypes.StringFieldType,
		"occurred_at":     entitytypes.TimestampFieldType,
		"status":          entitytypes.SingleEnumFieldType,
		"created_by":      entitytypes.StringFieldType,
		"updated_by":      entitytypes.StringFieldType,
		"created_at":      entitytypes.TimestampFieldType,
		"updated_at":      entitytypes.TimestampFieldType,
		"payload":         entitytypes.SingleDependantEntityFieldType,
	}
}

func (e AgentEvent) OrderedFieldIdentifiers() []string {
	res := []string{}
	res = append(res, "uuid")
	res = append(res, "run_uuid")
	res = append(res, "sequence")
	res = append(res, "event_type")
	res = append(res, "node_uuid")
	res = append(res, "agent_label")
	res = append(res, "idempotency_key")
	res = append(res, "occurred_at")
	res = append(res, "status")
	res = append(res, "created_by")
	res = append(res, "updated_by")
	res = append(res, "created_at")
	res = append(res, "updated_at")
	res = append(res, "payload")

	return res
}

func (e AgentEvent) DependantFieldIdentifierToTypeMap() map[string]map[string]entitytypes.FieldType {
	res := make(map[string]map[string]entitytypes.FieldType)

	res["payload"] = agent_event_payload.AgentEventPayload{}.FieldIdentifierToTypeMap()
	return res
}

func (e AgentEvent) EntityIdentifier() string {
	return "agent_event"
}

func (e AgentEvent) PrimaryKeyIdentifiers() []string {
	return []string{
		"uuid",
	}
}

func (e AgentEvent) ArrayFieldIdentifierToType() map[string]entitytypes.FieldType {
	res := make(map[string]entitytypes.FieldType)

	return res
}
