// Code generated by nuzur go-code-gen. DO NOT EDIT.

package agent_event

import (
	"github.com/nextwave/donald/entity/validation"
)

// Validate checks this AgentEvent against the schema's field type and
// type-config rules, aggregating every problem into a single *validation.Error.
// It mirrors the change-request data validation enforced in
// product/module/datavalidation, so data written through this API is held to
// the same rules. Generated by go-code-gen — do not edit.
func (e AgentEvent) Validate() error {
	c := validation.NewCollector()
	if e.UUID.IsNil() {
		c.Require("agent_event.uuid")
	}
	if e.RunUUID.IsNil() {
		c.Require("agent_event.run_uuid")
	}
	c.Field("agent_event.sequence", validation.Integer(e.Sequence, false, 0, 0, false, false, false, true, -9223372036854775808, 9223372036854775807))
	if e.EventType.ToInt64() == 0 {
		c.Require("agent_event.event_type")
	} else {
		c.Field("agent_event.event_type", validation.EnumMember(e.EventType.ToInt64(), []int64{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17}, "agent_event_type"))

	}
	if e.AgentLabel.Valid && e.AgentLabel.String != "" {
		c.Field("agent_event.agent_label", validation.String(e.AgentLabel.String, 0, 120, ""))

	}
	if e.IdempotencyKey == "" {
		c.Require("agent_event.idempotency_key")
	} else {
		c.Field("agent_event.idempotency_key", validation.String(e.IdempotencyKey, 0, 255, ""))

	}
	if e.OccurredAt.IsZero() {
		c.Require("agent_event.occurred_at")
	}
	if e.Status.ToInt64() == 0 {
		c.Require("agent_event.status")
	} else {
		c.Field("agent_event.status", validation.EnumMember(e.Status.ToInt64(), []int64{0, 1, 2}, "agent_event_status"))

	}
	if e.CreatedBy.IsNil() {
		c.Require("agent_event.created_by")
	}
	if e.UpdatedBy.IsNil() {
		c.Require("agent_event.updated_by")
	}
	if !validation.IsZeroEntity(e.Payload) {
		c.Merge("agent_event.payload", e.Payload.Validate())
	}

	return c.Result()
}
