// Code generated by nuzur go-code-gen. DO NOT EDIT.

package server

import (
	"fmt"
	"log"
	"net/http"

	"go.einride.tech/aip/filtering"
	"go.einride.tech/aip/ordering"

	agent_eventmodule "github.com/nextwave/donald/core/module/agent_event"
	"github.com/nextwave/donald/core/module/agent_event/types"
	main_entity "github.com/nextwave/donald/entity/agent_event"
)

func (h *handlers) ListAgentEvent(w http.ResponseWriter, r *http.Request) {
	defaultPageSize := int32(10)
	maxPageSize := int32(100)

	lp, err := parseListParams(r, defaultPageSize, maxPageSize)
	if err != nil {
		writeProblem(w, http.StatusBadRequest, err)
		return
	}

	offset, err := parsePageTokenOffset(lp.pageToken)
	if err != nil {
		writeProblem(w, http.StatusBadRequest, fmt.Errorf("invalid page token: %w", err))
		return
	}

	declarations := agent_eventDeclarations()
	filter, err := filtering.ParseFilter(lp, declarations)
	if err != nil {
		writeProblem(w, http.StatusBadRequest, fmt.Errorf("invalid filter expression: %w", err))
		return
	}

	orderBy, err := ordering.ParseOrderBy(lp)
	if err != nil {
		writeProblem(w, http.StatusBadRequest, fmt.Errorf("invalid order_by expression: %w", err))
		return
	}

	req := types.ListRequest{
		Offset:                offset,
		PageSize:              lp.GetPageSize(),
		Filter:                filter,
		FilteringDeclarations: declarations,
		EnumValues:            agent_eventEnumValues(),
		OrderBy:               orderBy,
		IncludeFields:         lp.includeFields,
		ExcludeFields:         lp.excludeFields,
	}

	var result types.ListResponse
	if lp.skipCache {
		result, err = h.core.AgentEvent().List(r.Context(), req, agent_eventmodule.WithSkipCache())
	} else {
		result, err = h.core.AgentEvent().List(r.Context(), req)
	}
	if err != nil {
		// A filter or order_by the clause builder cannot express is the caller's
		// error, not the server's: statusForError turns it into a 400.
		writeProblem(w, statusForError(err), err)
		return
	}

	resp := ListEnvelope[main_entity.AgentEvent]{
		Items: result.AgentEvent,
	}
	if result.HasNextPage {
		resp.NextPageToken = encodePageToken(offset + int64(lp.GetPageSize()))
	}

	writeJSON(w, http.StatusOK, resp)
}

func agent_eventDeclarations() *filtering.Declarations {
	declarations, err := filtering.NewDeclarations(
		filtering.DeclareStandardFunctions(),
		filtering.DeclareIdent("true", filtering.TypeBool),
		filtering.DeclareIdent("false", filtering.TypeBool),

		// payload

		// An enum is filtered by its VALUE over REST — either quoted
		// (status = "active", matched case-insensitively against every spelling
		// in agent_eventEnumValues) or as the generated value name ident
		// (status = STATUS_ACTIVE, the same spelling gRPC accepts). Both are
		// strings to the type checker; the number they stand for is resolved
		// from the value table, not from this declaration.
		filtering.DeclareIdent("payload.previous_status", filtering.TypeString),
		filtering.DeclareIdent("AGENT_NODE_STATUS_INVALID", filtering.TypeString),
		filtering.DeclareIdent("AGENT_NODE_STATUS_NOT_STARTED", filtering.TypeString),
		filtering.DeclareIdent("AGENT_NODE_STATUS_IN_PROGRESS", filtering.TypeString),
		filtering.DeclareIdent("AGENT_NODE_STATUS_SUCCEEDED", filtering.TypeString),
		filtering.DeclareIdent("AGENT_NODE_STATUS_BLOCKED_ON_USER_DECISION", filtering.TypeString),
		filtering.DeclareIdent("AGENT_NODE_STATUS_BLOCKED_ON_MISSING_DATA", filtering.TypeString),
		filtering.DeclareIdent("AGENT_NODE_STATUS_BLOCKED_ON_PROVIDER_OUTAGE", filtering.TypeString),
		filtering.DeclareIdent("AGENT_NODE_STATUS_FAILED", filtering.TypeString),
		filtering.DeclareIdent("AGENT_NODE_STATUS_CANCELLED", filtering.TypeString),
		filtering.DeclareIdent("AGENT_NODE_STATUS_SKIPPED", filtering.TypeString),

		// An enum is filtered by its VALUE over REST — either quoted
		// (status = "active", matched case-insensitively against every spelling
		// in agent_eventEnumValues) or as the generated value name ident
		// (status = STATUS_ACTIVE, the same spelling gRPC accepts). Both are
		// strings to the type checker; the number they stand for is resolved
		// from the value table, not from this declaration.
		filtering.DeclareIdent("payload.new_status", filtering.TypeString),
		filtering.DeclareIdent("AGENT_NODE_STATUS_INVALID", filtering.TypeString),
		filtering.DeclareIdent("AGENT_NODE_STATUS_NOT_STARTED", filtering.TypeString),
		filtering.DeclareIdent("AGENT_NODE_STATUS_IN_PROGRESS", filtering.TypeString),
		filtering.DeclareIdent("AGENT_NODE_STATUS_SUCCEEDED", filtering.TypeString),
		filtering.DeclareIdent("AGENT_NODE_STATUS_BLOCKED_ON_USER_DECISION", filtering.TypeString),
		filtering.DeclareIdent("AGENT_NODE_STATUS_BLOCKED_ON_MISSING_DATA", filtering.TypeString),
		filtering.DeclareIdent("AGENT_NODE_STATUS_BLOCKED_ON_PROVIDER_OUTAGE", filtering.TypeString),
		filtering.DeclareIdent("AGENT_NODE_STATUS_FAILED", filtering.TypeString),
		filtering.DeclareIdent("AGENT_NODE_STATUS_CANCELLED", filtering.TypeString),
		filtering.DeclareIdent("AGENT_NODE_STATUS_SKIPPED", filtering.TypeString),

		filtering.DeclareIdent("payload.message", filtering.TypeString),

		filtering.DeclareIdent("payload.progress_percent", filtering.TypeInt),

		filtering.DeclareIdent("payload.edge_uuid", filtering.TypeString),

		filtering.DeclareIdent("payload.artifact_uuid", filtering.TypeString),

		filtering.DeclareIdent("payload.intervention_uuid", filtering.TypeString),

		filtering.DeclareIdent("payload.detail", filtering.TypeString),

		// agent_event

		filtering.DeclareIdent("uuid", filtering.TypeString),

		filtering.DeclareIdent("run_uuid", filtering.TypeString),

		filtering.DeclareIdent("sequence", filtering.TypeInt),

		// An enum is filtered by its VALUE over REST — either quoted
		// (status = "active", matched case-insensitively against every spelling
		// in agent_eventEnumValues) or as the generated value name ident
		// (status = STATUS_ACTIVE, the same spelling gRPC accepts). Both are
		// strings to the type checker; the number they stand for is resolved
		// from the value table, not from this declaration.
		filtering.DeclareIdent("event_type", filtering.TypeString),
		filtering.DeclareIdent("AGENT_EVENT_TYPE_INVALID", filtering.TypeString),
		filtering.DeclareIdent("AGENT_EVENT_TYPE_RUN_STARTED", filtering.TypeString),
		filtering.DeclareIdent("AGENT_EVENT_TYPE_RUN_UPDATED", filtering.TypeString),
		filtering.DeclareIdent("AGENT_EVENT_TYPE_RUN_FINISHED", filtering.TypeString),
		filtering.DeclareIdent("AGENT_EVENT_TYPE_PLAN_DECLARED", filtering.TypeString),
		filtering.DeclareIdent("AGENT_EVENT_TYPE_NODE_ADDED", filtering.TypeString),
		filtering.DeclareIdent("AGENT_EVENT_TYPE_NODE_UPDATED", filtering.TypeString),
		filtering.DeclareIdent("AGENT_EVENT_TYPE_NODE_STATUS_CHANGED", filtering.TypeString),
		filtering.DeclareIdent("AGENT_EVENT_TYPE_NODE_REMOVED", filtering.TypeString),
		filtering.DeclareIdent("AGENT_EVENT_TYPE_EDGE_ADDED", filtering.TypeString),
		filtering.DeclareIdent("AGENT_EVENT_TYPE_EDGE_UPDATED", filtering.TypeString),
		filtering.DeclareIdent("AGENT_EVENT_TYPE_EDGE_REMOVED", filtering.TypeString),
		filtering.DeclareIdent("AGENT_EVENT_TYPE_ARTIFACT_ADDED", filtering.TypeString),
		filtering.DeclareIdent("AGENT_EVENT_TYPE_INTERVENTION_REQUESTED", filtering.TypeString),
		filtering.DeclareIdent("AGENT_EVENT_TYPE_INTERVENTION_DELIVERED", filtering.TypeString),
		filtering.DeclareIdent("AGENT_EVENT_TYPE_INTERVENTION_RESOLVED", filtering.TypeString),
		filtering.DeclareIdent("AGENT_EVENT_TYPE_HEARTBEAT", filtering.TypeString),
		filtering.DeclareIdent("AGENT_EVENT_TYPE_AGENT_MESSAGE", filtering.TypeString),

		filtering.DeclareIdent("node_uuid", filtering.TypeString),

		filtering.DeclareIdent("agent_label", filtering.TypeString),

		filtering.DeclareIdent("idempotency_key", filtering.TypeString),

		filtering.DeclareIdent("occurred_at", filtering.TypeTimestamp),

		// An enum is filtered by its VALUE over REST — either quoted
		// (status = "active", matched case-insensitively against every spelling
		// in agent_eventEnumValues) or as the generated value name ident
		// (status = STATUS_ACTIVE, the same spelling gRPC accepts). Both are
		// strings to the type checker; the number they stand for is resolved
		// from the value table, not from this declaration.
		filtering.DeclareIdent("status", filtering.TypeString),
		filtering.DeclareIdent("AGENT_EVENT_STATUS_INVALID", filtering.TypeString),
		filtering.DeclareIdent("AGENT_EVENT_STATUS_RECORDED", filtering.TypeString),
		filtering.DeclareIdent("AGENT_EVENT_STATUS_DISCARDED", filtering.TypeString),

		filtering.DeclareIdent("created_by", filtering.TypeString),

		filtering.DeclareIdent("updated_by", filtering.TypeString),

		filtering.DeclareIdent("created_at", filtering.TypeTimestamp),

		filtering.DeclareIdent("updated_at", filtering.TypeTimestamp),
	)
	if err != nil {
		log.Printf("error creating declarations for agent_event: %v", err)
	}
	return declarations
}

// agent_eventEnumValues maps each enum filter field to every accepted
// spelling of its values and the number the column stores. REST generates no
// protobuf enum types (an app built with --api rest has no proto package at
// all), so this table — not the filter declarations — is what makes an enum
// filter resolvable here.
func agent_eventEnumValues() map[string]map[string]int64 {
	return map[string]map[string]int64{

		"payload.previous_status": {
			"invalid":                                      0,
			"AGENT_NODE_STATUS_INVALID":                    0,
			"not_started":                                  1,
			"AGENT_NODE_STATUS_NOT_STARTED":                1,
			"in_progress":                                  2,
			"AGENT_NODE_STATUS_IN_PROGRESS":                2,
			"succeeded":                                    3,
			"AGENT_NODE_STATUS_SUCCEEDED":                  3,
			"blocked_on_user_decision":                     4,
			"AGENT_NODE_STATUS_BLOCKED_ON_USER_DECISION":   4,
			"blocked_on_missing_data":                      5,
			"AGENT_NODE_STATUS_BLOCKED_ON_MISSING_DATA":    5,
			"blocked_on_provider_outage":                   6,
			"AGENT_NODE_STATUS_BLOCKED_ON_PROVIDER_OUTAGE": 6,
			"failed":                      7,
			"AGENT_NODE_STATUS_FAILED":    7,
			"cancelled":                   8,
			"AGENT_NODE_STATUS_CANCELLED": 8,
			"skipped":                     9,
			"AGENT_NODE_STATUS_SKIPPED":   9,
		},

		"payload.new_status": {
			"invalid":                                      0,
			"AGENT_NODE_STATUS_INVALID":                    0,
			"not_started":                                  1,
			"AGENT_NODE_STATUS_NOT_STARTED":                1,
			"in_progress":                                  2,
			"AGENT_NODE_STATUS_IN_PROGRESS":                2,
			"succeeded":                                    3,
			"AGENT_NODE_STATUS_SUCCEEDED":                  3,
			"blocked_on_user_decision":                     4,
			"AGENT_NODE_STATUS_BLOCKED_ON_USER_DECISION":   4,
			"blocked_on_missing_data":                      5,
			"AGENT_NODE_STATUS_BLOCKED_ON_MISSING_DATA":    5,
			"blocked_on_provider_outage":                   6,
			"AGENT_NODE_STATUS_BLOCKED_ON_PROVIDER_OUTAGE": 6,
			"failed":                      7,
			"AGENT_NODE_STATUS_FAILED":    7,
			"cancelled":                   8,
			"AGENT_NODE_STATUS_CANCELLED": 8,
			"skipped":                     9,
			"AGENT_NODE_STATUS_SKIPPED":   9,
		},

		"event_type": {
			"invalid":                                 0,
			"AGENT_EVENT_TYPE_INVALID":                0,
			"run_started":                             1,
			"AGENT_EVENT_TYPE_RUN_STARTED":            1,
			"run_updated":                             2,
			"AGENT_EVENT_TYPE_RUN_UPDATED":            2,
			"run_finished":                            3,
			"AGENT_EVENT_TYPE_RUN_FINISHED":           3,
			"plan_declared":                           4,
			"AGENT_EVENT_TYPE_PLAN_DECLARED":          4,
			"node_added":                              5,
			"AGENT_EVENT_TYPE_NODE_ADDED":             5,
			"node_updated":                            6,
			"AGENT_EVENT_TYPE_NODE_UPDATED":           6,
			"node_status_changed":                     7,
			"AGENT_EVENT_TYPE_NODE_STATUS_CHANGED":    7,
			"node_removed":                            8,
			"AGENT_EVENT_TYPE_NODE_REMOVED":           8,
			"edge_added":                              9,
			"AGENT_EVENT_TYPE_EDGE_ADDED":             9,
			"edge_updated":                            10,
			"AGENT_EVENT_TYPE_EDGE_UPDATED":           10,
			"edge_removed":                            11,
			"AGENT_EVENT_TYPE_EDGE_REMOVED":           11,
			"artifact_added":                          12,
			"AGENT_EVENT_TYPE_ARTIFACT_ADDED":         12,
			"intervention_requested":                  13,
			"AGENT_EVENT_TYPE_INTERVENTION_REQUESTED": 13,
			"intervention_delivered":                  14,
			"AGENT_EVENT_TYPE_INTERVENTION_DELIVERED": 14,
			"intervention_resolved":                   15,
			"AGENT_EVENT_TYPE_INTERVENTION_RESOLVED":  15,
			"heartbeat":                               16,
			"AGENT_EVENT_TYPE_HEARTBEAT":              16,
			"agent_message":                           17,
			"AGENT_EVENT_TYPE_AGENT_MESSAGE":          17,
		},

		"status": {
			"invalid":                      0,
			"AGENT_EVENT_STATUS_INVALID":   0,
			"recorded":                     1,
			"AGENT_EVENT_STATUS_RECORDED":  1,
			"discarded":                    2,
			"AGENT_EVENT_STATUS_DISCARDED": 2,
		},
	}
}
