// Code generated by nuzur go-code-gen. DO NOT EDIT.

package server

import (
	"fmt"
	"log"
	"net/http"

	"go.einride.tech/aip/filtering"
	"go.einride.tech/aip/ordering"

	interventionmodule "github.com/nextwave/donald/core/module/intervention"
	"github.com/nextwave/donald/core/module/intervention/types"
	main_entity "github.com/nextwave/donald/entity/intervention"
)

func (h *handlers) ListIntervention(w http.ResponseWriter, r *http.Request) {
	defaultPageSize := int32(10)
	maxPageSize := int32(100)

	lp, err := parseListParams(r, defaultPageSize, maxPageSize)
	if err != nil {
		writeProblem(w, http.StatusBadRequest, err)
		return
	}

	offset, err := parsePageTokenOffset(lp.pageToken)
	if err != nil {
		writeProblem(w, http.StatusBadRequest, fmt.Errorf("invalid page token: %w", err))
		return
	}

	declarations := interventionDeclarations()
	filter, err := filtering.ParseFilter(lp, declarations)
	if err != nil {
		writeProblem(w, http.StatusBadRequest, fmt.Errorf("invalid filter expression: %w", err))
		return
	}

	orderBy, err := ordering.ParseOrderBy(lp)
	if err != nil {
		writeProblem(w, http.StatusBadRequest, fmt.Errorf("invalid order_by expression: %w", err))
		return
	}

	req := types.ListRequest{
		Offset:                offset,
		PageSize:              lp.GetPageSize(),
		Filter:                filter,
		FilteringDeclarations: declarations,
		EnumValues:            interventionEnumValues(),
		OrderBy:               orderBy,
		IncludeFields:         lp.includeFields,
		ExcludeFields:         lp.excludeFields,
	}

	var result types.ListResponse
	if lp.skipCache {
		result, err = h.core.Intervention().List(r.Context(), req, interventionmodule.WithSkipCache())
	} else {
		result, err = h.core.Intervention().List(r.Context(), req)
	}
	if err != nil {
		// A filter or order_by the clause builder cannot express is the caller's
		// error, not the server's: statusForError turns it into a 400.
		writeProblem(w, statusForError(err), err)
		return
	}

	resp := ListEnvelope[main_entity.Intervention]{
		Items: result.Intervention,
	}
	if result.HasNextPage {
		resp.NextPageToken = encodePageToken(offset + int64(lp.GetPageSize()))
	}

	writeJSON(w, http.StatusOK, resp)
}

func interventionDeclarations() *filtering.Declarations {
	declarations, err := filtering.NewDeclarations(
		filtering.DeclareStandardFunctions(),
		filtering.DeclareIdent("true", filtering.TypeBool),
		filtering.DeclareIdent("false", filtering.TypeBool),

		// interactions

		filtering.DeclareIdent("interactions.name", filtering.TypeString),

		filtering.DeclareIdent("interactions.user_message", filtering.TypeString),

		filtering.DeclareIdent("interactions.agent_response", filtering.TypeString),

		filtering.DeclareIdent("interactions.followup_prompt", filtering.TypeString),

		filtering.DeclareIdent("interactions.occurred_at", filtering.TypeTimestamp),

		// An enum is filtered by its VALUE over REST — either quoted
		// (status = "active", matched case-insensitively against every spelling
		// in interventionEnumValues) or as the generated value name ident
		// (status = STATUS_ACTIVE, the same spelling gRPC accepts). Both are
		// strings to the type checker; the number they stand for is resolved
		// from the value table, not from this declaration.
		filtering.DeclareIdent("interactions.status", filtering.TypeString),
		filtering.DeclareIdent("INTERVENTION_INTERACTION_STATUS_INVALID", filtering.TypeString),
		filtering.DeclareIdent("INTERVENTION_INTERACTION_STATUS_IN_PROGRESS", filtering.TypeString),
		filtering.DeclareIdent("INTERVENTION_INTERACTION_STATUS_COMPLETED", filtering.TypeString),
		filtering.DeclareIdent("INTERVENTION_INTERACTION_STATUS_FAILED", filtering.TypeString),

		// intervention

		filtering.DeclareIdent("uuid", filtering.TypeString),

		filtering.DeclareIdent("run_uuid", filtering.TypeString),

		filtering.DeclareIdent("node_uuid", filtering.TypeString),

		// An enum is filtered by its VALUE over REST — either quoted
		// (status = "active", matched case-insensitively against every spelling
		// in interventionEnumValues) or as the generated value name ident
		// (status = STATUS_ACTIVE, the same spelling gRPC accepts). Both are
		// strings to the type checker; the number they stand for is resolved
		// from the value table, not from this declaration.
		filtering.DeclareIdent("type", filtering.TypeString),
		filtering.DeclareIdent("INTERVENTION_TYPE_INVALID", filtering.TypeString),
		filtering.DeclareIdent("INTERVENTION_TYPE_STOP", filtering.TypeString),
		filtering.DeclareIdent("INTERVENTION_TYPE_STEER", filtering.TypeString),

		filtering.DeclareIdent("prompt", filtering.TypeString),

		// An enum is filtered by its VALUE over REST — either quoted
		// (status = "active", matched case-insensitively against every spelling
		// in interventionEnumValues) or as the generated value name ident
		// (status = STATUS_ACTIVE, the same spelling gRPC accepts). Both are
		// strings to the type checker; the number they stand for is resolved
		// from the value table, not from this declaration.
		filtering.DeclareIdent("status", filtering.TypeString),
		filtering.DeclareIdent("INTERVENTION_STATUS_INVALID", filtering.TypeString),
		filtering.DeclareIdent("INTERVENTION_STATUS_REGISTERED", filtering.TypeString),
		filtering.DeclareIdent("INTERVENTION_STATUS_FAILED", filtering.TypeString),
		filtering.DeclareIdent("INTERVENTION_STATUS_SUCCEEDED", filtering.TypeString),
		filtering.DeclareIdent("INTERVENTION_STATUS_PICKED_UP_BY_AGENT", filtering.TypeString),
		filtering.DeclareIdent("INTERVENTION_STATUS_EXPIRED", filtering.TypeString),
		filtering.DeclareIdent("INTERVENTION_STATUS_WITHDRAWN", filtering.TypeString),

		filtering.DeclareIdent("status_message", filtering.TypeString),

		filtering.DeclareIdent("requested_by_uuid", filtering.TypeString),

		filtering.DeclareIdent("resolved_by_uuid", filtering.TypeString),

		filtering.DeclareIdent("delivered_at", filtering.TypeTimestamp),

		filtering.DeclareIdent("resolved_at", filtering.TypeTimestamp),

		filtering.DeclareIdent("expires_at", filtering.TypeTimestamp),

		filtering.DeclareIdent("created_by", filtering.TypeString),

		filtering.DeclareIdent("updated_by", filtering.TypeString),

		filtering.DeclareIdent("created_at", filtering.TypeTimestamp),

		filtering.DeclareIdent("updated_at", filtering.TypeTimestamp),
	)
	if err != nil {
		log.Printf("error creating declarations for intervention: %v", err)
	}
	return declarations
}

// interventionEnumValues maps each enum filter field to every accepted
// spelling of its values and the number the column stores. REST generates no
// protobuf enum types (an app built with --api rest has no proto package at
// all), so this table — not the filter declarations — is what makes an enum
// filter resolvable here.
func interventionEnumValues() map[string]map[string]int64 {
	return map[string]map[string]int64{

		"interactions.status": {
			"invalid": 0,
			"INTERVENTION_INTERACTION_STATUS_INVALID": 0,
			"in_progress": 1,
			"INTERVENTION_INTERACTION_STATUS_IN_PROGRESS": 1,
			"completed": 2,
			"INTERVENTION_INTERACTION_STATUS_COMPLETED": 2,
			"failed":                                 3,
			"INTERVENTION_INTERACTION_STATUS_FAILED": 3,
		},

		"type": {
			"invalid":                   0,
			"INTERVENTION_TYPE_INVALID": 0,
			"stop":                      1,
			"INTERVENTION_TYPE_STOP":    1,
			"steer":                     2,
			"INTERVENTION_TYPE_STEER":   2,
		},

		"status": {
			"invalid":                                0,
			"INTERVENTION_STATUS_INVALID":            0,
			"registered":                             1,
			"INTERVENTION_STATUS_REGISTERED":         1,
			"failed":                                 2,
			"INTERVENTION_STATUS_FAILED":             2,
			"succeeded":                              3,
			"INTERVENTION_STATUS_SUCCEEDED":          3,
			"picked_up_by_agent":                     4,
			"INTERVENTION_STATUS_PICKED_UP_BY_AGENT": 4,
			"expired":                                5,
			"INTERVENTION_STATUS_EXPIRED":            5,
			"withdrawn":                              6,
			"INTERVENTION_STATUS_WITHDRAWN":          6,
		},
	}
}
