// Code generated by nuzur go-code-gen. DO NOT EDIT.

package server

import (
	"fmt"
	"log"
	"net/http"

	"go.einride.tech/aip/filtering"
	"go.einride.tech/aip/ordering"

	agent_edgemodule "github.com/nextwave/donald/core/module/agent_edge"
	"github.com/nextwave/donald/core/module/agent_edge/types"
	main_entity "github.com/nextwave/donald/entity/agent_edge"
)

func (h *handlers) ListAgentEdge(w http.ResponseWriter, r *http.Request) {
	defaultPageSize := int32(10)
	maxPageSize := int32(100)

	lp, err := parseListParams(r, defaultPageSize, maxPageSize)
	if err != nil {
		writeProblem(w, http.StatusBadRequest, err)
		return
	}

	offset, err := parsePageTokenOffset(lp.pageToken)
	if err != nil {
		writeProblem(w, http.StatusBadRequest, fmt.Errorf("invalid page token: %w", err))
		return
	}

	declarations := agent_edgeDeclarations()
	filter, err := filtering.ParseFilter(lp, declarations)
	if err != nil {
		writeProblem(w, http.StatusBadRequest, fmt.Errorf("invalid filter expression: %w", err))
		return
	}

	orderBy, err := ordering.ParseOrderBy(lp)
	if err != nil {
		writeProblem(w, http.StatusBadRequest, fmt.Errorf("invalid order_by expression: %w", err))
		return
	}

	req := types.ListRequest{
		Offset:                offset,
		PageSize:              lp.GetPageSize(),
		Filter:                filter,
		FilteringDeclarations: declarations,
		EnumValues:            agent_edgeEnumValues(),
		OrderBy:               orderBy,
		IncludeFields:         lp.includeFields,
		ExcludeFields:         lp.excludeFields,
	}

	var result types.ListResponse
	if lp.skipCache {
		result, err = h.core.AgentEdge().List(r.Context(), req, agent_edgemodule.WithSkipCache())
	} else {
		result, err = h.core.AgentEdge().List(r.Context(), req)
	}
	if err != nil {
		// A filter or order_by the clause builder cannot express is the caller's
		// error, not the server's: statusForError turns it into a 400.
		writeProblem(w, statusForError(err), err)
		return
	}

	resp := ListEnvelope[main_entity.AgentEdge]{
		Items: result.AgentEdge,
	}
	if result.HasNextPage {
		resp.NextPageToken = encodePageToken(offset + int64(lp.GetPageSize()))
	}

	writeJSON(w, http.StatusOK, resp)
}

func agent_edgeDeclarations() *filtering.Declarations {
	declarations, err := filtering.NewDeclarations(
		filtering.DeclareStandardFunctions(),
		filtering.DeclareIdent("true", filtering.TypeBool),
		filtering.DeclareIdent("false", filtering.TypeBool),

		// agent_edge

		filtering.DeclareIdent("uuid", filtering.TypeString),

		filtering.DeclareIdent("run_uuid", filtering.TypeString),

		filtering.DeclareIdent("from_node_uuid", filtering.TypeString),

		filtering.DeclareIdent("to_node_uuid", filtering.TypeString),

		// An enum is filtered by its VALUE over REST — either quoted
		// (status = "active", matched case-insensitively against every spelling
		// in agent_edgeEnumValues) or as the generated value name ident
		// (status = STATUS_ACTIVE, the same spelling gRPC accepts). Both are
		// strings to the type checker; the number they stand for is resolved
		// from the value table, not from this declaration.
		filtering.DeclareIdent("edge_type", filtering.TypeString),
		filtering.DeclareIdent("AGENT_EDGE_TYPE_INVALID", filtering.TypeString),
		filtering.DeclareIdent("AGENT_EDGE_TYPE_DEPENDENCY", filtering.TypeString),
		filtering.DeclareIdent("AGENT_EDGE_TYPE_TRANSITION", filtering.TypeString),
		filtering.DeclareIdent("AGENT_EDGE_TYPE_CONDITIONAL", filtering.TypeString),
		filtering.DeclareIdent("AGENT_EDGE_TYPE_RETRY", filtering.TypeString),
		filtering.DeclareIdent("AGENT_EDGE_TYPE_FALLBACK", filtering.TypeString),
		filtering.DeclareIdent("AGENT_EDGE_TYPE_SUBAGENT_SPAWN", filtering.TypeString),

		filtering.DeclareIdent("condition_label", filtering.TypeString),

		// An enum is filtered by its VALUE over REST — either quoted
		// (status = "active", matched case-insensitively against every spelling
		// in agent_edgeEnumValues) or as the generated value name ident
		// (status = STATUS_ACTIVE, the same spelling gRPC accepts). Both are
		// strings to the type checker; the number they stand for is resolved
		// from the value table, not from this declaration.
		filtering.DeclareIdent("status", filtering.TypeString),
		filtering.DeclareIdent("AGENT_EDGE_STATUS_INVALID", filtering.TypeString),
		filtering.DeclareIdent("AGENT_EDGE_STATUS_PENDING", filtering.TypeString),
		filtering.DeclareIdent("AGENT_EDGE_STATUS_TRAVERSED", filtering.TypeString),
		filtering.DeclareIdent("AGENT_EDGE_STATUS_SKIPPED", filtering.TypeString),
		filtering.DeclareIdent("AGENT_EDGE_STATUS_REMOVED", filtering.TypeString),

		filtering.DeclareIdent("created_by", filtering.TypeString),

		filtering.DeclareIdent("updated_by", filtering.TypeString),

		filtering.DeclareIdent("created_at", filtering.TypeTimestamp),

		filtering.DeclareIdent("updated_at", filtering.TypeTimestamp),
	)
	if err != nil {
		log.Printf("error creating declarations for agent_edge: %v", err)
	}
	return declarations
}

// agent_edgeEnumValues maps each enum filter field to every accepted
// spelling of its values and the number the column stores. REST generates no
// protobuf enum types (an app built with --api rest has no proto package at
// all), so this table — not the filter declarations — is what makes an enum
// filter resolvable here.
func agent_edgeEnumValues() map[string]map[string]int64 {
	return map[string]map[string]int64{

		"edge_type": {
			"invalid":                        0,
			"AGENT_EDGE_TYPE_INVALID":        0,
			"dependency":                     1,
			"AGENT_EDGE_TYPE_DEPENDENCY":     1,
			"transition":                     2,
			"AGENT_EDGE_TYPE_TRANSITION":     2,
			"conditional":                    3,
			"AGENT_EDGE_TYPE_CONDITIONAL":    3,
			"retry":                          4,
			"AGENT_EDGE_TYPE_RETRY":          4,
			"fallback":                       5,
			"AGENT_EDGE_TYPE_FALLBACK":       5,
			"subagent_spawn":                 6,
			"AGENT_EDGE_TYPE_SUBAGENT_SPAWN": 6,
		},

		"status": {
			"invalid":                     0,
			"AGENT_EDGE_STATUS_INVALID":   0,
			"pending":                     1,
			"AGENT_EDGE_STATUS_PENDING":   1,
			"traversed":                   2,
			"AGENT_EDGE_STATUS_TRAVERSED": 2,
			"skipped":                     3,
			"AGENT_EDGE_STATUS_SKIPPED":   3,
			"removed":                     4,
			"AGENT_EDGE_STATUS_REMOVED":   4,
		},
	}
}
