// Code generated by nuzur go-code-gen. DO NOT EDIT.

package server

import (
	"fmt"
	"log"
	"net/http"

	"go.einride.tech/aip/filtering"
	"go.einride.tech/aip/ordering"

	artifactmodule "github.com/nextwave/donald/core/module/artifact"
	"github.com/nextwave/donald/core/module/artifact/types"
	main_entity "github.com/nextwave/donald/entity/artifact"
)

func (h *handlers) ListArtifact(w http.ResponseWriter, r *http.Request) {
	defaultPageSize := int32(10)
	maxPageSize := int32(100)

	lp, err := parseListParams(r, defaultPageSize, maxPageSize)
	if err != nil {
		writeProblem(w, http.StatusBadRequest, err)
		return
	}

	offset, err := parsePageTokenOffset(lp.pageToken)
	if err != nil {
		writeProblem(w, http.StatusBadRequest, fmt.Errorf("invalid page token: %w", err))
		return
	}

	declarations := artifactDeclarations()
	filter, err := filtering.ParseFilter(lp, declarations)
	if err != nil {
		writeProblem(w, http.StatusBadRequest, fmt.Errorf("invalid filter expression: %w", err))
		return
	}

	orderBy, err := ordering.ParseOrderBy(lp)
	if err != nil {
		writeProblem(w, http.StatusBadRequest, fmt.Errorf("invalid order_by expression: %w", err))
		return
	}

	req := types.ListRequest{
		Offset:                offset,
		PageSize:              lp.GetPageSize(),
		Filter:                filter,
		FilteringDeclarations: declarations,
		EnumValues:            artifactEnumValues(),
		OrderBy:               orderBy,
		IncludeFields:         lp.includeFields,
		ExcludeFields:         lp.excludeFields,
	}

	var result types.ListResponse
	if lp.skipCache {
		result, err = h.core.Artifact().List(r.Context(), req, artifactmodule.WithSkipCache())
	} else {
		result, err = h.core.Artifact().List(r.Context(), req)
	}
	if err != nil {
		// A filter or order_by the clause builder cannot express is the caller's
		// error, not the server's: statusForError turns it into a 400.
		writeProblem(w, statusForError(err), err)
		return
	}

	resp := ListEnvelope[main_entity.Artifact]{
		Items: result.Artifact,
	}
	if result.HasNextPage {
		resp.NextPageToken = encodePageToken(offset + int64(lp.GetPageSize()))
	}

	writeJSON(w, http.StatusOK, resp)
}

func artifactDeclarations() *filtering.Declarations {
	declarations, err := filtering.NewDeclarations(
		filtering.DeclareStandardFunctions(),
		filtering.DeclareIdent("true", filtering.TypeBool),
		filtering.DeclareIdent("false", filtering.TypeBool),

		// artifact

		filtering.DeclareIdent("uuid", filtering.TypeString),

		filtering.DeclareIdent("run_uuid", filtering.TypeString),

		filtering.DeclareIdent("node_uuid", filtering.TypeString),

		filtering.DeclareIdent("name", filtering.TypeString),

		// An enum is filtered by its VALUE over REST — either quoted
		// (status = "active", matched case-insensitively against every spelling
		// in artifactEnumValues) or as the generated value name ident
		// (status = STATUS_ACTIVE, the same spelling gRPC accepts). Both are
		// strings to the type checker; the number they stand for is resolved
		// from the value table, not from this declaration.
		filtering.DeclareIdent("artifact_type", filtering.TypeString),
		filtering.DeclareIdent("ARTIFACT_TYPE_INVALID", filtering.TypeString),
		filtering.DeclareIdent("ARTIFACT_TYPE_FILE", filtering.TypeString),
		filtering.DeclareIdent("ARTIFACT_TYPE_IMAGE", filtering.TypeString),
		filtering.DeclareIdent("ARTIFACT_TYPE_VIDEO", filtering.TypeString),
		filtering.DeclareIdent("ARTIFACT_TYPE_AUDIO", filtering.TypeString),
		filtering.DeclareIdent("ARTIFACT_TYPE_LINK", filtering.TypeString),
		filtering.DeclareIdent("ARTIFACT_TYPE_TEXT", filtering.TypeString),
		filtering.DeclareIdent("ARTIFACT_TYPE_STRUCTURED_DATA", filtering.TypeString),

		filtering.DeclareIdent("url", filtering.TypeString),

		filtering.DeclareIdent("content_type", filtering.TypeString),

		filtering.DeclareIdent("size_bytes", filtering.TypeInt),

		filtering.DeclareIdent("text_content", filtering.TypeString),

		// An enum is filtered by its VALUE over REST — either quoted
		// (status = "active", matched case-insensitively against every spelling
		// in artifactEnumValues) or as the generated value name ident
		// (status = STATUS_ACTIVE, the same spelling gRPC accepts). Both are
		// strings to the type checker; the number they stand for is resolved
		// from the value table, not from this declaration.
		filtering.DeclareIdent("status", filtering.TypeString),
		filtering.DeclareIdent("ARTIFACT_STATUS_INVALID", filtering.TypeString),
		filtering.DeclareIdent("ARTIFACT_STATUS_ACTIVE", filtering.TypeString),
		filtering.DeclareIdent("ARTIFACT_STATUS_INACTIVE", filtering.TypeString),

		filtering.DeclareIdent("created_by", filtering.TypeString),

		filtering.DeclareIdent("updated_by", filtering.TypeString),

		filtering.DeclareIdent("created_at", filtering.TypeTimestamp),

		filtering.DeclareIdent("updated_at", filtering.TypeTimestamp),
	)
	if err != nil {
		log.Printf("error creating declarations for artifact: %v", err)
	}
	return declarations
}

// artifactEnumValues maps each enum filter field to every accepted
// spelling of its values and the number the column stores. REST generates no
// protobuf enum types (an app built with --api rest has no proto package at
// all), so this table — not the filter declarations — is what makes an enum
// filter resolvable here.
func artifactEnumValues() map[string]map[string]int64 {
	return map[string]map[string]int64{

		"artifact_type": {
			"invalid":                       0,
			"ARTIFACT_TYPE_INVALID":         0,
			"file":                          1,
			"ARTIFACT_TYPE_FILE":            1,
			"image":                         2,
			"ARTIFACT_TYPE_IMAGE":           2,
			"video":                         3,
			"ARTIFACT_TYPE_VIDEO":           3,
			"audio":                         4,
			"ARTIFACT_TYPE_AUDIO":           4,
			"link":                          5,
			"ARTIFACT_TYPE_LINK":            5,
			"text":                          6,
			"ARTIFACT_TYPE_TEXT":            6,
			"structured_data":               7,
			"ARTIFACT_TYPE_STRUCTURED_DATA": 7,
		},

		"status": {
			"invalid":                  0,
			"ARTIFACT_STATUS_INVALID":  0,
			"active":                   1,
			"ARTIFACT_STATUS_ACTIVE":   1,
			"inactive":                 2,
			"ARTIFACT_STATUS_INACTIVE": 2,
		},
	}
}
