// Code generated by nuzur go-code-gen. DO NOT EDIT.

package server

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/gofrs/uuid"

	artifactmodule "github.com/nextwave/donald/core/module/artifact"
	"github.com/nextwave/donald/core/module/artifact/types"
	main_entity "github.com/nextwave/donald/entity/artifact"
)

func (h *handlers) UpdateArtifact(w http.ResponseWriter, r *http.Request) {

	UUIDStr := chi.URLParam(r, "id")
	UUIDVal, err := uuid.FromString(UUIDStr)
	if err != nil {
		writeProblem(w, http.StatusBadRequest, fmt.Errorf("invalid path parameter UUID: %w", err))
		return
	}

	fetchRes, err := h.core.Artifact().FetchArtifactByUUID(r.Context(), types.FetchArtifactByUUIDRequest{
		UUID: UUIDVal,
	}, artifactmodule.WithSkipCache())
	if err != nil {
		writeProblem(w, http.StatusInternalServerError, err)
		return
	}
	if len(fetchRes.Results) == 0 {
		writeProblem(w, http.StatusNotFound, errors.New("entity not found"))
		return
	}

	existingEntity := fetchRes.Results[0]

	body, err := io.ReadAll(r.Body)
	if err != nil {
		writeProblem(w, http.StatusBadRequest, err)
		return
	}

	if err := MergePatchArtifact(&existingEntity, body); err != nil {
		writeProblem(w, http.StatusBadRequest, err)
		return
	}

	// Path parameters are authoritative for the primary key(s).
	existingEntity.UUID = UUIDVal

	_, err = h.core.Artifact().Update(r.Context(), types.UpsertRequest{
		Artifact: existingEntity,
	})
	if err != nil {
		writeProblem(w, http.StatusInternalServerError, err)
		return
	}

	fetchResUpdated, err := h.core.Artifact().FetchArtifactByUUID(r.Context(), types.FetchArtifactByUUIDRequest{
		UUID: UUIDVal,
	}, artifactmodule.WithSkipCache())
	if err != nil {
		writeProblem(w, http.StatusInternalServerError, err)
		return
	}

	if len(fetchResUpdated.Results) == 0 {
		writeProblem(w, http.StatusInternalServerError, errors.New("entity not found after update"))
		return
	}

	writeJSON(w, http.StatusOK, fetchResUpdated.Results[0])
}

// MergePatchArtifact applies JSON merge-patch semantics: only the keys present
// in the request body overwrite the existing entity. It round-trips through the
// entity's own JSON tags so every field type (enums, nested entities, arrays)
// is handled without per-field reconstruction.
func MergePatchArtifact(existing *main_entity.Artifact, body []byte) error {
	var patch map[string]json.RawMessage
	if err := json.Unmarshal(body, &patch); err != nil {
		return fmt.Errorf("invalid request body: %w", err)
	}

	base, err := json.Marshal(existing)
	if err != nil {
		return err
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(base, &merged); err != nil {
		return err
	}

	for k, v := range patch {
		merged[k] = v
	}

	out, err := json.Marshal(merged)
	if err != nil {
		return err
	}
	return json.Unmarshal(out, existing)
}
