// Code generated by nuzur go-code-gen. DO NOT EDIT.

package server

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/gofrs/uuid"

	interventionmodule "github.com/nextwave/donald/core/module/intervention"
	"github.com/nextwave/donald/core/module/intervention/types"
	main_entity "github.com/nextwave/donald/entity/intervention"
)

func (h *handlers) UpdateIntervention(w http.ResponseWriter, r *http.Request) {

	UUIDStr := chi.URLParam(r, "id")
	UUIDVal, err := uuid.FromString(UUIDStr)
	if err != nil {
		writeProblem(w, http.StatusBadRequest, fmt.Errorf("invalid path parameter UUID: %w", err))
		return
	}

	fetchRes, err := h.core.Intervention().FetchInterventionByUUID(r.Context(), types.FetchInterventionByUUIDRequest{
		UUID: UUIDVal,
	}, interventionmodule.WithSkipCache())
	if err != nil {
		writeProblem(w, http.StatusInternalServerError, err)
		return
	}
	if len(fetchRes.Results) == 0 {
		writeProblem(w, http.StatusNotFound, errors.New("entity not found"))
		return
	}

	existingEntity := fetchRes.Results[0]

	body, err := io.ReadAll(r.Body)
	if err != nil {
		writeProblem(w, http.StatusBadRequest, err)
		return
	}

	if err := MergePatchIntervention(&existingEntity, body); err != nil {
		writeProblem(w, http.StatusBadRequest, err)
		return
	}

	// Path parameters are authoritative for the primary key(s).
	existingEntity.UUID = UUIDVal

	_, err = h.core.Intervention().Update(r.Context(), types.UpsertRequest{
		Intervention: existingEntity,
	})
	if err != nil {
		writeProblem(w, http.StatusInternalServerError, err)
		return
	}

	fetchResUpdated, err := h.core.Intervention().FetchInterventionByUUID(r.Context(), types.FetchInterventionByUUIDRequest{
		UUID: UUIDVal,
	}, interventionmodule.WithSkipCache())
	if err != nil {
		writeProblem(w, http.StatusInternalServerError, err)
		return
	}

	if len(fetchResUpdated.Results) == 0 {
		writeProblem(w, http.StatusInternalServerError, errors.New("entity not found after update"))
		return
	}

	writeJSON(w, http.StatusOK, fetchResUpdated.Results[0])
}

// MergePatchIntervention applies JSON merge-patch semantics: only the keys present
// in the request body overwrite the existing entity. It round-trips through the
// entity's own JSON tags so every field type (enums, nested entities, arrays)
// is handled without per-field reconstruction.
func MergePatchIntervention(existing *main_entity.Intervention, body []byte) error {
	var patch map[string]json.RawMessage
	if err := json.Unmarshal(body, &patch); err != nil {
		return fmt.Errorf("invalid request body: %w", err)
	}

	base, err := json.Marshal(existing)
	if err != nil {
		return err
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(base, &merged); err != nil {
		return err
	}

	for k, v := range patch {
		merged[k] = v
	}

	out, err := json.Marshal(merged)
	if err != nil {
		return err
	}
	return json.Unmarshal(out, existing)
}
