// Code generated by nuzur go-code-gen. DO NOT EDIT.

package client

import (
	"github.com/nextwave/donald/entity/validation"
)

// Validate checks this Client against the schema's field type and
// type-config rules, aggregating every problem into a single *validation.Error.
// It mirrors the change-request data validation enforced in
// product/module/datavalidation, so data written through this API is held to
// the same rules. Generated by go-code-gen — do not edit.
func (e Client) Validate() error {
	c := validation.NewCollector()
	if e.UUID.IsNil() {
		c.Require("client.uuid")
	}
	if e.Name == "" {
		c.Require("client.name")
	} else {
		c.Field("client.name", validation.String(e.Name, 0, 0, ""))

	}
	if e.Industry.ToInt64() != 0 {
		c.Field("client.industry", validation.EnumMember(e.Industry.ToInt64(), []int64{0, 1, 2}, "client_industry"))

	}
	if e.CreatedBy.IsNil() {
		c.Require("client.created_by")
	}
	if e.UpdatedBy.IsNil() {
		c.Require("client.updated_by")
	}
	if e.Status.ToInt64() == 0 {
		c.Require("client.status")
	} else {
		c.Field("client.status", validation.EnumMember(e.Status.ToInt64(), []int64{0, 1, 2}, "client_status"))

	}

	return c.Result()
}
