// Code generated by nuzur go-code-gen. DO NOT EDIT.

package client

import (
	entitytypes "github.com/nextwave/donald/entity/types"
)

func (e Client) FieldIdentifierToTypeMap() map[string]entitytypes.FieldType {
	return map[string]entitytypes.FieldType{
		"uuid":       entitytypes.StringFieldType,
		"name":       entitytypes.StringFieldType,
		"industry":   entitytypes.SingleEnumFieldType,
		"created_by": entitytypes.StringFieldType,
		"updated_by": entitytypes.StringFieldType,
		"status":     entitytypes.SingleEnumFieldType,
		"created_at": entitytypes.TimestampFieldType,
		"updated_at": entitytypes.TimestampFieldType,
	}
}

func (e Client) OrderedFieldIdentifiers() []string {
	res := []string{}
	res = append(res, "uuid")
	res = append(res, "name")
	res = append(res, "industry")
	res = append(res, "created_by")
	res = append(res, "updated_by")
	res = append(res, "status")
	res = append(res, "created_at")
	res = append(res, "updated_at")

	return res
}

func (e Client) DependantFieldIdentifierToTypeMap() map[string]map[string]entitytypes.FieldType {
	res := make(map[string]map[string]entitytypes.FieldType)

	return res
}

func (e Client) EntityIdentifier() string {
	return "client"
}

func (e Client) PrimaryKeyIdentifiers() []string {
	return []string{
		"uuid",
	}
}

func (e Client) ArrayFieldIdentifierToType() map[string]entitytypes.FieldType {
	res := make(map[string]entitytypes.FieldType)

	return res
}
