// Code generated by nuzur go-code-gen. DO NOT EDIT.

package client

import (
	"encoding/json"
	"log"

	"github.com/gofrs/uuid"
	"github.com/nextwave/donald/enums"
	"time"

	"github.com/nextwave/donald/entity/mapper"
)

type Client struct {
	UUID      uuid.UUID            `json:"uuid"`
	Name      string               `json:"name"`
	Industry  enums.ClientIndustry `json:"industry"`
	CreatedBy uuid.UUID            `json:"created_by"`
	UpdatedBy uuid.UUID            `json:"updated_by"`
	Status    enums.ClientStatus   `json:"status"`
	CreatedAt time.Time            `json:"created_at"`
	UpdatedAt time.Time            `json:"updated_at"`
}

func (e Client) String() string {
	res, _ := json.Marshal(e)
	return string(res)
}

func (e Client) PrimaryKeyValues() []string {
	return []string{
		e.UUID.String(),
	}
}

// The parameter is a plain []byte rather than json.RawMessage so that both a
// json.RawMessage and the mapper.JSON a repository model holds can be passed
// without a conversion at the call site.
func ClientFromJSON(data []byte) Client {
	entity := Client{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		if err2 := mapper.FlexibleUnmarshal(data, &entity); err2 != nil {
			log.Printf("flexible unmarshal error ClientFromJSON: %v\n", err2)
		}
	}
	return entity
}

func ClientSliceFromJSON(data []byte) []Client {
	entity := []Client{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		entity = []Client{}
		var rawSlice []json.RawMessage
		if err2 := json.Unmarshal(data, &rawSlice); err2 == nil {
			for _, raw := range rawSlice {
				item := Client{}
				if err3 := mapper.FlexibleUnmarshal(raw, &item); err3 != nil {
					log.Printf("flexible unmarshal error ClientSliceFromJSON item: %v\n", err3)
				}
				entity = append(entity, item)
			}
		}
	}
	return entity
}

func (e Client) ToJSON() json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error ClientToJSON: %v\n", err)
		return json.RawMessage("null")
	}
	return res
}

func ClientToJSON(e Client) json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error ClientToJSON: %v\n", err)
		return json.RawMessage("null")
	}
	return res
}

// ClientSliceToJSON serializes a ONE_TO_MANY embed for its JSON column.
// An absent embed is the EMPTY ARRAY, never a zero-length json.RawMessage: a
// zero-length value reaches the driver as the empty string, which is not valid
// JSON, so a create that simply omitted an optional array embed was rejected by
// the database ("invalid input syntax for type json", MySQL error 3140) and
// surfaced as a 500. "[]" is also exactly what an explicit `"field": []` stores,
// so the omitted and the explicitly-empty request round-trip to the same value.
func ClientSliceToJSON(e []Client) json.RawMessage {
	if e == nil {
		return json.RawMessage("[]")
	}
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error ClientSliceToJSON: %v\n", err)
		return json.RawMessage("[]")
	}
	return res
}
