// Code generated by nuzur go-code-gen. DO NOT EDIT.

package agent_run

import (
	"encoding/json"
	"log"

	"github.com/gofrs/uuid"
	"github.com/guregu/null/v6"
	"github.com/nextwave/donald/enums"
	"time"

	"github.com/nextwave/donald/entity/mapper"
)

type AgentRun struct {
	UUID              uuid.UUID            `json:"uuid"`
	ClientUUID        uuid.UUID            `json:"client_uuid"`
	RunKey            string               `json:"run_key"`
	Name              null.String          `json:"name"`
	DisplaySummary    null.String          `json:"display_summary"`
	AgentSummary      null.String          `json:"agent_summary"`
	AgentIdentifier   null.String          `json:"agent_identifier"`
	InitialPrompt     null.String          `json:"initial_prompt"`
	ProtocolVersion   null.String          `json:"protocol_version"`
	Status            enums.AgentRunStatus `json:"status"`
	StatusMessage     null.String          `json:"status_message"`
	GraphRevision     int64                `json:"graph_revision"`
	LastEventSequence int64                `json:"last_event_sequence"`
	StartedAt         null.Time            `json:"started_at"`
	FinishedAt        null.Time            `json:"finished_at"`
	LastHeartbeatAt   null.Time            `json:"last_heartbeat_at"`
	CreatedBy         uuid.UUID            `json:"created_by"`
	UpdatedBy         uuid.UUID            `json:"updated_by"`
	CreatedAt         time.Time            `json:"created_at"`
	UpdatedAt         time.Time            `json:"updated_at"`
}

func (e AgentRun) String() string {
	res, _ := json.Marshal(e)
	return string(res)
}

func (e AgentRun) PrimaryKeyValues() []string {
	return []string{
		e.UUID.String(),
	}
}

// The parameter is a plain []byte rather than json.RawMessage so that both a
// json.RawMessage and the mapper.JSON a repository model holds can be passed
// without a conversion at the call site.
func AgentRunFromJSON(data []byte) AgentRun {
	entity := AgentRun{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		if err2 := mapper.FlexibleUnmarshal(data, &entity); err2 != nil {
			log.Printf("flexible unmarshal error AgentRunFromJSON: %v\n", err2)
		}
	}
	return entity
}

func AgentRunSliceFromJSON(data []byte) []AgentRun {
	entity := []AgentRun{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		entity = []AgentRun{}
		var rawSlice []json.RawMessage
		if err2 := json.Unmarshal(data, &rawSlice); err2 == nil {
			for _, raw := range rawSlice {
				item := AgentRun{}
				if err3 := mapper.FlexibleUnmarshal(raw, &item); err3 != nil {
					log.Printf("flexible unmarshal error AgentRunSliceFromJSON item: %v\n", err3)
				}
				entity = append(entity, item)
			}
		}
	}
	return entity
}

func (e AgentRun) ToJSON() json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error AgentRunToJSON: %v\n", err)
		return json.RawMessage("null")
	}
	return res
}

func AgentRunToJSON(e AgentRun) json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error AgentRunToJSON: %v\n", err)
		return json.RawMessage("null")
	}
	return res
}

// AgentRunSliceToJSON serializes a ONE_TO_MANY embed for its JSON column.
// An absent embed is the EMPTY ARRAY, never a zero-length json.RawMessage: a
// zero-length value reaches the driver as the empty string, which is not valid
// JSON, so a create that simply omitted an optional array embed was rejected by
// the database ("invalid input syntax for type json", MySQL error 3140) and
// surfaced as a 500. "[]" is also exactly what an explicit `"field": []` stores,
// so the omitted and the explicitly-empty request round-trip to the same value.
func AgentRunSliceToJSON(e []AgentRun) json.RawMessage {
	if e == nil {
		return json.RawMessage("[]")
	}
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error AgentRunSliceToJSON: %v\n", err)
		return json.RawMessage("[]")
	}
	return res
}
