// Code generated by nuzur go-code-gen. DO NOT EDIT.

package agent_run

import (
	entitytypes "github.com/nextwave/donald/entity/types"
)

func (e AgentRun) FieldIdentifierToTypeMap() map[string]entitytypes.FieldType {
	return map[string]entitytypes.FieldType{
		"uuid":                entitytypes.StringFieldType,
		"client_uuid":         entitytypes.StringFieldType,
		"run_key":             entitytypes.StringFieldType,
		"name":                entitytypes.StringFieldType,
		"display_summary":     entitytypes.StringFieldType,
		"agent_summary":       entitytypes.StringFieldType,
		"agent_identifier":    entitytypes.StringFieldType,
		"initial_prompt":      entitytypes.StringFieldType,
		"protocol_version":    entitytypes.StringFieldType,
		"status":              entitytypes.SingleEnumFieldType,
		"status_message":      entitytypes.StringFieldType,
		"graph_revision":      entitytypes.IntFieldType,
		"last_event_sequence": entitytypes.IntFieldType,
		"started_at":          entitytypes.TimestampFieldType,
		"finished_at":         entitytypes.TimestampFieldType,
		"last_heartbeat_at":   entitytypes.TimestampFieldType,
		"created_by":          entitytypes.StringFieldType,
		"updated_by":          entitytypes.StringFieldType,
		"created_at":          entitytypes.TimestampFieldType,
		"updated_at":          entitytypes.TimestampFieldType,
	}
}

func (e AgentRun) OrderedFieldIdentifiers() []string {
	res := []string{}
	res = append(res, "uuid")
	res = append(res, "client_uuid")
	res = append(res, "run_key")
	res = append(res, "name")
	res = append(res, "display_summary")
	res = append(res, "agent_summary")
	res = append(res, "agent_identifier")
	res = append(res, "initial_prompt")
	res = append(res, "protocol_version")
	res = append(res, "status")
	res = append(res, "status_message")
	res = append(res, "graph_revision")
	res = append(res, "last_event_sequence")
	res = append(res, "started_at")
	res = append(res, "finished_at")
	res = append(res, "last_heartbeat_at")
	res = append(res, "created_by")
	res = append(res, "updated_by")
	res = append(res, "created_at")
	res = append(res, "updated_at")

	return res
}

func (e AgentRun) DependantFieldIdentifierToTypeMap() map[string]map[string]entitytypes.FieldType {
	res := make(map[string]map[string]entitytypes.FieldType)

	return res
}

func (e AgentRun) EntityIdentifier() string {
	return "agent_run"
}

func (e AgentRun) PrimaryKeyIdentifiers() []string {
	return []string{
		"uuid",
	}
}

func (e AgentRun) ArrayFieldIdentifierToType() map[string]entitytypes.FieldType {
	res := make(map[string]entitytypes.FieldType)

	return res
}
