// Code generated by nuzur go-code-gen. DO NOT EDIT.

package agent_run

import (
	"github.com/nextwave/donald/entity/validation"
)

// Validate checks this AgentRun against the schema's field type and
// type-config rules, aggregating every problem into a single *validation.Error.
// It mirrors the change-request data validation enforced in
// product/module/datavalidation, so data written through this API is held to
// the same rules. Generated by go-code-gen — do not edit.
func (e AgentRun) Validate() error {
	c := validation.NewCollector()
	if e.UUID.IsNil() {
		c.Require("agent_run.uuid")
	}
	if e.ClientUUID.IsNil() {
		c.Require("agent_run.client_uuid")
	}
	if e.RunKey == "" {
		c.Require("agent_run.run_key")
	} else {
		c.Field("agent_run.run_key", validation.String(e.RunKey, 0, 255, ""))

	}
	if e.Name.Valid && e.Name.String != "" {
		c.Field("agent_run.name", validation.String(e.Name.String, 0, 255, ""))

	}
	if e.AgentIdentifier.Valid && e.AgentIdentifier.String != "" {
		c.Field("agent_run.agent_identifier", validation.String(e.AgentIdentifier.String, 0, 255, ""))

	}
	if e.ProtocolVersion.Valid && e.ProtocolVersion.String != "" {
		c.Field("agent_run.protocol_version", validation.String(e.ProtocolVersion.String, 0, 32, ""))

	}
	if e.Status.ToInt64() == 0 {
		c.Require("agent_run.status")
	} else {
		c.Field("agent_run.status", validation.EnumMember(e.Status.ToInt64(), []int64{0, 1, 2, 3, 4, 5, 6, 7, 8}, "agent_run_status"))

	}
	c.Field("agent_run.graph_revision", validation.Integer(e.GraphRevision, false, 0, 0, false, false, false, true, -9223372036854775808, 9223372036854775807))
	c.Field("agent_run.last_event_sequence", validation.Integer(e.LastEventSequence, false, 0, 0, false, false, false, true, -9223372036854775808, 9223372036854775807))
	if e.CreatedBy.IsNil() {
		c.Require("agent_run.created_by")
	}
	if e.UpdatedBy.IsNil() {
		c.Require("agent_run.updated_by")
	}

	return c.Result()
}
