// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nextwave/donald/entity/agent_node"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchAgentNodeByUUIDRequest struct {
	UUID uuid.UUID
}

func (r FetchAgentNodeByUUIDRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("uuid", r.UUID.String())

	return nil
}

type FetchAgentNodeByUUIDResponse struct {
	Results []main_entity.AgentNode
}
