// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nextwave/donald/entity/agent_node"

	"github.com/gofrs/uuid"
	"github.com/nextwave/donald/enums"
	"go.uber.org/zap/zapcore"
)

type FetchAgentNodeByRunUUIDAndStatusRequest struct {
	RunUUID uuid.UUID
	Status  enums.AgentNodeStatus

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchAgentNodeByRunUUIDAndStatusRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("run_uuid", r.RunUUID.String())

	return nil
}

type FetchAgentNodeByRunUUIDAndStatusResponse struct {
	Results []main_entity.AgentNode
}
