// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nextwave/donald/entity/agent_node"

	"github.com/gofrs/uuid"
)

type UpsertRequest struct {
	AgentNode main_entity.AgentNode
}

type UpsertResponse struct {
	UUID uuid.UUID
}
