// Code generated by nuzur go-code-gen. DO NOT EDIT.

package client

import (
	donalddb "github.com/nextwave/donald/core/repository/gen"
	main_entity "github.com/nextwave/donald/entity/client"

	"github.com/nextwave/donald/entity/mapper"

	"github.com/nextwave/donald/enums"
)

func mapModelsToEntities(models []donalddb.Client) []main_entity.Client {
	result := []main_entity.Client{}
	for _, p := range models {
		result = append(result, mapModelToEntity(p))
	}
	return result
}

func mapModelToEntity(m donalddb.Client) main_entity.Client {
	return main_entity.Client{
		UUID:      mapper.StringToUUID(m.UUID),
		Name:      m.Name,
		Industry:  enums.ClientIndustry(m.Industry.Int64),
		CreatedBy: mapper.StringToUUID(m.CreatedBy),
		UpdatedBy: mapper.StringToUUID(m.UpdatedBy),
		Status:    enums.ClientStatus(m.Status),
		CreatedAt: m.CreatedAt,
		UpdatedAt: m.UpdatedAt,
	}
}
