// Code generated by nuzur go-code-gen. DO NOT EDIT.

package client

import (
	"context"

	"github.com/nextwave/donald/core/module/client/types"
	donalddb "github.com/nextwave/donald/core/repository/gen"

	"github.com/gofrs/uuid"

	"time"
)

func (m *module) Insert(
	ctx context.Context,
	req types.UpsertRequest,
	opts ...Option,
) (types.UpsertResponse, error) {

	// auto-generate primary-key UUIDs for new records when not supplied by the caller
	if req.Client.UUID == uuid.Nil {
		req.Client.UUID = uuid.Must(uuid.NewV4())
	}

	// server-managed timestamps (generated created_at/updated_at)
	req.Client.CreatedAt = time.Now()
	req.Client.UpdatedAt = time.Now()

	// validate the new record against the schema's field type/type-config rules
	if err := req.Client.Validate(); err != nil {

		return types.UpsertResponse{}, err
	}

	optConfig := applyAllOptions(opts)

	tx := optConfig.SQLTx
	createdTx := false
	if tx == nil {
		ntx, err := m.repository.DB.Begin()
		if err != nil {
			return types.UpsertResponse{}, err
		}
		tx = ntx
		defer tx.Rollback()
		createdTx = true
	}

	qtx := m.repository.Queries.WithTx(tx)
	params := mapUpsertRequestToInsertParams(req)

	_, err := qtx.InsertClient(
		ctx,
		params,
	)
	if err != nil {

		return types.UpsertResponse{}, err
	}

	if createdTx {
		err := tx.Commit()
		if err != nil {

			return types.UpsertResponse{}, err
		}
	}

	// The rows this module caches have changed, so everything it holds is
	// suspect: drop it rather than answer a later read from a snapshot that
	// predates this write. The cache is per entity, so this discards only this
	// entity's reads. (It is a no-op while a caller-supplied transaction is
	// still open — those reads bypass the cache anyway.)
	m.cache.Flush()

	return buildInsertResponse(req), nil
}

func buildInsertResponse(req types.UpsertRequest) types.UpsertResponse {
	return types.UpsertResponse{

		UUID: req.Client.UUID,
	}
}

func mapUpsertRequestToInsertParams(req types.UpsertRequest) donalddb.InsertClientParams {
	return donalddb.InsertClientParams{
		UUID: req.Client.UUID.String(),

		Name: req.Client.Name,

		Industry: req.Client.Industry.ToNullInt(),

		CreatedBy: req.Client.CreatedBy.String(),

		UpdatedBy: req.Client.UpdatedBy.String(),

		Status: req.Client.Status.ToInt64(),

		CreatedAt: req.Client.CreatedAt,

		UpdatedAt: req.Client.UpdatedAt,
	}
}
