// Code generated by nuzur go-code-gen. DO NOT EDIT.

package agent_edge

import (
	"github.com/nextwave/donald/entity/validation"
)

// Validate checks this AgentEdge against the schema's field type and
// type-config rules, aggregating every problem into a single *validation.Error.
// It mirrors the change-request data validation enforced in
// product/module/datavalidation, so data written through this API is held to
// the same rules. Generated by go-code-gen — do not edit.
func (e AgentEdge) Validate() error {
	c := validation.NewCollector()
	if e.UUID.IsNil() {
		c.Require("agent_edge.uuid")
	}
	if e.RunUUID.IsNil() {
		c.Require("agent_edge.run_uuid")
	}
	if e.FromNodeUUID.IsNil() {
		c.Require("agent_edge.from_node_uuid")
	}
	if e.ToNodeUUID.IsNil() {
		c.Require("agent_edge.to_node_uuid")
	}
	if e.EdgeType.ToInt64() == 0 {
		c.Require("agent_edge.edge_type")
	} else {
		c.Field("agent_edge.edge_type", validation.EnumMember(e.EdgeType.ToInt64(), []int64{0, 1, 2, 3, 4, 5, 6}, "agent_edge_type"))

	}
	if e.ConditionLabel.Valid && e.ConditionLabel.String != "" {
		c.Field("agent_edge.condition_label", validation.String(e.ConditionLabel.String, 0, 255, ""))

	}
	if e.Status.ToInt64() == 0 {
		c.Require("agent_edge.status")
	} else {
		c.Field("agent_edge.status", validation.EnumMember(e.Status.ToInt64(), []int64{0, 1, 2, 3, 4}, "agent_edge_status"))

	}
	if e.CreatedBy.IsNil() {
		c.Require("agent_edge.created_by")
	}
	if e.UpdatedBy.IsNil() {
		c.Require("agent_edge.updated_by")
	}

	return c.Result()
}
