// Code generated by nuzur go-code-gen. DO NOT EDIT.

package agent_edge

import (
	entitytypes "github.com/nextwave/donald/entity/types"
)

func (e AgentEdge) FieldIdentifierToTypeMap() map[string]entitytypes.FieldType {
	return map[string]entitytypes.FieldType{
		"uuid":            entitytypes.StringFieldType,
		"run_uuid":        entitytypes.StringFieldType,
		"from_node_uuid":  entitytypes.StringFieldType,
		"to_node_uuid":    entitytypes.StringFieldType,
		"edge_type":       entitytypes.SingleEnumFieldType,
		"condition_label": entitytypes.StringFieldType,
		"status":          entitytypes.SingleEnumFieldType,
		"created_by":      entitytypes.StringFieldType,
		"updated_by":      entitytypes.StringFieldType,
		"created_at":      entitytypes.TimestampFieldType,
		"updated_at":      entitytypes.TimestampFieldType,
	}
}

func (e AgentEdge) OrderedFieldIdentifiers() []string {
	res := []string{}
	res = append(res, "uuid")
	res = append(res, "run_uuid")
	res = append(res, "from_node_uuid")
	res = append(res, "to_node_uuid")
	res = append(res, "edge_type")
	res = append(res, "condition_label")
	res = append(res, "status")
	res = append(res, "created_by")
	res = append(res, "updated_by")
	res = append(res, "created_at")
	res = append(res, "updated_at")

	return res
}

func (e AgentEdge) DependantFieldIdentifierToTypeMap() map[string]map[string]entitytypes.FieldType {
	res := make(map[string]map[string]entitytypes.FieldType)

	return res
}

func (e AgentEdge) EntityIdentifier() string {
	return "agent_edge"
}

func (e AgentEdge) PrimaryKeyIdentifiers() []string {
	return []string{
		"uuid",
	}
}

func (e AgentEdge) ArrayFieldIdentifierToType() map[string]entitytypes.FieldType {
	res := make(map[string]entitytypes.FieldType)

	return res
}
