// Code generated by nuzur go-code-gen. DO NOT EDIT.

package agent_node

import (
	"context"
	"github.com/nextwave/donald/core/module/agent_node/types"
	"github.com/nextwave/donald/core/repository"
	coretypes "github.com/nextwave/donald/core/types"
	gocache "github.com/patrickmn/go-cache"
	"go.uber.org/zap"
	"golang.org/x/sync/singleflight"
	"sync"
	"time"
)

type Module interface {
	FetchAgentNodeByUUID(ctx context.Context, req types.FetchAgentNodeByUUIDRequest, opts ...Option) (types.FetchAgentNodeByUUIDResponse, error)
	FetchAgentNodeByRunUUIDAndNodeKey(ctx context.Context, req types.FetchAgentNodeByRunUUIDAndNodeKeyRequest, opts ...Option) (types.FetchAgentNodeByRunUUIDAndNodeKeyResponse, error)
	FetchAgentNodeByRunUUIDAndStatus(ctx context.Context, req types.FetchAgentNodeByRunUUIDAndStatusRequest, opts ...Option) (types.FetchAgentNodeByRunUUIDAndStatusResponse, error)

	List(ctx context.Context, req types.ListRequest, opts ...Option) (types.ListResponse, error)

	Upsert(ctx context.Context, req types.UpsertRequest, opts ...Option) (types.UpsertResponse, error)
	Insert(ctx context.Context, req types.UpsertRequest, opts ...Option) (types.UpsertResponse, error)
	Update(ctx context.Context, req types.UpsertRequest, opts ...Option) (types.UpsertResponse, error)
	Delete(ctx context.Context, req types.DeleteRequest, opts ...Option) error
}

type module struct {
	mu         sync.Mutex
	sg         singleflight.Group
	cache      *gocache.Cache
	repository *repository.Implementation
	logger     *zap.Logger
}

func New(params coretypes.ModuleParams) Module {
	return &module{
		repository: params.Repository,
		logger:     params.Logger,
		cache:      gocache.New(30*time.Second, 5*time.Minute),
	}
}
