// Code generated by nuzur go-code-gen. DO NOT EDIT.

package agent_node

import (
	donalddb "github.com/nextwave/donald/core/repository/gen"
	main_entity "github.com/nextwave/donald/entity/agent_node"

	"github.com/nextwave/donald/entity/mapper"

	"github.com/guregu/null/v6"
	"github.com/nextwave/donald/enums"
)

func mapModelsToEntities(models []donalddb.AgentNode) []main_entity.AgentNode {
	result := []main_entity.AgentNode{}
	for _, p := range models {
		result = append(result, mapModelToEntity(p))
	}
	return result
}

func mapModelToEntity(m donalddb.AgentNode) main_entity.AgentNode {
	return main_entity.AgentNode{
		UUID:            mapper.StringToUUID(m.UUID),
		RunUUID:         mapper.StringToUUID(m.RunUUID),
		NodeKey:         m.NodeKey,
		Name:            m.Name,
		Description:     null.NewString(m.Description.String, m.Description.Valid),
		NodeType:        enums.AgentNodeType(m.NodeType.Int64),
		AgentLabel:      null.NewString(m.AgentLabel.String, m.AgentLabel.Valid),
		ToolName:        null.NewString(m.ToolName.String, m.ToolName.Valid),
		Status:          enums.AgentNodeStatus(m.Status),
		StatusMessage:   null.NewString(m.StatusMessage.String, m.StatusMessage.Valid),
		ErrorMessage:    null.NewString(m.ErrorMessage.String, m.ErrorMessage.Valid),
		ProgressPercent: null.NewInt(m.ProgressPercent.Int64, m.ProgressPercent.Valid),
		PlanOrder:       null.NewInt(m.PlanOrder.Int64, m.PlanOrder.Valid),
		Planned:         m.Planned,
		InputSummary:    null.NewString(m.InputSummary.String, m.InputSummary.Valid),
		OutputSummary:   null.NewString(m.OutputSummary.String, m.OutputSummary.Valid),
		StartedAt:       null.NewTime(m.StartedAt.Time, m.StartedAt.Valid),
		FinishedAt:      null.NewTime(m.FinishedAt.Time, m.FinishedAt.Valid),
		CreatedBy:       mapper.StringToUUID(m.CreatedBy),
		UpdatedBy:       mapper.StringToUUID(m.UpdatedBy),
		CreatedAt:       m.CreatedAt,
		UpdatedAt:       m.UpdatedAt,
	}
}
