// Code generated by nuzur go-code-gen. DO NOT EDIT.

package agent_node

import (
	"context"
	"errors"

	"github.com/nextwave/donald/core/module/agent_node/types"
	donalddb "github.com/nextwave/donald/core/repository/gen"

	"time"
)

func (m *module) Update(
	ctx context.Context,
	req types.UpsertRequest,
	opts ...Option,
) (types.UpsertResponse, error) {
	optConfig := applyAllOptions(opts)

	tx := optConfig.SQLTx
	createdTx := false
	if tx == nil {
		ntx, err := m.repository.DB.Begin()
		if err != nil {
			return types.UpsertResponse{}, err
		}
		tx = ntx
		defer tx.Rollback()
		createdTx = true
	}

	qtx := m.repository.Queries.WithTx(tx)
	existing, err := qtx.FetchAgentNodeByUUIDForUpdate(ctx,
		req.AgentNode.UUID.String(),
	)
	if err != nil {

		return types.UpsertResponse{}, err
	}

	if len(existing) == 0 {
		err := errors.New("entity not found")

		return types.UpsertResponse{}, err
	}

	// refresh server-managed timestamps that update on every write (updated_at)
	req.AgentNode.UpdatedAt = time.Now()

	// validate the merged entity against the schema's field type/type-config rules
	if err := req.AgentNode.Validate(); err != nil {

		return types.UpsertResponse{}, err
	}

	params := mapUpsertRequestToUpdateParams(req)
	err = qtx.UpdateAgentNode(
		ctx,
		params,
	)
	if err != nil {

		return types.UpsertResponse{}, err
	}

	if createdTx {
		err := tx.Commit()
		if err != nil {

			return types.UpsertResponse{}, err
		}
	}

	// The rows this module caches have changed, so everything it holds is
	// suspect: drop it rather than answer a later read from a snapshot that
	// predates this write. The cache is per entity, so this discards only this
	// entity's reads. (It is a no-op while a caller-supplied transaction is
	// still open — those reads bypass the cache anyway.)
	m.cache.Flush()

	return buildUpdateResponse(req), nil
}

func buildUpdateResponse(req types.UpsertRequest) types.UpsertResponse {
	return types.UpsertResponse{

		UUID: req.AgentNode.UUID,
	}
}

func mapUpsertRequestToUpdateParams(req types.UpsertRequest) donalddb.UpdateAgentNodeParams {
	return donalddb.UpdateAgentNodeParams{
		UUID: req.AgentNode.UUID.String(),

		RunUUID: req.AgentNode.RunUUID.String(),

		NodeKey: req.AgentNode.NodeKey,

		Name: req.AgentNode.Name,

		Description: req.AgentNode.Description,

		NodeType: req.AgentNode.NodeType.ToNullInt(),

		AgentLabel: req.AgentNode.AgentLabel,

		ToolName: req.AgentNode.ToolName,

		Status: req.AgentNode.Status.ToInt64(),

		StatusMessage: req.AgentNode.StatusMessage,

		ErrorMessage: req.AgentNode.ErrorMessage,

		ProgressPercent: req.AgentNode.ProgressPercent,

		PlanOrder: req.AgentNode.PlanOrder,

		Planned: req.AgentNode.Planned,

		InputSummary: req.AgentNode.InputSummary,

		OutputSummary: req.AgentNode.OutputSummary,

		StartedAt: req.AgentNode.StartedAt,

		FinishedAt: req.AgentNode.FinishedAt,

		CreatedBy: req.AgentNode.CreatedBy.String(),

		UpdatedBy: req.AgentNode.UpdatedBy.String(),

		CreatedAt: req.AgentNode.CreatedAt,

		UpdatedAt: req.AgentNode.UpdatedAt,
	}
}
