// Code generated by nuzur go-code-gen. DO NOT EDIT.

package agent_node

import (
	"context"

	"github.com/nextwave/donald/core/module/agent_node/types"
	donalddb "github.com/nextwave/donald/core/repository/gen"

	"github.com/gofrs/uuid"

	"time"
)

func (m *module) Insert(
	ctx context.Context,
	req types.UpsertRequest,
	opts ...Option,
) (types.UpsertResponse, error) {

	// auto-generate primary-key UUIDs for new records when not supplied by the caller
	if req.AgentNode.UUID == uuid.Nil {
		req.AgentNode.UUID = uuid.Must(uuid.NewV4())
	}

	// server-managed timestamps (generated created_at/updated_at)
	req.AgentNode.CreatedAt = time.Now()
	req.AgentNode.UpdatedAt = time.Now()

	// validate the new record against the schema's field type/type-config rules
	if err := req.AgentNode.Validate(); err != nil {

		return types.UpsertResponse{}, err
	}

	optConfig := applyAllOptions(opts)

	tx := optConfig.SQLTx
	createdTx := false
	if tx == nil {
		ntx, err := m.repository.DB.Begin()
		if err != nil {
			return types.UpsertResponse{}, err
		}
		tx = ntx
		defer tx.Rollback()
		createdTx = true
	}

	qtx := m.repository.Queries.WithTx(tx)
	params := mapUpsertRequestToInsertParams(req)

	_, err := qtx.InsertAgentNode(
		ctx,
		params,
	)
	if err != nil {

		return types.UpsertResponse{}, err
	}

	if createdTx {
		err := tx.Commit()
		if err != nil {

			return types.UpsertResponse{}, err
		}
	}

	// The rows this module caches have changed, so everything it holds is
	// suspect: drop it rather than answer a later read from a snapshot that
	// predates this write. The cache is per entity, so this discards only this
	// entity's reads. (It is a no-op while a caller-supplied transaction is
	// still open — those reads bypass the cache anyway.)
	m.cache.Flush()

	return buildInsertResponse(req), nil
}

func buildInsertResponse(req types.UpsertRequest) types.UpsertResponse {
	return types.UpsertResponse{

		UUID: req.AgentNode.UUID,
	}
}

func mapUpsertRequestToInsertParams(req types.UpsertRequest) donalddb.InsertAgentNodeParams {
	return donalddb.InsertAgentNodeParams{
		UUID: req.AgentNode.UUID.String(),

		RunUUID: req.AgentNode.RunUUID.String(),

		NodeKey: req.AgentNode.NodeKey,

		Name: req.AgentNode.Name,

		Description: req.AgentNode.Description,

		NodeType: req.AgentNode.NodeType.ToNullInt(),

		AgentLabel: req.AgentNode.AgentLabel,

		ToolName: req.AgentNode.ToolName,

		Status: req.AgentNode.Status.ToInt64(),

		StatusMessage: req.AgentNode.StatusMessage,

		ErrorMessage: req.AgentNode.ErrorMessage,

		ProgressPercent: req.AgentNode.ProgressPercent,

		PlanOrder: req.AgentNode.PlanOrder,

		Planned: req.AgentNode.Planned,

		InputSummary: req.AgentNode.InputSummary,

		OutputSummary: req.AgentNode.OutputSummary,

		StartedAt: req.AgentNode.StartedAt,

		FinishedAt: req.AgentNode.FinishedAt,

		CreatedBy: req.AgentNode.CreatedBy.String(),

		UpdatedBy: req.AgentNode.UpdatedBy.String(),

		CreatedAt: req.AgentNode.CreatedAt,

		UpdatedAt: req.AgentNode.UpdatedAt,
	}
}
