// Code generated by nuzur go-code-gen. DO NOT EDIT.

package artifact

import (
	"encoding/json"
	"log"

	"github.com/gofrs/uuid"
	"github.com/guregu/null/v6"
	"github.com/nextwave/donald/enums"
	"time"

	"github.com/nextwave/donald/entity/mapper"
)

type Artifact struct {
	UUID         uuid.UUID            `json:"uuid"`
	RunUUID      uuid.UUID            `json:"run_uuid"`
	NodeUUID     *uuid.UUID           `json:"node_uuid"`
	Name         string               `json:"name"`
	ArtifactType enums.ArtifactType   `json:"artifact_type"`
	Content      null.String          `json:"content"`
	URL          null.String          `json:"url"`
	ContentType  null.String          `json:"content_type"`
	SizeBytes    null.Int64           `json:"size_bytes"`
	TextContent  null.String          `json:"text_content"`
	Status       enums.ArtifactStatus `json:"status"`
	CreatedBy    uuid.UUID            `json:"created_by"`
	UpdatedBy    uuid.UUID            `json:"updated_by"`
	CreatedAt    time.Time            `json:"created_at"`
	UpdatedAt    time.Time            `json:"updated_at"`
}

func (e Artifact) String() string {
	res, _ := json.Marshal(e)
	return string(res)
}

func (e Artifact) PrimaryKeyValues() []string {
	return []string{
		e.UUID.String(),
	}
}

// The parameter is a plain []byte rather than json.RawMessage so that both a
// json.RawMessage and the mapper.JSON a repository model holds can be passed
// without a conversion at the call site.
func ArtifactFromJSON(data []byte) Artifact {
	entity := Artifact{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		if err2 := mapper.FlexibleUnmarshal(data, &entity); err2 != nil {
			log.Printf("flexible unmarshal error ArtifactFromJSON: %v\n", err2)
		}
	}
	return entity
}

func ArtifactSliceFromJSON(data []byte) []Artifact {
	entity := []Artifact{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		entity = []Artifact{}
		var rawSlice []json.RawMessage
		if err2 := json.Unmarshal(data, &rawSlice); err2 == nil {
			for _, raw := range rawSlice {
				item := Artifact{}
				if err3 := mapper.FlexibleUnmarshal(raw, &item); err3 != nil {
					log.Printf("flexible unmarshal error ArtifactSliceFromJSON item: %v\n", err3)
				}
				entity = append(entity, item)
			}
		}
	}
	return entity
}

func (e Artifact) ToJSON() json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error ArtifactToJSON: %v\n", err)
		return json.RawMessage("null")
	}
	return res
}

func ArtifactToJSON(e Artifact) json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error ArtifactToJSON: %v\n", err)
		return json.RawMessage("null")
	}
	return res
}

// ArtifactSliceToJSON serializes a ONE_TO_MANY embed for its JSON column.
// An absent embed is the EMPTY ARRAY, never a zero-length json.RawMessage: a
// zero-length value reaches the driver as the empty string, which is not valid
// JSON, so a create that simply omitted an optional array embed was rejected by
// the database ("invalid input syntax for type json", MySQL error 3140) and
// surfaced as a 500. "[]" is also exactly what an explicit `"field": []` stores,
// so the omitted and the explicitly-empty request round-trip to the same value.
func ArtifactSliceToJSON(e []Artifact) json.RawMessage {
	if e == nil {
		return json.RawMessage("[]")
	}
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error ArtifactSliceToJSON: %v\n", err)
		return json.RawMessage("[]")
	}
	return res
}
