// Code generated by nuzur go-code-gen. DO NOT EDIT.

package artifact

import (
	"github.com/nextwave/donald/entity/validation"
)

// Validate checks this Artifact against the schema's field type and
// type-config rules, aggregating every problem into a single *validation.Error.
// It mirrors the change-request data validation enforced in
// product/module/datavalidation, so data written through this API is held to
// the same rules. Generated by go-code-gen — do not edit.
func (e Artifact) Validate() error {
	c := validation.NewCollector()
	if e.UUID.IsNil() {
		c.Require("artifact.uuid")
	}
	if e.RunUUID.IsNil() {
		c.Require("artifact.run_uuid")
	}
	if e.Name == "" {
		c.Require("artifact.name")
	} else {
		c.Field("artifact.name", validation.String(e.Name, 0, 255, ""))

	}
	if e.ArtifactType.ToInt64() == 0 {
		c.Require("artifact.artifact_type")
	} else {
		c.Field("artifact.artifact_type", validation.EnumMember(e.ArtifactType.ToInt64(), []int64{0, 1, 2, 3, 4, 5, 6, 7}, "artifact_type"))

	}
	if e.URL.Valid && e.URL.String != "" {
		c.Field("artifact.url", validation.URL(e.URL.String, false, nil, nil, nil))

	}
	if e.ContentType.Valid && e.ContentType.String != "" {
		c.Field("artifact.content_type", validation.String(e.ContentType.String, 0, 128, ""))

	}
	if e.SizeBytes.Valid {
		c.Field("artifact.size_bytes", validation.Integer(e.SizeBytes.Int64, false, 0, 0, false, false, false, true, -9223372036854775808, 9223372036854775807))

	}
	if e.Status.ToInt64() == 0 {
		c.Require("artifact.status")
	} else {
		c.Field("artifact.status", validation.EnumMember(e.Status.ToInt64(), []int64{0, 1, 2}, "artifact_status"))

	}
	if e.CreatedBy.IsNil() {
		c.Require("artifact.created_by")
	}
	if e.UpdatedBy.IsNil() {
		c.Require("artifact.updated_by")
	}

	return c.Result()
}
