// Code generated by nuzur go-code-gen. DO NOT EDIT.

package artifact

import (
	entitytypes "github.com/nextwave/donald/entity/types"
)

func (e Artifact) FieldIdentifierToTypeMap() map[string]entitytypes.FieldType {
	return map[string]entitytypes.FieldType{
		"uuid":          entitytypes.StringFieldType,
		"run_uuid":      entitytypes.StringFieldType,
		"node_uuid":     entitytypes.StringFieldType,
		"name":          entitytypes.StringFieldType,
		"artifact_type": entitytypes.SingleEnumFieldType,
		"content":       entitytypes.StringFieldType,
		"url":           entitytypes.StringFieldType,
		"content_type":  entitytypes.StringFieldType,
		"size_bytes":    entitytypes.IntFieldType,
		"text_content":  entitytypes.StringFieldType,
		"status":        entitytypes.SingleEnumFieldType,
		"created_by":    entitytypes.StringFieldType,
		"updated_by":    entitytypes.StringFieldType,
		"created_at":    entitytypes.TimestampFieldType,
		"updated_at":    entitytypes.TimestampFieldType,
	}
}

func (e Artifact) OrderedFieldIdentifiers() []string {
	res := []string{}
	res = append(res, "uuid")
	res = append(res, "run_uuid")
	res = append(res, "node_uuid")
	res = append(res, "name")
	res = append(res, "artifact_type")
	res = append(res, "content")
	res = append(res, "url")
	res = append(res, "content_type")
	res = append(res, "size_bytes")
	res = append(res, "text_content")
	res = append(res, "status")
	res = append(res, "created_by")
	res = append(res, "updated_by")
	res = append(res, "created_at")
	res = append(res, "updated_at")

	return res
}

func (e Artifact) DependantFieldIdentifierToTypeMap() map[string]map[string]entitytypes.FieldType {
	res := make(map[string]map[string]entitytypes.FieldType)

	return res
}

func (e Artifact) EntityIdentifier() string {
	return "artifact"
}

func (e Artifact) PrimaryKeyIdentifiers() []string {
	return []string{
		"uuid",
	}
}

func (e Artifact) ArrayFieldIdentifierToType() map[string]entitytypes.FieldType {
	res := make(map[string]entitytypes.FieldType)

	return res
}
