// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nextwave/donald/entity/client"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchClientByUUIDRequest struct {
	UUID uuid.UUID
}

func (r FetchClientByUUIDRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("uuid", r.UUID.String())

	return nil
}

type FetchClientByUUIDResponse struct {
	Results []main_entity.Client
}
