// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nextwave/donald/entity/client"

	"github.com/gofrs/uuid"
)

type UpsertRequest struct {
	Client main_entity.Client
}

type UpsertResponse struct {
	UUID uuid.UUID
}
