// Code generated by nuzur go-code-gen. DO NOT EDIT.

package agent_run

import (
	"context"
	"fmt"

	"github.com/nextwave/donald/core/module/agent_run/types"

	"errors"
	donalddb "github.com/nextwave/donald/core/repository/gen"
)

func (m *module) FetchAgentRunByClientUUIDAndRunKey(
	ctx context.Context,
	req types.FetchAgentRunByClientUUIDAndRunKeyRequest,
	opts ...Option,
) (types.FetchAgentRunByClientUUIDAndRunKeyResponse, error) {

	resolvedOpts := applyAllOptions(opts)
	queries := m.repository.Queries
	if resolvedOpts.SQLTx != nil {
		queries = queries.WithTx(resolvedOpts.SQLTx)
	}
	// A read inside a transaction must observe that transaction's own
	// uncommitted writes, so it can neither be served from the shared cache nor
	// be collapsed into another caller's in-flight query.
	skipShared := resolvedOpts.SkipCache || resolvedOpts.SQLTx != nil
	cacheKey := fmt.Sprintf("FetchAgentRunByClientUUIDAndRunKey:%v", req)
	if !skipShared {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.FetchAgentRunByClientUUIDAndRunKeyResponse), nil
		}
	}
	fetch := func() (any, error) {
		if req.OrderBy == "" {
			models, err := queries.FetchAgentRunByClientUUIDAndRunKey(
				ctx,
				donalddb.FetchAgentRunByClientUUIDAndRunKeyParams{
					ClientUUID: req.ClientUUID.String(),

					RunKey: req.RunKey,

					Offset: req.Offset,
					Limit:  req.Limit,
				},
			)

			if err != nil {

				return types.FetchAgentRunByClientUUIDAndRunKeyResponse{}, err
			}
			return types.FetchAgentRunByClientUUIDAndRunKeyResponse{
				Results: mapModelsToEntities(models),
			}, nil
		}

		err := errors.New("could not process request")

		return types.FetchAgentRunByClientUUIDAndRunKeyResponse{}, err
	} // end fetch
	var v any
	var fetchErr error
	if skipShared {
		v, fetchErr = fetch()
	} else {
		v, fetchErr, _ = m.sg.Do(cacheKey, fetch)
	}
	if fetchErr != nil {
		return types.FetchAgentRunByClientUUIDAndRunKeyResponse{}, fetchErr
	}
	result := v.(types.FetchAgentRunByClientUUIDAndRunKeyResponse)
	if !skipShared {
		m.cache.Set(cacheKey, result, 0)
	}
	return result, nil

}
