// Code generated by nuzur go-code-gen. DO NOT EDIT.

package agent_run

import (
	"context"
	"fmt"

	"github.com/nextwave/donald/core/module/agent_run/types"
)

func (m *module) FetchAgentRunByUUID(
	ctx context.Context,
	req types.FetchAgentRunByUUIDRequest,
	opts ...Option,
) (types.FetchAgentRunByUUIDResponse, error) {

	resolvedOpts := applyAllOptions(opts)
	queries := m.repository.Queries
	if resolvedOpts.SQLTx != nil {
		queries = queries.WithTx(resolvedOpts.SQLTx)
	}
	// A read inside a transaction must observe that transaction's own
	// uncommitted writes, so it can neither be served from the shared cache nor
	// be collapsed into another caller's in-flight query.
	skipShared := resolvedOpts.SkipCache || resolvedOpts.SQLTx != nil
	cacheKey := fmt.Sprintf("FetchAgentRunByUUID:%v", req)
	if !skipShared {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.FetchAgentRunByUUIDResponse), nil
		}
	}
	fetch := func() (any, error) {
		models, err := queries.FetchAgentRunByUUID(
			ctx,
			req.UUID.String(),
		)
		if err != nil {

			return types.FetchAgentRunByUUIDResponse{}, err
		}
		return types.FetchAgentRunByUUIDResponse{
			Results: mapModelsToEntities(models),
		}, nil
	}
	var v any
	var err error
	if skipShared {
		v, err = fetch()
	} else {
		v, err, _ = m.sg.Do(cacheKey, fetch)
	}
	if err != nil {
		return types.FetchAgentRunByUUIDResponse{}, err
	}
	result := v.(types.FetchAgentRunByUUIDResponse)
	if !skipShared {
		m.cache.Set(cacheKey, result, 0)
	}
	return result, nil

}
