// Code generated by nuzur go-code-gen. DO NOT EDIT.

package agent_run

import (
	donalddb "github.com/nextwave/donald/core/repository/gen"
	main_entity "github.com/nextwave/donald/entity/agent_run"

	"github.com/nextwave/donald/entity/mapper"

	"github.com/guregu/null/v6"
	"github.com/nextwave/donald/enums"
)

func mapModelsToEntities(models []donalddb.AgentRun) []main_entity.AgentRun {
	result := []main_entity.AgentRun{}
	for _, p := range models {
		result = append(result, mapModelToEntity(p))
	}
	return result
}

func mapModelToEntity(m donalddb.AgentRun) main_entity.AgentRun {
	return main_entity.AgentRun{
		UUID:              mapper.StringToUUID(m.UUID),
		ClientUUID:        mapper.StringToUUID(m.ClientUUID),
		RunKey:            m.RunKey,
		Name:              null.NewString(m.Name.String, m.Name.Valid),
		DisplaySummary:    null.NewString(m.DisplaySummary.String, m.DisplaySummary.Valid),
		AgentSummary:      null.NewString(m.AgentSummary.String, m.AgentSummary.Valid),
		AgentIdentifier:   null.NewString(m.AgentIdentifier.String, m.AgentIdentifier.Valid),
		InitialPrompt:     null.NewString(m.InitialPrompt.String, m.InitialPrompt.Valid),
		ProtocolVersion:   null.NewString(m.ProtocolVersion.String, m.ProtocolVersion.Valid),
		Status:            enums.AgentRunStatus(m.Status),
		StatusMessage:     null.NewString(m.StatusMessage.String, m.StatusMessage.Valid),
		GraphRevision:     int64(m.GraphRevision),
		LastEventSequence: int64(m.LastEventSequence),
		StartedAt:         null.NewTime(m.StartedAt.Time, m.StartedAt.Valid),
		FinishedAt:        null.NewTime(m.FinishedAt.Time, m.FinishedAt.Valid),
		LastHeartbeatAt:   null.NewTime(m.LastHeartbeatAt.Time, m.LastHeartbeatAt.Valid),
		CreatedBy:         mapper.StringToUUID(m.CreatedBy),
		UpdatedBy:         mapper.StringToUUID(m.UpdatedBy),
		CreatedAt:         m.CreatedAt,
		UpdatedAt:         m.UpdatedAt,
	}
}
