// Code generated by nuzur go-code-gen. DO NOT EDIT.

package agent_run

import (
	"context"

	"github.com/nextwave/donald/core/module/agent_run/types"
	donalddb "github.com/nextwave/donald/core/repository/gen"

	"github.com/gofrs/uuid"

	"time"
)

func (m *module) Insert(
	ctx context.Context,
	req types.UpsertRequest,
	opts ...Option,
) (types.UpsertResponse, error) {

	// auto-generate primary-key UUIDs for new records when not supplied by the caller
	if req.AgentRun.UUID == uuid.Nil {
		req.AgentRun.UUID = uuid.Must(uuid.NewV4())
	}

	// server-managed timestamps (generated created_at/updated_at)
	req.AgentRun.CreatedAt = time.Now()
	req.AgentRun.UpdatedAt = time.Now()

	// validate the new record against the schema's field type/type-config rules
	if err := req.AgentRun.Validate(); err != nil {

		return types.UpsertResponse{}, err
	}

	optConfig := applyAllOptions(opts)

	tx := optConfig.SQLTx
	createdTx := false
	if tx == nil {
		ntx, err := m.repository.DB.Begin()
		if err != nil {
			return types.UpsertResponse{}, err
		}
		tx = ntx
		defer tx.Rollback()
		createdTx = true
	}

	qtx := m.repository.Queries.WithTx(tx)
	params := mapUpsertRequestToInsertParams(req)

	_, err := qtx.InsertAgentRun(
		ctx,
		params,
	)
	if err != nil {

		return types.UpsertResponse{}, err
	}

	if createdTx {
		err := tx.Commit()
		if err != nil {

			return types.UpsertResponse{}, err
		}
	}

	// The rows this module caches have changed, so everything it holds is
	// suspect: drop it rather than answer a later read from a snapshot that
	// predates this write. The cache is per entity, so this discards only this
	// entity's reads. (It is a no-op while a caller-supplied transaction is
	// still open — those reads bypass the cache anyway.)
	m.cache.Flush()

	return buildInsertResponse(req), nil
}

func buildInsertResponse(req types.UpsertRequest) types.UpsertResponse {
	return types.UpsertResponse{

		UUID: req.AgentRun.UUID,
	}
}

func mapUpsertRequestToInsertParams(req types.UpsertRequest) donalddb.InsertAgentRunParams {
	return donalddb.InsertAgentRunParams{
		UUID: req.AgentRun.UUID.String(),

		ClientUUID: req.AgentRun.ClientUUID.String(),

		RunKey: req.AgentRun.RunKey,

		Name: req.AgentRun.Name,

		DisplaySummary: req.AgentRun.DisplaySummary,

		AgentSummary: req.AgentRun.AgentSummary,

		AgentIdentifier: req.AgentRun.AgentIdentifier,

		InitialPrompt: req.AgentRun.InitialPrompt,

		ProtocolVersion: req.AgentRun.ProtocolVersion,

		Status: req.AgentRun.Status.ToInt64(),

		StatusMessage: req.AgentRun.StatusMessage,

		GraphRevision: req.AgentRun.GraphRevision,

		LastEventSequence: req.AgentRun.LastEventSequence,

		StartedAt: req.AgentRun.StartedAt,

		FinishedAt: req.AgentRun.FinishedAt,

		LastHeartbeatAt: req.AgentRun.LastHeartbeatAt,

		CreatedBy: req.AgentRun.CreatedBy.String(),

		UpdatedBy: req.AgentRun.UpdatedBy.String(),

		CreatedAt: req.AgentRun.CreatedAt,

		UpdatedAt: req.AgentRun.UpdatedAt,
	}
}
