// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nextwave/donald/entity/agent_event"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchAgentEventByRunUUIDAndSequenceRequest struct {
	RunUUID  uuid.UUID
	Sequence int64

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchAgentEventByRunUUIDAndSequenceRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("run_uuid", r.RunUUID.String())

	return nil
}

type FetchAgentEventByRunUUIDAndSequenceResponse struct {
	Results []main_entity.AgentEvent
}
