// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nextwave/donald/entity/agent_event"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchAgentEventByNodeUUIDAndSequenceRequest struct {
	NodeUUID *uuid.UUID
	Sequence int64

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchAgentEventByNodeUUIDAndSequenceRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	return nil
}

type FetchAgentEventByNodeUUIDAndSequenceResponse struct {
	Results []main_entity.AgentEvent
}
