// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nextwave/donald/entity/agent_event"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchAgentEventByUUIDRequest struct {
	UUID uuid.UUID
}

func (r FetchAgentEventByUUIDRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("uuid", r.UUID.String())

	return nil
}

type FetchAgentEventByUUIDResponse struct {
	Results []main_entity.AgentEvent
}
