// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nextwave/donald/entity/agent_event"

	"github.com/gofrs/uuid"
)

type UpsertRequest struct {
	AgentEvent main_entity.AgentEvent
}

type UpsertResponse struct {
	UUID uuid.UUID
}
