CREATE TABLE IF NOT EXISTS `client` (
	`uuid` char(36) NOT NULL,
	`name` varchar(255) NOT NULL,
	`industry` int,
	`created_by` char(36) NOT NULL,
	`updated_by` char(36) NOT NULL,
	`status` int NOT NULL,
	`created_at` datetime NOT NULL DEFAULT current_timestamp(),
	`updated_at` datetime NOT NULL DEFAULT current_timestamp(),
	PRIMARY KEY (`uuid`)
) ENGINE InnoDB;
CREATE TABLE IF NOT EXISTS `agent_run` (
	`uuid` char(36) NOT NULL,
	`client_uuid` char(36) NOT NULL,
	`run_key` varchar(255) NOT NULL,
	`name` varchar(255),
	`display_summary` text,
	`agent_summary` text,
	`agent_identifier` varchar(255),
	`initial_prompt` text,
	`protocol_version` varchar(32),
	`status` int NOT NULL,
	`status_message` text,
	`graph_revision` bigint NOT NULL DEFAULT 0,
	`last_event_sequence` bigint NOT NULL DEFAULT 0,
	`started_at` datetime,
	`finished_at` datetime,
	`last_heartbeat_at` datetime,
	`created_by` char(36) NOT NULL,
	`updated_by` char(36) NOT NULL,
	`created_at` datetime NOT NULL DEFAULT current_timestamp(),
	`updated_at` datetime NOT NULL DEFAULT current_timestamp(),
	PRIMARY KEY (`uuid`),
	KEY `idx_agent_run_client_status_created` (`client_uuid`, `status`, `created_at` DESC),
	UNIQUE KEY `uq_agent_run_client_run_key` (`client_uuid`, `run_key`),
	CONSTRAINT `agent_run_client` FOREIGN KEY (`client_uuid`) REFERENCES `client` (`uuid`) ON DELETE RESTRICT
) ENGINE InnoDB;
CREATE TABLE IF NOT EXISTS `agent_event` (
	`uuid` char(36) NOT NULL,
	`run_uuid` char(36) NOT NULL,
	`sequence` bigint NOT NULL,
	`event_type` int NOT NULL,
	`node_uuid` char(36),
	`agent_label` varchar(120),
	`idempotency_key` varchar(255) NOT NULL,
	`occurred_at` datetime(3) NOT NULL,
	`status` int NOT NULL,
	`created_by` char(36) NOT NULL,
	`updated_by` char(36) NOT NULL,
	`created_at` datetime NOT NULL DEFAULT current_timestamp(),
	`updated_at` datetime NOT NULL DEFAULT current_timestamp(),
	`payload` json,
	PRIMARY KEY (`uuid`),
	KEY `idx_agent_event_node_sequence` (`node_uuid`, `sequence`),
	UNIQUE KEY `uq_agent_event_run_sequence` (`run_uuid`, `sequence`),
	UNIQUE KEY `uq_agent_event_run_idempotency_key` (`run_uuid`, `idempotency_key`),
	CONSTRAINT `agent_event_run` FOREIGN KEY (`run_uuid`) REFERENCES `agent_run` (`uuid`) ON DELETE CASCADE
) ENGINE InnoDB;
CREATE TABLE IF NOT EXISTS `agent_node` (
	`uuid` char(36) NOT NULL,
	`run_uuid` char(36) NOT NULL,
	`node_key` varchar(255) NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`node_type` int,
	`agent_label` varchar(120),
	`tool_name` varchar(255),
	`status` int NOT NULL,
	`status_message` text,
	`error_message` text,
	`progress_percent` smallint,
	`plan_order` smallint,
	`planned` tinyint(1) NOT NULL DEFAULT 0,
	`input_summary` text,
	`output_summary` text,
	`started_at` datetime,
	`finished_at` datetime,
	`created_by` char(36) NOT NULL,
	`updated_by` char(36) NOT NULL,
	`created_at` datetime NOT NULL DEFAULT current_timestamp(),
	`updated_at` datetime NOT NULL DEFAULT current_timestamp(),
	PRIMARY KEY (`uuid`),
	KEY `idx_agent_node_run_status` (`run_uuid`, `status`),
	UNIQUE KEY `uq_agent_node_run_node_key` (`run_uuid`, `node_key`),
	CONSTRAINT `agent_node_run` FOREIGN KEY (`run_uuid`) REFERENCES `agent_run` (`uuid`) ON DELETE CASCADE
) ENGINE InnoDB;
CREATE TABLE IF NOT EXISTS `agent_edge` (
	`uuid` char(36) NOT NULL,
	`run_uuid` char(36) NOT NULL,
	`from_node_uuid` char(36) NOT NULL,
	`to_node_uuid` char(36) NOT NULL,
	`edge_type` int NOT NULL,
	`condition_label` varchar(255),
	`status` int NOT NULL,
	`created_by` char(36) NOT NULL,
	`updated_by` char(36) NOT NULL,
	`created_at` datetime NOT NULL DEFAULT current_timestamp(),
	`updated_at` datetime NOT NULL DEFAULT current_timestamp(),
	PRIMARY KEY (`uuid`),
	KEY `idx_agent_edge_run` (`run_uuid`),
	KEY `idx_agent_edge_to_node` (`to_node_uuid`),
	UNIQUE KEY `uq_agent_edge_from_to_type` (`from_node_uuid`, `to_node_uuid`, `edge_type`),
	CONSTRAINT `agent_edge_run` FOREIGN KEY (`run_uuid`) REFERENCES `agent_run` (`uuid`) ON DELETE CASCADE,
	CONSTRAINT `agent_edge_from_node` FOREIGN KEY (`from_node_uuid`) REFERENCES `agent_node` (`uuid`) ON DELETE CASCADE,
	CONSTRAINT `agent_edge_to_node` FOREIGN KEY (`to_node_uuid`) REFERENCES `agent_node` (`uuid`) ON DELETE CASCADE
) ENGINE InnoDB;
CREATE TABLE IF NOT EXISTS `artifact` (
	`uuid` char(36) NOT NULL,
	`run_uuid` char(36) NOT NULL,
	`node_uuid` char(36),
	`name` varchar(255) NOT NULL,
	`artifact_type` int NOT NULL,
	`content` varchar(512),
	`url` varchar(512),
	`content_type` varchar(128),
	`size_bytes` bigint,
	`text_content` text,
	`status` int NOT NULL,
	`created_by` char(36) NOT NULL,
	`updated_by` char(36) NOT NULL,
	`created_at` datetime NOT NULL DEFAULT current_timestamp(),
	`updated_at` datetime NOT NULL DEFAULT current_timestamp(),
	PRIMARY KEY (`uuid`),
	KEY `idx_artifact_run_created` (`run_uuid`, `created_at`),
	KEY `idx_artifact_node` (`node_uuid`),
	CONSTRAINT `artifact_run` FOREIGN KEY (`run_uuid`) REFERENCES `agent_run` (`uuid`) ON DELETE CASCADE,
	CONSTRAINT `artifact_node` FOREIGN KEY (`node_uuid`) REFERENCES `agent_node` (`uuid`) ON DELETE SET NULL
) ENGINE InnoDB;
CREATE TABLE IF NOT EXISTS `intervention` (
	`uuid` char(36) NOT NULL,
	`run_uuid` char(36) NOT NULL,
	`node_uuid` char(36) NOT NULL,
	`type` int NOT NULL,
	`prompt` text,
	`status` int NOT NULL,
	`status_message` text,
	`requested_by_uuid` char(36) NOT NULL,
	`resolved_by_uuid` char(36),
	`delivered_at` datetime,
	`resolved_at` datetime,
	`expires_at` datetime,
	`created_by` char(36) NOT NULL,
	`updated_by` char(36) NOT NULL,
	`created_at` datetime NOT NULL DEFAULT current_timestamp(),
	`updated_at` datetime NOT NULL DEFAULT current_timestamp(),
	`interactions` json,
	PRIMARY KEY (`uuid`),
	KEY `idx_intervention_run_status` (`run_uuid`, `status`, `created_at`),
	KEY `idx_intervention_node` (`node_uuid`),
	CONSTRAINT `intervention_run` FOREIGN KEY (`run_uuid`) REFERENCES `agent_run` (`uuid`) ON DELETE CASCADE,
	CONSTRAINT `intervention_node` FOREIGN KEY (`node_uuid`) REFERENCES `agent_node` (`uuid`) ON DELETE CASCADE
) ENGINE InnoDB;
