// Code generated by nuzur go-code-gen. DO NOT EDIT.

package intervention

import (
	donalddb "github.com/nextwave/donald/core/repository/gen"
	main_entity "github.com/nextwave/donald/entity/intervention"

	"github.com/nextwave/donald/entity/mapper"

	"github.com/guregu/null/v6"
	"github.com/nextwave/donald/entity/intervention_interaction"
	"github.com/nextwave/donald/enums"
)

func mapModelsToEntities(models []donalddb.Intervention) []main_entity.Intervention {
	result := []main_entity.Intervention{}
	for _, p := range models {
		result = append(result, mapModelToEntity(p))
	}
	return result
}

func mapModelToEntity(m donalddb.Intervention) main_entity.Intervention {
	return main_entity.Intervention{
		UUID:            mapper.StringToUUID(m.UUID),
		RunUUID:         mapper.StringToUUID(m.RunUUID),
		NodeUUID:        mapper.StringToUUID(m.NodeUUID),
		Type:            enums.InterventionType(m.Type),
		Prompt:          null.NewString(m.Prompt.String, m.Prompt.Valid),
		Status:          enums.InterventionStatus(m.Status),
		StatusMessage:   null.NewString(m.StatusMessage.String, m.StatusMessage.Valid),
		RequestedByUUID: mapper.StringToUUID(m.RequestedByUUID),
		ResolvedByUUID:  mapper.StringToUUIDPtr(m.ResolvedByUUID),
		DeliveredAt:     null.NewTime(m.DeliveredAt.Time, m.DeliveredAt.Valid),
		ResolvedAt:      null.NewTime(m.ResolvedAt.Time, m.ResolvedAt.Valid),
		ExpiresAt:       null.NewTime(m.ExpiresAt.Time, m.ExpiresAt.Valid),
		CreatedBy:       mapper.StringToUUID(m.CreatedBy),
		UpdatedBy:       mapper.StringToUUID(m.UpdatedBy),
		CreatedAt:       m.CreatedAt,
		UpdatedAt:       m.UpdatedAt,
		Interactions:    intervention_interaction.InterventionInteractionSliceFromJSON(m.Interactions),
	}
}
