// Code generated by nuzur go-code-gen. DO NOT EDIT.

package intervention

import (
	"context"

	"github.com/nextwave/donald/core/module/intervention/types"
	donalddb "github.com/nextwave/donald/core/repository/gen"

	"github.com/gofrs/uuid"

	"github.com/nextwave/donald/entity/intervention_interaction"

	"time"

	"github.com/nextwave/donald/entity/mapper"
)

func (m *module) Insert(
	ctx context.Context,
	req types.UpsertRequest,
	opts ...Option,
) (types.UpsertResponse, error) {

	// auto-generate primary-key UUIDs for new records when not supplied by the caller
	if req.Intervention.UUID == uuid.Nil {
		req.Intervention.UUID = uuid.Must(uuid.NewV4())
	}

	// server-managed timestamps (generated created_at/updated_at)
	req.Intervention.CreatedAt = time.Now()
	req.Intervention.UpdatedAt = time.Now()

	// validate the new record against the schema's field type/type-config rules
	if err := req.Intervention.Validate(); err != nil {

		return types.UpsertResponse{}, err
	}

	optConfig := applyAllOptions(opts)

	tx := optConfig.SQLTx
	createdTx := false
	if tx == nil {
		ntx, err := m.repository.DB.Begin()
		if err != nil {
			return types.UpsertResponse{}, err
		}
		tx = ntx
		defer tx.Rollback()
		createdTx = true
	}

	qtx := m.repository.Queries.WithTx(tx)
	params := mapUpsertRequestToInsertParams(req)

	_, err := qtx.InsertIntervention(
		ctx,
		params,
	)
	if err != nil {

		return types.UpsertResponse{}, err
	}

	if createdTx {
		err := tx.Commit()
		if err != nil {

			return types.UpsertResponse{}, err
		}
	}

	// The rows this module caches have changed, so everything it holds is
	// suspect: drop it rather than answer a later read from a snapshot that
	// predates this write. The cache is per entity, so this discards only this
	// entity's reads. (It is a no-op while a caller-supplied transaction is
	// still open — those reads bypass the cache anyway.)
	m.cache.Flush()

	return buildInsertResponse(req), nil
}

func buildInsertResponse(req types.UpsertRequest) types.UpsertResponse {
	return types.UpsertResponse{

		UUID: req.Intervention.UUID,
	}
}

func mapUpsertRequestToInsertParams(req types.UpsertRequest) donalddb.InsertInterventionParams {
	return donalddb.InsertInterventionParams{
		UUID: req.Intervention.UUID.String(),

		RunUUID: req.Intervention.RunUUID.String(),

		NodeUUID: req.Intervention.NodeUUID.String(),

		Type: req.Intervention.Type.ToInt64(),

		Prompt: req.Intervention.Prompt,

		Status: req.Intervention.Status.ToInt64(),

		StatusMessage: req.Intervention.StatusMessage,

		RequestedByUUID: req.Intervention.RequestedByUUID.String(),

		ResolvedByUUID: mapper.UUIDPtrToNullString(req.Intervention.ResolvedByUUID),

		DeliveredAt: req.Intervention.DeliveredAt,

		ResolvedAt: req.Intervention.ResolvedAt,

		ExpiresAt: req.Intervention.ExpiresAt,

		CreatedBy: req.Intervention.CreatedBy.String(),

		UpdatedBy: req.Intervention.UpdatedBy.String(),

		CreatedAt: req.Intervention.CreatedAt,

		UpdatedAt: req.Intervention.UpdatedAt,

		Interactions: mapper.JSON(intervention_interaction.InterventionInteractionSliceToJSON(req.Intervention.Interactions)),
	}
}
