// Code generated by nuzur go-code-gen. DO NOT EDIT.

package intervention

import (
	entitytypes "github.com/nextwave/donald/entity/types"

	"github.com/nextwave/donald/entity/intervention_interaction"
)

func (e Intervention) FieldIdentifierToTypeMap() map[string]entitytypes.FieldType {
	return map[string]entitytypes.FieldType{
		"uuid":              entitytypes.StringFieldType,
		"run_uuid":          entitytypes.StringFieldType,
		"node_uuid":         entitytypes.StringFieldType,
		"type":              entitytypes.SingleEnumFieldType,
		"prompt":            entitytypes.StringFieldType,
		"status":            entitytypes.SingleEnumFieldType,
		"status_message":    entitytypes.StringFieldType,
		"requested_by_uuid": entitytypes.StringFieldType,
		"resolved_by_uuid":  entitytypes.StringFieldType,
		"delivered_at":      entitytypes.TimestampFieldType,
		"resolved_at":       entitytypes.TimestampFieldType,
		"expires_at":        entitytypes.TimestampFieldType,
		"created_by":        entitytypes.StringFieldType,
		"updated_by":        entitytypes.StringFieldType,
		"created_at":        entitytypes.TimestampFieldType,
		"updated_at":        entitytypes.TimestampFieldType,
		"interactions":      entitytypes.MultiDependantEntityFieldType,
	}
}

func (e Intervention) OrderedFieldIdentifiers() []string {
	res := []string{}
	res = append(res, "uuid")
	res = append(res, "run_uuid")
	res = append(res, "node_uuid")
	res = append(res, "type")
	res = append(res, "prompt")
	res = append(res, "status")
	res = append(res, "status_message")
	res = append(res, "requested_by_uuid")
	res = append(res, "resolved_by_uuid")
	res = append(res, "delivered_at")
	res = append(res, "resolved_at")
	res = append(res, "expires_at")
	res = append(res, "created_by")
	res = append(res, "updated_by")
	res = append(res, "created_at")
	res = append(res, "updated_at")
	res = append(res, "interactions")

	return res
}

func (e Intervention) DependantFieldIdentifierToTypeMap() map[string]map[string]entitytypes.FieldType {
	res := make(map[string]map[string]entitytypes.FieldType)

	res["interactions"] = intervention_interaction.InterventionInteraction{}.FieldIdentifierToTypeMap()
	return res
}

func (e Intervention) EntityIdentifier() string {
	return "intervention"
}

func (e Intervention) PrimaryKeyIdentifiers() []string {
	return []string{
		"uuid",
	}
}

func (e Intervention) ArrayFieldIdentifierToType() map[string]entitytypes.FieldType {
	res := make(map[string]entitytypes.FieldType)

	return res
}
