// Code generated by nuzur go-code-gen. DO NOT EDIT.

package intervention

import (
	"github.com/nextwave/donald/entity/validation"
)

// Validate checks this Intervention against the schema's field type and
// type-config rules, aggregating every problem into a single *validation.Error.
// It mirrors the change-request data validation enforced in
// product/module/datavalidation, so data written through this API is held to
// the same rules. Generated by go-code-gen — do not edit.
func (e Intervention) Validate() error {
	c := validation.NewCollector()
	if e.UUID.IsNil() {
		c.Require("intervention.uuid")
	}
	if e.RunUUID.IsNil() {
		c.Require("intervention.run_uuid")
	}
	if e.NodeUUID.IsNil() {
		c.Require("intervention.node_uuid")
	}
	if e.Type.ToInt64() == 0 {
		c.Require("intervention.type")
	} else {
		c.Field("intervention.type", validation.EnumMember(e.Type.ToInt64(), []int64{0, 1, 2}, "intervention_type"))

	}
	if e.Status.ToInt64() == 0 {
		c.Require("intervention.status")
	} else {
		c.Field("intervention.status", validation.EnumMember(e.Status.ToInt64(), []int64{0, 1, 2, 3, 4, 5, 6}, "intervention_status"))

	}
	if e.RequestedByUUID.IsNil() {
		c.Require("intervention.requested_by_uuid")
	}
	if e.CreatedBy.IsNil() {
		c.Require("intervention.created_by")
	}
	if e.UpdatedBy.IsNil() {
		c.Require("intervention.updated_by")
	}
	for i, item := range e.Interactions {
		c.Merge(validation.Index("intervention.interactions", i), item.Validate())
	}

	return c.Result()
}
