// Code generated by nuzur go-code-gen. DO NOT EDIT.

package intervention

import (
	"encoding/json"
	"log"

	"github.com/gofrs/uuid"
	"github.com/guregu/null/v6"
	"github.com/nextwave/donald/entity/intervention_interaction"
	"github.com/nextwave/donald/enums"
	"time"

	"github.com/nextwave/donald/entity/mapper"
)

type Intervention struct {
	UUID            uuid.UUID                                          `json:"uuid"`
	RunUUID         uuid.UUID                                          `json:"run_uuid"`
	NodeUUID        uuid.UUID                                          `json:"node_uuid"`
	Type            enums.InterventionType                             `json:"type"`
	Prompt          null.String                                        `json:"prompt"`
	Status          enums.InterventionStatus                           `json:"status"`
	StatusMessage   null.String                                        `json:"status_message"`
	RequestedByUUID uuid.UUID                                          `json:"requested_by_uuid"`
	ResolvedByUUID  *uuid.UUID                                         `json:"resolved_by_uuid"`
	DeliveredAt     null.Time                                          `json:"delivered_at"`
	ResolvedAt      null.Time                                          `json:"resolved_at"`
	ExpiresAt       null.Time                                          `json:"expires_at"`
	CreatedBy       uuid.UUID                                          `json:"created_by"`
	UpdatedBy       uuid.UUID                                          `json:"updated_by"`
	CreatedAt       time.Time                                          `json:"created_at"`
	UpdatedAt       time.Time                                          `json:"updated_at"`
	Interactions    []intervention_interaction.InterventionInteraction `json:"interactions"`
}

func (e Intervention) String() string {
	res, _ := json.Marshal(e)
	return string(res)
}

func (e Intervention) PrimaryKeyValues() []string {
	return []string{
		e.UUID.String(),
	}
}

// The parameter is a plain []byte rather than json.RawMessage so that both a
// json.RawMessage and the mapper.JSON a repository model holds can be passed
// without a conversion at the call site.
func InterventionFromJSON(data []byte) Intervention {
	entity := Intervention{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		if err2 := mapper.FlexibleUnmarshal(data, &entity); err2 != nil {
			log.Printf("flexible unmarshal error InterventionFromJSON: %v\n", err2)
		}
	}
	return entity
}

func InterventionSliceFromJSON(data []byte) []Intervention {
	entity := []Intervention{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		entity = []Intervention{}
		var rawSlice []json.RawMessage
		if err2 := json.Unmarshal(data, &rawSlice); err2 == nil {
			for _, raw := range rawSlice {
				item := Intervention{}
				if err3 := mapper.FlexibleUnmarshal(raw, &item); err3 != nil {
					log.Printf("flexible unmarshal error InterventionSliceFromJSON item: %v\n", err3)
				}
				entity = append(entity, item)
			}
		}
	}
	return entity
}

func (e Intervention) ToJSON() json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error InterventionToJSON: %v\n", err)
		return json.RawMessage("null")
	}
	return res
}

func InterventionToJSON(e Intervention) json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error InterventionToJSON: %v\n", err)
		return json.RawMessage("null")
	}
	return res
}

// InterventionSliceToJSON serializes a ONE_TO_MANY embed for its JSON column.
// An absent embed is the EMPTY ARRAY, never a zero-length json.RawMessage: a
// zero-length value reaches the driver as the empty string, which is not valid
// JSON, so a create that simply omitted an optional array embed was rejected by
// the database ("invalid input syntax for type json", MySQL error 3140) and
// surfaced as a 500. "[]" is also exactly what an explicit `"field": []` stores,
// so the omitted and the explicitly-empty request round-trip to the same value.
func InterventionSliceToJSON(e []Intervention) json.RawMessage {
	if e == nil {
		return json.RawMessage("[]")
	}
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error InterventionSliceToJSON: %v\n", err)
		return json.RawMessage("[]")
	}
	return res
}
