-- Code generated by nuzur go-code-gen. DO NOT EDIT.
CREATE TABLE IF NOT EXISTS `client` (
    `uuid` CHAR(36) NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `industry` INT,
    `created_by` CHAR(36) NOT NULL,
    `updated_by` CHAR(36) NOT NULL,
    `status` INT NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`uuid`)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `agent_run` (
    `uuid` CHAR(36) NOT NULL,
    `client_uuid` CHAR(36) NOT NULL,
    `run_key` VARCHAR(255) NOT NULL,
    `name` VARCHAR(255),
    `display_summary` TEXT,
    `agent_summary` TEXT,
    `agent_identifier` VARCHAR(255),
    `initial_prompt` TEXT,
    `protocol_version` VARCHAR(32),
    `status` INT NOT NULL,
    `status_message` TEXT,
    `graph_revision` BIGINT NOT NULL DEFAULT 0,
    `last_event_sequence` BIGINT NOT NULL DEFAULT 0,
    `started_at` DATETIME,
    `finished_at` DATETIME,
    `last_heartbeat_at` DATETIME,
    `created_by` CHAR(36) NOT NULL,
    `updated_by` CHAR(36) NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`uuid`),
    INDEX `idx_agent_run_client_status_created` (`client_uuid`, `status`, `created_at` DESC),
    UNIQUE INDEX `uq_agent_run_client_run_key` (`client_uuid`, `run_key`),
    CONSTRAINT `agent_run_client`
        FOREIGN KEY (`client_uuid`)
        REFERENCES `client` (`uuid`)
        ON DELETE RESTRICT
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `agent_node` (
    `uuid` CHAR(36) NOT NULL,
    `run_uuid` CHAR(36) NOT NULL,
    `node_key` VARCHAR(255) NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `description` TEXT,
    `node_type` INT,
    `agent_label` VARCHAR(120),
    `tool_name` VARCHAR(255),
    `status` INT NOT NULL,
    `status_message` TEXT,
    `error_message` TEXT,
    `progress_percent` SMALLINT,
    `plan_order` SMALLINT,
    `planned` TINYINT(1) NOT NULL DEFAULT 0,
    `input_summary` TEXT,
    `output_summary` TEXT,
    `started_at` DATETIME,
    `finished_at` DATETIME,
    `created_by` CHAR(36) NOT NULL,
    `updated_by` CHAR(36) NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`uuid`),
    INDEX `idx_agent_node_run_status` (`run_uuid`, `status`),
    UNIQUE INDEX `uq_agent_node_run_node_key` (`run_uuid`, `node_key`),
    CONSTRAINT `agent_node_run`
        FOREIGN KEY (`run_uuid`)
        REFERENCES `agent_run` (`uuid`)
        ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `agent_edge` (
    `uuid` CHAR(36) NOT NULL,
    `run_uuid` CHAR(36) NOT NULL,
    `from_node_uuid` CHAR(36) NOT NULL,
    `to_node_uuid` CHAR(36) NOT NULL,
    `edge_type` INT NOT NULL,
    `condition_label` VARCHAR(255),
    `status` INT NOT NULL,
    `created_by` CHAR(36) NOT NULL,
    `updated_by` CHAR(36) NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`uuid`),
    INDEX `idx_agent_edge_run` (`run_uuid`),
    INDEX `idx_agent_edge_to_node` (`to_node_uuid`),
    UNIQUE INDEX `uq_agent_edge_from_to_type` (`from_node_uuid`, `to_node_uuid`, `edge_type`),
    CONSTRAINT `agent_edge_run`
        FOREIGN KEY (`run_uuid`)
        REFERENCES `agent_run` (`uuid`)
        ON DELETE CASCADE,
    CONSTRAINT `agent_edge_from_node`
        FOREIGN KEY (`from_node_uuid`)
        REFERENCES `agent_node` (`uuid`)
        ON DELETE CASCADE,
    CONSTRAINT `agent_edge_to_node`
        FOREIGN KEY (`to_node_uuid`)
        REFERENCES `agent_node` (`uuid`)
        ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `agent_event` (
    `uuid` CHAR(36) NOT NULL,
    `run_uuid` CHAR(36) NOT NULL,
    `sequence` BIGINT NOT NULL,
    `event_type` INT NOT NULL,
    `node_uuid` CHAR(36),
    `agent_label` VARCHAR(120),
    `idempotency_key` VARCHAR(255) NOT NULL,
    `occurred_at` DATETIME(3) NOT NULL,
    `status` INT NOT NULL,
    `created_by` CHAR(36) NOT NULL,
    `updated_by` CHAR(36) NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `payload` JSON,
    PRIMARY KEY (`uuid`),
    INDEX `idx_agent_event_node_sequence` (`node_uuid`, `sequence`),
    UNIQUE INDEX `uq_agent_event_run_sequence` (`run_uuid`, `sequence`),
    UNIQUE INDEX `uq_agent_event_run_idempotency_key` (`run_uuid`, `idempotency_key`),
    CONSTRAINT `agent_event_run`
        FOREIGN KEY (`run_uuid`)
        REFERENCES `agent_run` (`uuid`)
        ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `intervention` (
    `uuid` CHAR(36) NOT NULL,
    `run_uuid` CHAR(36) NOT NULL,
    `node_uuid` CHAR(36) NOT NULL,
    `type` INT NOT NULL,
    `prompt` TEXT,
    `status` INT NOT NULL,
    `status_message` TEXT,
    `requested_by_uuid` CHAR(36) NOT NULL,
    `resolved_by_uuid` CHAR(36),
    `delivered_at` DATETIME,
    `resolved_at` DATETIME,
    `expires_at` DATETIME,
    `created_by` CHAR(36) NOT NULL,
    `updated_by` CHAR(36) NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `interactions` JSON,
    PRIMARY KEY (`uuid`),
    INDEX `idx_intervention_run_status` (`run_uuid`, `status`, `created_at`),
    INDEX `idx_intervention_node` (`node_uuid`),
    CONSTRAINT `intervention_run`
        FOREIGN KEY (`run_uuid`)
        REFERENCES `agent_run` (`uuid`)
        ON DELETE CASCADE,
    CONSTRAINT `intervention_node`
        FOREIGN KEY (`node_uuid`)
        REFERENCES `agent_node` (`uuid`)
        ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `artifact` (
    `uuid` CHAR(36) NOT NULL,
    `run_uuid` CHAR(36) NOT NULL,
    `node_uuid` CHAR(36),
    `name` VARCHAR(255) NOT NULL,
    `artifact_type` INT NOT NULL,
    `content` VARCHAR(512),
    `url` VARCHAR(512),
    `content_type` VARCHAR(128),
    `size_bytes` BIGINT,
    `text_content` TEXT,
    `status` INT NOT NULL,
    `created_by` CHAR(36) NOT NULL,
    `updated_by` CHAR(36) NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`uuid`),
    INDEX `idx_artifact_run_created` (`run_uuid`, `created_at`),
    INDEX `idx_artifact_node` (`node_uuid`),
    CONSTRAINT `artifact_run`
        FOREIGN KEY (`run_uuid`)
        REFERENCES `agent_run` (`uuid`)
        ON DELETE CASCADE,
    CONSTRAINT `artifact_node`
        FOREIGN KEY (`node_uuid`)
        REFERENCES `agent_node` (`uuid`)
        ON DELETE SET NULL
) ENGINE = InnoDB;

