// Code generated by nuzur go-code-gen. DO NOT EDIT.

package core

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"

	_ "github.com/go-sql-driver/mysql"

	donaldconfig "github.com/nextwave/donald/config"
	coretypes "github.com/nextwave/donald/core/types"
	"go.uber.org/config"
	"go.uber.org/fx"
	"go.uber.org/zap"

	"github.com/nextwave/donald/core/module/client"

	"github.com/nextwave/donald/core/module/agent_run"

	"github.com/nextwave/donald/core/module/agent_node"

	"github.com/nextwave/donald/core/module/agent_edge"

	"github.com/nextwave/donald/core/module/agent_event"

	"github.com/nextwave/donald/core/module/intervention"

	"github.com/nextwave/donald/core/module/artifact"

	"github.com/nextwave/donald/core/repository"
)

type Implementation struct {
	db         *sql.DB
	repository *repository.Implementation
	logger     *zap.Logger

	client client.Module

	agent_run agent_run.Module

	agent_node agent_node.Module

	agent_edge agent_edge.Module

	agent_event agent_event.Module

	intervention intervention.Module

	artifact artifact.Module
}

type Params struct {
	fx.In
	Provider  config.Provider
	Lifecycle fx.Lifecycle
	Logger    *zap.Logger `optional:"true"`
}

func New(params Params) (*Implementation, error) {

	var dbs donaldconfig.DBs
	if err := params.Provider.Get("db").Populate(&dbs); err != nil {
		return nil, err
	}

	if len(dbs) == 0 {
		return nil, errors.New("db configuration not found")
	}

	dbconfig := dbs[0]
	db, err := sql.Open(dbconfig.Driver, dbconfig.Path())
	if err != nil {
		return nil, fmt.Errorf("error connecting to DB: %v", err)
	}
	db.SetConnMaxLifetime(0)
	db.SetMaxIdleConns(10)
	db.SetMaxOpenConns(0)
	repository := repository.New(db)

	logger := params.Logger
	if logger == nil {
		logger = zap.NewNop()
	}

	if params.Lifecycle != nil {
		params.Lifecycle.Append(fx.Hook{
			OnStart: func(ctx context.Context) error {
				// Warm the connection pool and fail fast with a clear error if the
				// database is unreachable or credentials/permissions are wrong,
				// instead of surfacing it later as a request-time timeout.
				pingCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
				defer cancel()
				if err := db.PingContext(pingCtx); err != nil {
					logger.Error("failed to connect to database on startup", zap.Error(err))
					return fmt.Errorf("error connecting to DB: %w", err)
				}
				logger.Info("connected to database")
				return nil
			},
			OnStop: func(ctx context.Context) error {
				db.Close()
				return nil
			},
		})
	}

	impl := &Implementation{
		db:         db,
		repository: repository,
		logger:     logger,
	}

	// Every module is built ONCE, here, and the accessors below just hand it
	// back. The accessors used to build their module lazily on a VALUE receiver,
	// so the assignment landed on a copy that was thrown away when the method
	// returned: every one of the (hundreds of) accessor calls in the transports
	// constructed a fresh module — with a fresh, empty 30s cache and its own
	// janitor goroutine — which is why the per-entity cache never served a hit
	// and WithSkipCache() meant nothing.
	//
	// Constructing eagerly rather than lazily on a POINTER receiver is
	// deliberate: the lazy branch would otherwise be a data race, since the
	// accessors are called concurrently from request handlers.

	impl.client = client.New(coretypes.ModuleParams{
		Repository: repository,
		Logger:     logger,
	})

	impl.agent_run = agent_run.New(coretypes.ModuleParams{
		Repository: repository,
		Logger:     logger,
	})

	impl.agent_node = agent_node.New(coretypes.ModuleParams{
		Repository: repository,
		Logger:     logger,
	})

	impl.agent_edge = agent_edge.New(coretypes.ModuleParams{
		Repository: repository,
		Logger:     logger,
	})

	impl.agent_event = agent_event.New(coretypes.ModuleParams{
		Repository: repository,
		Logger:     logger,
	})

	impl.intervention = intervention.New(coretypes.ModuleParams{
		Repository: repository,
		Logger:     logger,
	})

	impl.artifact = artifact.New(coretypes.ModuleParams{
		Repository: repository,
		Logger:     logger,
	})

	return impl, nil
}

func (i *Implementation) Destroy() {
	i.db.Close()
}

func (i *Implementation) DB() *sql.DB {
	return i.db
}

// Client returns the process-wide client module built in New.
// The receiver is a POINTER, like Destroy/DB above: a value receiver here would
// copy the struct on every call, which is how the previous lazy initialization
// came to be discarded.
func (i *Implementation) Client() client.Module {
	return i.client
}

// AgentRun returns the process-wide agent_run module built in New.
// The receiver is a POINTER, like Destroy/DB above: a value receiver here would
// copy the struct on every call, which is how the previous lazy initialization
// came to be discarded.
func (i *Implementation) AgentRun() agent_run.Module {
	return i.agent_run
}

// AgentNode returns the process-wide agent_node module built in New.
// The receiver is a POINTER, like Destroy/DB above: a value receiver here would
// copy the struct on every call, which is how the previous lazy initialization
// came to be discarded.
func (i *Implementation) AgentNode() agent_node.Module {
	return i.agent_node
}

// AgentEdge returns the process-wide agent_edge module built in New.
// The receiver is a POINTER, like Destroy/DB above: a value receiver here would
// copy the struct on every call, which is how the previous lazy initialization
// came to be discarded.
func (i *Implementation) AgentEdge() agent_edge.Module {
	return i.agent_edge
}

// AgentEvent returns the process-wide agent_event module built in New.
// The receiver is a POINTER, like Destroy/DB above: a value receiver here would
// copy the struct on every call, which is how the previous lazy initialization
// came to be discarded.
func (i *Implementation) AgentEvent() agent_event.Module {
	return i.agent_event
}

// Intervention returns the process-wide intervention module built in New.
// The receiver is a POINTER, like Destroy/DB above: a value receiver here would
// copy the struct on every call, which is how the previous lazy initialization
// came to be discarded.
func (i *Implementation) Intervention() intervention.Module {
	return i.intervention
}

// Artifact returns the process-wide artifact module built in New.
// The receiver is a POINTER, like Destroy/DB above: a value receiver here would
// copy the struct on every call, which is how the previous lazy initialization
// came to be discarded.
func (i *Implementation) Artifact() artifact.Module {
	return i.artifact
}
