// Code generated by nuzur go-code-gen. DO NOT EDIT.

package agent_edge

import (
	donalddb "github.com/nextwave/donald/core/repository/gen"
	main_entity "github.com/nextwave/donald/entity/agent_edge"

	"github.com/nextwave/donald/entity/mapper"

	"github.com/guregu/null/v6"
	"github.com/nextwave/donald/enums"
)

func mapModelsToEntities(models []donalddb.AgentEdge) []main_entity.AgentEdge {
	result := []main_entity.AgentEdge{}
	for _, p := range models {
		result = append(result, mapModelToEntity(p))
	}
	return result
}

func mapModelToEntity(m donalddb.AgentEdge) main_entity.AgentEdge {
	return main_entity.AgentEdge{
		UUID:           mapper.StringToUUID(m.UUID),
		RunUUID:        mapper.StringToUUID(m.RunUUID),
		FromNodeUUID:   mapper.StringToUUID(m.FromNodeUUID),
		ToNodeUUID:     mapper.StringToUUID(m.ToNodeUUID),
		EdgeType:       enums.AgentEdgeType(m.EdgeType),
		ConditionLabel: null.NewString(m.ConditionLabel.String, m.ConditionLabel.Valid),
		Status:         enums.AgentEdgeStatus(m.Status),
		CreatedBy:      mapper.StringToUUID(m.CreatedBy),
		UpdatedBy:      mapper.StringToUUID(m.UpdatedBy),
		CreatedAt:      m.CreatedAt,
		UpdatedAt:      m.UpdatedAt,
	}
}
