// Code generated by nuzur go-code-gen. DO NOT EDIT.

package agent_edge

import (
	"context"

	"github.com/nextwave/donald/core/module/agent_edge/types"
	donalddb "github.com/nextwave/donald/core/repository/gen"

	"github.com/gofrs/uuid"

	"time"
)

func (m *module) Insert(
	ctx context.Context,
	req types.UpsertRequest,
	opts ...Option,
) (types.UpsertResponse, error) {

	// auto-generate primary-key UUIDs for new records when not supplied by the caller
	if req.AgentEdge.UUID == uuid.Nil {
		req.AgentEdge.UUID = uuid.Must(uuid.NewV4())
	}

	// server-managed timestamps (generated created_at/updated_at)
	req.AgentEdge.CreatedAt = time.Now()
	req.AgentEdge.UpdatedAt = time.Now()

	// validate the new record against the schema's field type/type-config rules
	if err := req.AgentEdge.Validate(); err != nil {

		return types.UpsertResponse{}, err
	}

	optConfig := applyAllOptions(opts)

	tx := optConfig.SQLTx
	createdTx := false
	if tx == nil {
		ntx, err := m.repository.DB.Begin()
		if err != nil {
			return types.UpsertResponse{}, err
		}
		tx = ntx
		defer tx.Rollback()
		createdTx = true
	}

	qtx := m.repository.Queries.WithTx(tx)
	params := mapUpsertRequestToInsertParams(req)

	_, err := qtx.InsertAgentEdge(
		ctx,
		params,
	)
	if err != nil {

		return types.UpsertResponse{}, err
	}

	if createdTx {
		err := tx.Commit()
		if err != nil {

			return types.UpsertResponse{}, err
		}
	}

	// The rows this module caches have changed, so everything it holds is
	// suspect: drop it rather than answer a later read from a snapshot that
	// predates this write. The cache is per entity, so this discards only this
	// entity's reads. (It is a no-op while a caller-supplied transaction is
	// still open — those reads bypass the cache anyway.)
	m.cache.Flush()

	return buildInsertResponse(req), nil
}

func buildInsertResponse(req types.UpsertRequest) types.UpsertResponse {
	return types.UpsertResponse{

		UUID: req.AgentEdge.UUID,
	}
}

func mapUpsertRequestToInsertParams(req types.UpsertRequest) donalddb.InsertAgentEdgeParams {
	return donalddb.InsertAgentEdgeParams{
		UUID: req.AgentEdge.UUID.String(),

		RunUUID: req.AgentEdge.RunUUID.String(),

		FromNodeUUID: req.AgentEdge.FromNodeUUID.String(),

		ToNodeUUID: req.AgentEdge.ToNodeUUID.String(),

		EdgeType: req.AgentEdge.EdgeType.ToInt64(),

		ConditionLabel: req.AgentEdge.ConditionLabel,

		Status: req.AgentEdge.Status.ToInt64(),

		CreatedBy: req.AgentEdge.CreatedBy.String(),

		UpdatedBy: req.AgentEdge.UpdatedBy.String(),

		CreatedAt: req.AgentEdge.CreatedAt,

		UpdatedAt: req.AgentEdge.UpdatedAt,
	}
}
