// Code generated by nuzur go-code-gen. DO NOT EDIT.

package artifact

import (
	donalddb "github.com/nextwave/donald/core/repository/gen"
	main_entity "github.com/nextwave/donald/entity/artifact"

	"github.com/nextwave/donald/entity/mapper"

	"github.com/guregu/null/v6"
	"github.com/nextwave/donald/enums"
)

func mapModelsToEntities(models []donalddb.Artifact) []main_entity.Artifact {
	result := []main_entity.Artifact{}
	for _, p := range models {
		result = append(result, mapModelToEntity(p))
	}
	return result
}

func mapModelToEntity(m donalddb.Artifact) main_entity.Artifact {
	return main_entity.Artifact{
		UUID:         mapper.StringToUUID(m.UUID),
		RunUUID:      mapper.StringToUUID(m.RunUUID),
		NodeUUID:     mapper.StringToUUIDPtr(m.NodeUUID),
		Name:         m.Name,
		ArtifactType: enums.ArtifactType(m.ArtifactType),
		Content:      null.NewString(m.Content.String, m.Content.Valid),
		URL:          null.NewString(m.URL.String, m.URL.Valid),
		ContentType:  null.NewString(m.ContentType.String, m.ContentType.Valid),
		SizeBytes:    null.NewInt(m.SizeBytes.Int64, m.SizeBytes.Valid),
		TextContent:  null.NewString(m.TextContent.String, m.TextContent.Valid),
		Status:       enums.ArtifactStatus(m.Status),
		CreatedBy:    mapper.StringToUUID(m.CreatedBy),
		UpdatedBy:    mapper.StringToUUID(m.UpdatedBy),
		CreatedAt:    m.CreatedAt,
		UpdatedAt:    m.UpdatedAt,
	}
}
