// Code generated by nuzur go-code-gen. DO NOT EDIT.

package artifact

import (
	"context"
	"errors"

	"github.com/nextwave/donald/core/module/artifact/types"
	donalddb "github.com/nextwave/donald/core/repository/gen"

	"time"

	"github.com/nextwave/donald/entity/mapper"
)

func (m *module) Update(
	ctx context.Context,
	req types.UpsertRequest,
	opts ...Option,
) (types.UpsertResponse, error) {
	optConfig := applyAllOptions(opts)

	tx := optConfig.SQLTx
	createdTx := false
	if tx == nil {
		ntx, err := m.repository.DB.Begin()
		if err != nil {
			return types.UpsertResponse{}, err
		}
		tx = ntx
		defer tx.Rollback()
		createdTx = true
	}

	qtx := m.repository.Queries.WithTx(tx)
	existing, err := qtx.FetchArtifactByUUIDForUpdate(ctx,
		req.Artifact.UUID.String(),
	)
	if err != nil {

		return types.UpsertResponse{}, err
	}

	if len(existing) == 0 {
		err := errors.New("entity not found")

		return types.UpsertResponse{}, err
	}

	// refresh server-managed timestamps that update on every write (updated_at)
	req.Artifact.UpdatedAt = time.Now()

	// validate the merged entity against the schema's field type/type-config rules
	if err := req.Artifact.Validate(); err != nil {

		return types.UpsertResponse{}, err
	}

	params := mapUpsertRequestToUpdateParams(req)
	err = qtx.UpdateArtifact(
		ctx,
		params,
	)
	if err != nil {

		return types.UpsertResponse{}, err
	}

	if createdTx {
		err := tx.Commit()
		if err != nil {

			return types.UpsertResponse{}, err
		}
	}

	// The rows this module caches have changed, so everything it holds is
	// suspect: drop it rather than answer a later read from a snapshot that
	// predates this write. The cache is per entity, so this discards only this
	// entity's reads. (It is a no-op while a caller-supplied transaction is
	// still open — those reads bypass the cache anyway.)
	m.cache.Flush()

	return buildUpdateResponse(req), nil
}

func buildUpdateResponse(req types.UpsertRequest) types.UpsertResponse {
	return types.UpsertResponse{

		UUID: req.Artifact.UUID,
	}
}

func mapUpsertRequestToUpdateParams(req types.UpsertRequest) donalddb.UpdateArtifactParams {
	return donalddb.UpdateArtifactParams{
		UUID: req.Artifact.UUID.String(),

		RunUUID: req.Artifact.RunUUID.String(),

		NodeUUID: mapper.UUIDPtrToNullString(req.Artifact.NodeUUID),

		Name: req.Artifact.Name,

		ArtifactType: req.Artifact.ArtifactType.ToInt64(),

		Content: req.Artifact.Content,

		URL: req.Artifact.URL,

		ContentType: req.Artifact.ContentType,

		SizeBytes: req.Artifact.SizeBytes,

		TextContent: req.Artifact.TextContent,

		Status: req.Artifact.Status.ToInt64(),

		CreatedBy: req.Artifact.CreatedBy.String(),

		UpdatedBy: req.Artifact.UpdatedBy.String(),

		CreatedAt: req.Artifact.CreatedAt,

		UpdatedAt: req.Artifact.UpdatedAt,
	}
}
