// Code generated by nuzur go-code-gen. DO NOT EDIT.

package artifact

import (
	"context"

	"github.com/nextwave/donald/core/module/artifact/types"
	donalddb "github.com/nextwave/donald/core/repository/gen"

	"github.com/gofrs/uuid"

	"time"

	"github.com/nextwave/donald/entity/mapper"
)

func (m *module) Insert(
	ctx context.Context,
	req types.UpsertRequest,
	opts ...Option,
) (types.UpsertResponse, error) {

	// auto-generate primary-key UUIDs for new records when not supplied by the caller
	if req.Artifact.UUID == uuid.Nil {
		req.Artifact.UUID = uuid.Must(uuid.NewV4())
	}

	// server-managed timestamps (generated created_at/updated_at)
	req.Artifact.CreatedAt = time.Now()
	req.Artifact.UpdatedAt = time.Now()

	// validate the new record against the schema's field type/type-config rules
	if err := req.Artifact.Validate(); err != nil {

		return types.UpsertResponse{}, err
	}

	optConfig := applyAllOptions(opts)

	tx := optConfig.SQLTx
	createdTx := false
	if tx == nil {
		ntx, err := m.repository.DB.Begin()
		if err != nil {
			return types.UpsertResponse{}, err
		}
		tx = ntx
		defer tx.Rollback()
		createdTx = true
	}

	qtx := m.repository.Queries.WithTx(tx)
	params := mapUpsertRequestToInsertParams(req)

	_, err := qtx.InsertArtifact(
		ctx,
		params,
	)
	if err != nil {

		return types.UpsertResponse{}, err
	}

	if createdTx {
		err := tx.Commit()
		if err != nil {

			return types.UpsertResponse{}, err
		}
	}

	// The rows this module caches have changed, so everything it holds is
	// suspect: drop it rather than answer a later read from a snapshot that
	// predates this write. The cache is per entity, so this discards only this
	// entity's reads. (It is a no-op while a caller-supplied transaction is
	// still open — those reads bypass the cache anyway.)
	m.cache.Flush()

	return buildInsertResponse(req), nil
}

func buildInsertResponse(req types.UpsertRequest) types.UpsertResponse {
	return types.UpsertResponse{

		UUID: req.Artifact.UUID,
	}
}

func mapUpsertRequestToInsertParams(req types.UpsertRequest) donalddb.InsertArtifactParams {
	return donalddb.InsertArtifactParams{
		UUID: req.Artifact.UUID.String(),

		RunUUID: req.Artifact.RunUUID.String(),

		NodeUUID: mapper.UUIDPtrToNullString(req.Artifact.NodeUUID),

		Name: req.Artifact.Name,

		ArtifactType: req.Artifact.ArtifactType.ToInt64(),

		Content: req.Artifact.Content,

		URL: req.Artifact.URL,

		ContentType: req.Artifact.ContentType,

		SizeBytes: req.Artifact.SizeBytes,

		TextContent: req.Artifact.TextContent,

		Status: req.Artifact.Status.ToInt64(),

		CreatedBy: req.Artifact.CreatedBy.String(),

		UpdatedBy: req.Artifact.UpdatedBy.String(),

		CreatedAt: req.Artifact.CreatedAt,

		UpdatedAt: req.Artifact.UpdatedAt,
	}
}
