-- Code generated by nuzur go-code-gen. DO NOT EDIT.
-- name: DeleteClient :execresult
DELETE FROM `client`
WHERE
`uuid` = ?;

-- name: DeleteAgentRun :execresult
DELETE FROM `agent_run`
WHERE
`uuid` = ?;

-- name: DeleteAgentNode :execresult
DELETE FROM `agent_node`
WHERE
`uuid` = ?;

-- name: DeleteAgentEdge :execresult
DELETE FROM `agent_edge`
WHERE
`uuid` = ?;

-- name: DeleteAgentEvent :execresult
DELETE FROM `agent_event`
WHERE
`uuid` = ?;

-- name: DeleteIntervention :execresult
DELETE FROM `intervention`
WHERE
`uuid` = ?;

-- name: DeleteArtifact :execresult
DELETE FROM `artifact`
WHERE
`uuid` = ?;

