-- Code generated by nuzur go-code-gen. DO NOT EDIT.
-- name: InsertClient :execresult
INSERT INTO `client`
(`uuid`,`name`,`industry`,`created_by`,`updated_by`,`status`,`created_at`,`updated_at`)
VALUES
(?,?,?,?,?,?,?,?);

-- name: InsertAgentRun :execresult
INSERT INTO `agent_run`
(`uuid`,`client_uuid`,`run_key`,`name`,`display_summary`,`agent_summary`,`agent_identifier`,`initial_prompt`,`protocol_version`,`status`,`status_message`,`graph_revision`,`last_event_sequence`,`started_at`,`finished_at`,`last_heartbeat_at`,`created_by`,`updated_by`,`created_at`,`updated_at`)
VALUES
(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);

-- name: InsertAgentNode :execresult
INSERT INTO `agent_node`
(`uuid`,`run_uuid`,`node_key`,`name`,`description`,`node_type`,`agent_label`,`tool_name`,`status`,`status_message`,`error_message`,`progress_percent`,`plan_order`,`planned`,`input_summary`,`output_summary`,`started_at`,`finished_at`,`created_by`,`updated_by`,`created_at`,`updated_at`)
VALUES
(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);

-- name: InsertAgentEdge :execresult
INSERT INTO `agent_edge`
(`uuid`,`run_uuid`,`from_node_uuid`,`to_node_uuid`,`edge_type`,`condition_label`,`status`,`created_by`,`updated_by`,`created_at`,`updated_at`)
VALUES
(?,?,?,?,?,?,?,?,?,?,?);

-- name: InsertAgentEvent :execresult
INSERT INTO `agent_event`
(`uuid`,`run_uuid`,`sequence`,`event_type`,`node_uuid`,`agent_label`,`idempotency_key`,`occurred_at`,`status`,`created_by`,`updated_by`,`created_at`,`updated_at`,`payload`)
VALUES
(?,?,?,?,?,?,?,?,?,?,?,?,?,?);

-- name: InsertIntervention :execresult
INSERT INTO `intervention`
(`uuid`,`run_uuid`,`node_uuid`,`type`,`prompt`,`status`,`status_message`,`requested_by_uuid`,`resolved_by_uuid`,`delivered_at`,`resolved_at`,`expires_at`,`created_by`,`updated_by`,`created_at`,`updated_at`,`interactions`)
VALUES
(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);

-- name: InsertArtifact :execresult
INSERT INTO `artifact`
(`uuid`,`run_uuid`,`node_uuid`,`name`,`artifact_type`,`content`,`url`,`content_type`,`size_bytes`,`text_content`,`status`,`created_by`,`updated_by`,`created_at`,`updated_at`)
VALUES
(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);

