-- Code generated by nuzur go-code-gen. DO NOT EDIT.


-- client selects:
-- name: FetchClientByUUID :many
SELECT `uuid`,`name`,`industry`,`created_by`,`updated_by`,`status`,`created_at`,`updated_at`
FROM `client`
WHERE 
    `uuid` = ? ;

        
-- name: FetchClientByUUIDForUpdate :many
SELECT `uuid`,`name`,`industry`,`created_by`,`updated_by`,`status`,`created_at`,`updated_at`
FROM `client`
WHERE 
    `uuid` = ? 
FOR UPDATE;
        




-- agent_run selects:
-- name: FetchAgentRunByUUID :many
SELECT `uuid`,`client_uuid`,`run_key`,`name`,`display_summary`,`agent_summary`,`agent_identifier`,`initial_prompt`,`protocol_version`,`status`,`status_message`,`graph_revision`,`last_event_sequence`,`started_at`,`finished_at`,`last_heartbeat_at`,`created_by`,`updated_by`,`created_at`,`updated_at`
FROM `agent_run`
WHERE 
    `uuid` = ? ;

        
-- name: FetchAgentRunByClientUUIDAndRunKey :many
SELECT `uuid`,`client_uuid`,`run_key`,`name`,`display_summary`,`agent_summary`,`agent_identifier`,`initial_prompt`,`protocol_version`,`status`,`status_message`,`graph_revision`,`last_event_sequence`,`started_at`,`finished_at`,`last_heartbeat_at`,`created_by`,`updated_by`,`created_at`,`updated_at`
FROM `agent_run`
WHERE 
    `client_uuid` = ? AND `run_key` = ? 
LIMIT ?, ?;
        
-- name: FetchAgentRunByClientUUIDAndStatus :many
SELECT `uuid`,`client_uuid`,`run_key`,`name`,`display_summary`,`agent_summary`,`agent_identifier`,`initial_prompt`,`protocol_version`,`status`,`status_message`,`graph_revision`,`last_event_sequence`,`started_at`,`finished_at`,`last_heartbeat_at`,`created_by`,`updated_by`,`created_at`,`updated_at`
FROM `agent_run`
WHERE 
    `client_uuid` = ? AND `status` = ? 
LIMIT ?, ?;
        
-- name: FetchAgentRunByUUIDForUpdate :many
SELECT `uuid`,`client_uuid`,`run_key`,`name`,`display_summary`,`agent_summary`,`agent_identifier`,`initial_prompt`,`protocol_version`,`status`,`status_message`,`graph_revision`,`last_event_sequence`,`started_at`,`finished_at`,`last_heartbeat_at`,`created_by`,`updated_by`,`created_at`,`updated_at`
FROM `agent_run`
WHERE 
    `uuid` = ? 
FOR UPDATE;
        




-- agent_node selects:
-- name: FetchAgentNodeByUUID :many
SELECT `uuid`,`run_uuid`,`node_key`,`name`,`description`,`node_type`,`agent_label`,`tool_name`,`status`,`status_message`,`error_message`,`progress_percent`,`plan_order`,`planned`,`input_summary`,`output_summary`,`started_at`,`finished_at`,`created_by`,`updated_by`,`created_at`,`updated_at`
FROM `agent_node`
WHERE 
    `uuid` = ? ;

        
-- name: FetchAgentNodeByRunUUIDAndNodeKey :many
SELECT `uuid`,`run_uuid`,`node_key`,`name`,`description`,`node_type`,`agent_label`,`tool_name`,`status`,`status_message`,`error_message`,`progress_percent`,`plan_order`,`planned`,`input_summary`,`output_summary`,`started_at`,`finished_at`,`created_by`,`updated_by`,`created_at`,`updated_at`
FROM `agent_node`
WHERE 
    `node_key` = ? AND `run_uuid` = ? 
LIMIT ?, ?;
        
-- name: FetchAgentNodeByRunUUIDAndStatus :many
SELECT `uuid`,`run_uuid`,`node_key`,`name`,`description`,`node_type`,`agent_label`,`tool_name`,`status`,`status_message`,`error_message`,`progress_percent`,`plan_order`,`planned`,`input_summary`,`output_summary`,`started_at`,`finished_at`,`created_by`,`updated_by`,`created_at`,`updated_at`
FROM `agent_node`
WHERE 
    `run_uuid` = ? AND `status` = ? 
LIMIT ?, ?;
        
-- name: FetchAgentNodeByUUIDForUpdate :many
SELECT `uuid`,`run_uuid`,`node_key`,`name`,`description`,`node_type`,`agent_label`,`tool_name`,`status`,`status_message`,`error_message`,`progress_percent`,`plan_order`,`planned`,`input_summary`,`output_summary`,`started_at`,`finished_at`,`created_by`,`updated_by`,`created_at`,`updated_at`
FROM `agent_node`
WHERE 
    `uuid` = ? 
FOR UPDATE;
        




-- agent_edge selects:
-- name: FetchAgentEdgeByUUID :many
SELECT `uuid`,`run_uuid`,`from_node_uuid`,`to_node_uuid`,`edge_type`,`condition_label`,`status`,`created_by`,`updated_by`,`created_at`,`updated_at`
FROM `agent_edge`
WHERE 
    `uuid` = ? ;

        
-- name: FetchAgentEdgeByFromNodeUUIDAndToNodeUUIDAndEdgeType :many
SELECT `uuid`,`run_uuid`,`from_node_uuid`,`to_node_uuid`,`edge_type`,`condition_label`,`status`,`created_by`,`updated_by`,`created_at`,`updated_at`
FROM `agent_edge`
WHERE 
    `edge_type` = ? AND `from_node_uuid` = ? AND `to_node_uuid` = ? 
LIMIT ?, ?;
        
-- name: FetchAgentEdgeByRunUUID :many
SELECT `uuid`,`run_uuid`,`from_node_uuid`,`to_node_uuid`,`edge_type`,`condition_label`,`status`,`created_by`,`updated_by`,`created_at`,`updated_at`
FROM `agent_edge`
WHERE 
    `run_uuid` = ? 
LIMIT ?, ?;
        
-- name: FetchAgentEdgeByToNodeUUID :many
SELECT `uuid`,`run_uuid`,`from_node_uuid`,`to_node_uuid`,`edge_type`,`condition_label`,`status`,`created_by`,`updated_by`,`created_at`,`updated_at`
FROM `agent_edge`
WHERE 
    `to_node_uuid` = ? 
LIMIT ?, ?;
        
-- name: FetchAgentEdgeByUUIDForUpdate :many
SELECT `uuid`,`run_uuid`,`from_node_uuid`,`to_node_uuid`,`edge_type`,`condition_label`,`status`,`created_by`,`updated_by`,`created_at`,`updated_at`
FROM `agent_edge`
WHERE 
    `uuid` = ? 
FOR UPDATE;
        




-- agent_event selects:
-- name: FetchAgentEventByUUID :many
SELECT `uuid`,`run_uuid`,`sequence`,`event_type`,`node_uuid`,`agent_label`,`idempotency_key`,`occurred_at`,`status`,`created_by`,`updated_by`,`created_at`,`updated_at`,`payload`
FROM `agent_event`
WHERE 
    `uuid` = ? ;

        
-- name: FetchAgentEventByRunUUIDAndSequence :many
SELECT `uuid`,`run_uuid`,`sequence`,`event_type`,`node_uuid`,`agent_label`,`idempotency_key`,`occurred_at`,`status`,`created_by`,`updated_by`,`created_at`,`updated_at`,`payload`
FROM `agent_event`
WHERE 
    `run_uuid` = ? AND `sequence` = ? 
LIMIT ?, ?;
        
-- name: FetchAgentEventByRunUUIDAndIdempotencyKey :many
SELECT `uuid`,`run_uuid`,`sequence`,`event_type`,`node_uuid`,`agent_label`,`idempotency_key`,`occurred_at`,`status`,`created_by`,`updated_by`,`created_at`,`updated_at`,`payload`
FROM `agent_event`
WHERE 
    `idempotency_key` = ? AND `run_uuid` = ? 
LIMIT ?, ?;
        
-- name: FetchAgentEventByNodeUUIDAndSequence :many
SELECT `uuid`,`run_uuid`,`sequence`,`event_type`,`node_uuid`,`agent_label`,`idempotency_key`,`occurred_at`,`status`,`created_by`,`updated_by`,`created_at`,`updated_at`,`payload`
FROM `agent_event`
WHERE 
    `node_uuid` = ? AND `sequence` = ? 
LIMIT ?, ?;
        
-- name: FetchAgentEventByUUIDForUpdate :many
SELECT `uuid`,`run_uuid`,`sequence`,`event_type`,`node_uuid`,`agent_label`,`idempotency_key`,`occurred_at`,`status`,`created_by`,`updated_by`,`created_at`,`updated_at`,`payload`
FROM `agent_event`
WHERE 
    `uuid` = ? 
FOR UPDATE;
        




-- intervention selects:
-- name: FetchInterventionByUUID :many
SELECT `uuid`,`run_uuid`,`node_uuid`,`type`,`prompt`,`status`,`status_message`,`requested_by_uuid`,`resolved_by_uuid`,`delivered_at`,`resolved_at`,`expires_at`,`created_by`,`updated_by`,`created_at`,`updated_at`,`interactions`
FROM `intervention`
WHERE 
    `uuid` = ? ;

        
-- name: FetchInterventionByRunUUIDAndStatus :many
SELECT `uuid`,`run_uuid`,`node_uuid`,`type`,`prompt`,`status`,`status_message`,`requested_by_uuid`,`resolved_by_uuid`,`delivered_at`,`resolved_at`,`expires_at`,`created_by`,`updated_by`,`created_at`,`updated_at`,`interactions`
FROM `intervention`
WHERE 
    `run_uuid` = ? AND `status` = ? 
LIMIT ?, ?;
        
-- name: FetchInterventionByNodeUUID :many
SELECT `uuid`,`run_uuid`,`node_uuid`,`type`,`prompt`,`status`,`status_message`,`requested_by_uuid`,`resolved_by_uuid`,`delivered_at`,`resolved_at`,`expires_at`,`created_by`,`updated_by`,`created_at`,`updated_at`,`interactions`
FROM `intervention`
WHERE 
    `node_uuid` = ? 
LIMIT ?, ?;
        
-- name: FetchInterventionByUUIDForUpdate :many
SELECT `uuid`,`run_uuid`,`node_uuid`,`type`,`prompt`,`status`,`status_message`,`requested_by_uuid`,`resolved_by_uuid`,`delivered_at`,`resolved_at`,`expires_at`,`created_by`,`updated_by`,`created_at`,`updated_at`,`interactions`
FROM `intervention`
WHERE 
    `uuid` = ? 
FOR UPDATE;
        




-- artifact selects:
-- name: FetchArtifactByUUID :many
SELECT `uuid`,`run_uuid`,`node_uuid`,`name`,`artifact_type`,`content`,`url`,`content_type`,`size_bytes`,`text_content`,`status`,`created_by`,`updated_by`,`created_at`,`updated_at`
FROM `artifact`
WHERE 
    `uuid` = ? ;

        
-- name: FetchArtifactByRunUUID :many
SELECT `uuid`,`run_uuid`,`node_uuid`,`name`,`artifact_type`,`content`,`url`,`content_type`,`size_bytes`,`text_content`,`status`,`created_by`,`updated_by`,`created_at`,`updated_at`
FROM `artifact`
WHERE 
    `run_uuid` = ? 
LIMIT ?, ?;
        
-- name: FetchArtifactByNodeUUID :many
SELECT `uuid`,`run_uuid`,`node_uuid`,`name`,`artifact_type`,`content`,`url`,`content_type`,`size_bytes`,`text_content`,`status`,`created_by`,`updated_by`,`created_at`,`updated_at`
FROM `artifact`
WHERE 
    `node_uuid` = ? 
LIMIT ?, ?;
        
-- name: FetchArtifactByUUIDForUpdate :many
SELECT `uuid`,`run_uuid`,`node_uuid`,`name`,`artifact_type`,`content`,`url`,`content_type`,`size_bytes`,`text_content`,`status`,`created_by`,`updated_by`,`created_at`,`updated_at`
FROM `artifact`
WHERE 
    `uuid` = ? 
FOR UPDATE;
        


