-- Code generated by nuzur go-code-gen. DO NOT EDIT.
-- name: FetchClient :many
SELECT `uuid`,`name`,`industry`,`created_by`,`updated_by`,`status`,`created_at`,`updated_at`
FROM `client`;

-- name: FetchAgentRun :many
SELECT `uuid`,`client_uuid`,`run_key`,`name`,`display_summary`,`agent_summary`,`agent_identifier`,`initial_prompt`,`protocol_version`,`status`,`status_message`,`graph_revision`,`last_event_sequence`,`started_at`,`finished_at`,`last_heartbeat_at`,`created_by`,`updated_by`,`created_at`,`updated_at`
FROM `agent_run`;

-- name: FetchAgentNode :many
SELECT `uuid`,`run_uuid`,`node_key`,`name`,`description`,`node_type`,`agent_label`,`tool_name`,`status`,`status_message`,`error_message`,`progress_percent`,`plan_order`,`planned`,`input_summary`,`output_summary`,`started_at`,`finished_at`,`created_by`,`updated_by`,`created_at`,`updated_at`
FROM `agent_node`;

-- name: FetchAgentEdge :many
SELECT `uuid`,`run_uuid`,`from_node_uuid`,`to_node_uuid`,`edge_type`,`condition_label`,`status`,`created_by`,`updated_by`,`created_at`,`updated_at`
FROM `agent_edge`;

-- name: FetchAgentEvent :many
SELECT `uuid`,`run_uuid`,`sequence`,`event_type`,`node_uuid`,`agent_label`,`idempotency_key`,`occurred_at`,`status`,`created_by`,`updated_by`,`created_at`,`updated_at`,`payload`
FROM `agent_event`;

-- name: FetchIntervention :many
SELECT `uuid`,`run_uuid`,`node_uuid`,`type`,`prompt`,`status`,`status_message`,`requested_by_uuid`,`resolved_by_uuid`,`delivered_at`,`resolved_at`,`expires_at`,`created_by`,`updated_by`,`created_at`,`updated_at`,`interactions`
FROM `intervention`;

-- name: FetchArtifact :many
SELECT `uuid`,`run_uuid`,`node_uuid`,`name`,`artifact_type`,`content`,`url`,`content_type`,`size_bytes`,`text_content`,`status`,`created_by`,`updated_by`,`created_at`,`updated_at`
FROM `artifact`;

