// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nextwave/donald/entity/agent_edge"

	"github.com/gofrs/uuid"
	"github.com/nextwave/donald/enums"
	"go.uber.org/zap/zapcore"
)

type FetchAgentEdgeByFromNodeUUIDAndToNodeUUIDAndEdgeTypeRequest struct {
	FromNodeUUID uuid.UUID
	ToNodeUUID   uuid.UUID
	EdgeType     enums.AgentEdgeType

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchAgentEdgeByFromNodeUUIDAndToNodeUUIDAndEdgeTypeRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("from_node_uuid", r.FromNodeUUID.String())

	e.AddString("to_node_uuid", r.ToNodeUUID.String())

	return nil
}

type FetchAgentEdgeByFromNodeUUIDAndToNodeUUIDAndEdgeTypeResponse struct {
	Results []main_entity.AgentEdge
}
