// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nextwave/donald/entity/agent_edge"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchAgentEdgeByUUIDRequest struct {
	UUID uuid.UUID
}

func (r FetchAgentEdgeByUUIDRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("uuid", r.UUID.String())

	return nil
}

type FetchAgentEdgeByUUIDResponse struct {
	Results []main_entity.AgentEdge
}
