// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nextwave/donald/entity/agent_edge"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchAgentEdgeByToNodeUUIDRequest struct {
	ToNodeUUID uuid.UUID

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchAgentEdgeByToNodeUUIDRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("to_node_uuid", r.ToNodeUUID.String())

	return nil
}

type FetchAgentEdgeByToNodeUUIDResponse struct {
	Results []main_entity.AgentEdge
}
