// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nextwave/donald/entity/agent_edge"

	"github.com/gofrs/uuid"
)

type UpsertRequest struct {
	AgentEdge main_entity.AgentEdge
}

type UpsertResponse struct {
	UUID uuid.UUID
}
