// Code generated by nuzur go-code-gen. DO NOT EDIT.

package agent_event_payload

import (
	"github.com/nextwave/donald/entity/validation"
)

// Validate checks this AgentEventPayload against the schema's field type and
// type-config rules, aggregating every problem into a single *validation.Error.
// It mirrors the change-request data validation enforced in
// product/module/datavalidation, so data written through this API is held to
// the same rules. Generated by go-code-gen — do not edit.
func (e AgentEventPayload) Validate() error {
	c := validation.NewCollector()
	if e.PreviousStatus.ToInt64() != 0 {
		c.Field("agent_event_payload.previous_status", validation.EnumMember(e.PreviousStatus.ToInt64(), []int64{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, "agent_node_status"))

	}
	if e.NewStatus.ToInt64() != 0 {
		c.Field("agent_event_payload.new_status", validation.EnumMember(e.NewStatus.ToInt64(), []int64{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, "agent_node_status"))

	}
	if e.ProgressPercent.Valid {
		c.Field("agent_event_payload.progress_percent", validation.Integer(e.ProgressPercent.Int64, false, 0, 0, false, false, false, true, -32768, 32767))

	}

	return c.Result()
}
