// Code generated by nuzur go-code-gen. DO NOT EDIT.

package agent_event_payload

import (
	entitytypes "github.com/nextwave/donald/entity/types"
)

func (e AgentEventPayload) FieldIdentifierToTypeMap() map[string]entitytypes.FieldType {
	return map[string]entitytypes.FieldType{
		"previous_status":   entitytypes.SingleEnumFieldType,
		"new_status":        entitytypes.SingleEnumFieldType,
		"message":           entitytypes.StringFieldType,
		"progress_percent":  entitytypes.IntFieldType,
		"edge_uuid":         entitytypes.StringFieldType,
		"artifact_uuid":     entitytypes.StringFieldType,
		"intervention_uuid": entitytypes.StringFieldType,
		"detail":            entitytypes.StringFieldType,
	}
}

func (e AgentEventPayload) OrderedFieldIdentifiers() []string {
	res := []string{}
	res = append(res, "previous_status")
	res = append(res, "new_status")
	res = append(res, "message")
	res = append(res, "progress_percent")
	res = append(res, "edge_uuid")
	res = append(res, "artifact_uuid")
	res = append(res, "intervention_uuid")
	res = append(res, "detail")

	return res
}

func (e AgentEventPayload) DependantFieldIdentifierToTypeMap() map[string]map[string]entitytypes.FieldType {
	res := make(map[string]map[string]entitytypes.FieldType)

	return res
}

func (e AgentEventPayload) EntityIdentifier() string {
	return "agent_event_payload"
}

func (e AgentEventPayload) PrimaryKeyIdentifiers() []string {
	return []string{}
}

func (e AgentEventPayload) ArrayFieldIdentifierToType() map[string]entitytypes.FieldType {
	res := make(map[string]entitytypes.FieldType)

	return res
}
