// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nextwave/donald/entity/intervention"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchInterventionByUUIDRequest struct {
	UUID uuid.UUID
}

func (r FetchInterventionByUUIDRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("uuid", r.UUID.String())

	return nil
}

type FetchInterventionByUUIDResponse struct {
	Results []main_entity.Intervention
}
