// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nextwave/donald/entity/intervention"

	"github.com/gofrs/uuid"
	"github.com/nextwave/donald/enums"
	"go.uber.org/zap/zapcore"
)

type FetchInterventionByRunUUIDAndStatusRequest struct {
	RunUUID uuid.UUID
	Status  enums.InterventionStatus

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchInterventionByRunUUIDAndStatusRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("run_uuid", r.RunUUID.String())

	return nil
}

type FetchInterventionByRunUUIDAndStatusResponse struct {
	Results []main_entity.Intervention
}
