// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nextwave/donald/entity/intervention"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchInterventionByNodeUUIDRequest struct {
	NodeUUID uuid.UUID

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchInterventionByNodeUUIDRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("node_uuid", r.NodeUUID.String())

	return nil
}

type FetchInterventionByNodeUUIDResponse struct {
	Results []main_entity.Intervention
}
