// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nextwave/donald/entity/intervention"

	"github.com/gofrs/uuid"
)

type UpsertRequest struct {
	Intervention main_entity.Intervention
}

type UpsertResponse struct {
	UUID uuid.UUID
}
