// Code generated by nuzur go-code-gen. DO NOT EDIT.

package agent_node

import (
	"encoding/json"
	"log"

	"github.com/gofrs/uuid"
	"github.com/guregu/null/v6"
	"github.com/nextwave/donald/enums"
	"time"

	"github.com/nextwave/donald/entity/mapper"
)

type AgentNode struct {
	UUID            uuid.UUID             `json:"uuid"`
	RunUUID         uuid.UUID             `json:"run_uuid"`
	NodeKey         string                `json:"node_key"`
	Name            string                `json:"name"`
	Description     null.String           `json:"description"`
	NodeType        enums.AgentNodeType   `json:"node_type"`
	AgentLabel      null.String           `json:"agent_label"`
	ToolName        null.String           `json:"tool_name"`
	Status          enums.AgentNodeStatus `json:"status"`
	StatusMessage   null.String           `json:"status_message"`
	ErrorMessage    null.String           `json:"error_message"`
	ProgressPercent null.Int64            `json:"progress_percent"`
	PlanOrder       null.Int64            `json:"plan_order"`
	Planned         bool                  `json:"planned"`
	InputSummary    null.String           `json:"input_summary"`
	OutputSummary   null.String           `json:"output_summary"`
	StartedAt       null.Time             `json:"started_at"`
	FinishedAt      null.Time             `json:"finished_at"`
	CreatedBy       uuid.UUID             `json:"created_by"`
	UpdatedBy       uuid.UUID             `json:"updated_by"`
	CreatedAt       time.Time             `json:"created_at"`
	UpdatedAt       time.Time             `json:"updated_at"`
}

func (e AgentNode) String() string {
	res, _ := json.Marshal(e)
	return string(res)
}

func (e AgentNode) PrimaryKeyValues() []string {
	return []string{
		e.UUID.String(),
	}
}

// The parameter is a plain []byte rather than json.RawMessage so that both a
// json.RawMessage and the mapper.JSON a repository model holds can be passed
// without a conversion at the call site.
func AgentNodeFromJSON(data []byte) AgentNode {
	entity := AgentNode{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		if err2 := mapper.FlexibleUnmarshal(data, &entity); err2 != nil {
			log.Printf("flexible unmarshal error AgentNodeFromJSON: %v\n", err2)
		}
	}
	return entity
}

func AgentNodeSliceFromJSON(data []byte) []AgentNode {
	entity := []AgentNode{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		entity = []AgentNode{}
		var rawSlice []json.RawMessage
		if err2 := json.Unmarshal(data, &rawSlice); err2 == nil {
			for _, raw := range rawSlice {
				item := AgentNode{}
				if err3 := mapper.FlexibleUnmarshal(raw, &item); err3 != nil {
					log.Printf("flexible unmarshal error AgentNodeSliceFromJSON item: %v\n", err3)
				}
				entity = append(entity, item)
			}
		}
	}
	return entity
}

func (e AgentNode) ToJSON() json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error AgentNodeToJSON: %v\n", err)
		return json.RawMessage("null")
	}
	return res
}

func AgentNodeToJSON(e AgentNode) json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error AgentNodeToJSON: %v\n", err)
		return json.RawMessage("null")
	}
	return res
}

// AgentNodeSliceToJSON serializes a ONE_TO_MANY embed for its JSON column.
// An absent embed is the EMPTY ARRAY, never a zero-length json.RawMessage: a
// zero-length value reaches the driver as the empty string, which is not valid
// JSON, so a create that simply omitted an optional array embed was rejected by
// the database ("invalid input syntax for type json", MySQL error 3140) and
// surfaced as a 500. "[]" is also exactly what an explicit `"field": []` stores,
// so the omitted and the explicitly-empty request round-trip to the same value.
func AgentNodeSliceToJSON(e []AgentNode) json.RawMessage {
	if e == nil {
		return json.RawMessage("[]")
	}
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error AgentNodeSliceToJSON: %v\n", err)
		return json.RawMessage("[]")
	}
	return res
}
