// Code generated by nuzur go-code-gen. DO NOT EDIT.

package agent_node

import (
	entitytypes "github.com/nextwave/donald/entity/types"
)

func (e AgentNode) FieldIdentifierToTypeMap() map[string]entitytypes.FieldType {
	return map[string]entitytypes.FieldType{
		"uuid":             entitytypes.StringFieldType,
		"run_uuid":         entitytypes.StringFieldType,
		"node_key":         entitytypes.StringFieldType,
		"name":             entitytypes.StringFieldType,
		"description":      entitytypes.StringFieldType,
		"node_type":        entitytypes.SingleEnumFieldType,
		"agent_label":      entitytypes.StringFieldType,
		"tool_name":        entitytypes.StringFieldType,
		"status":           entitytypes.SingleEnumFieldType,
		"status_message":   entitytypes.StringFieldType,
		"error_message":    entitytypes.StringFieldType,
		"progress_percent": entitytypes.IntFieldType,
		"plan_order":       entitytypes.IntFieldType,
		"planned":          entitytypes.BooleanFieldType,
		"input_summary":    entitytypes.StringFieldType,
		"output_summary":   entitytypes.StringFieldType,
		"started_at":       entitytypes.TimestampFieldType,
		"finished_at":      entitytypes.TimestampFieldType,
		"created_by":       entitytypes.StringFieldType,
		"updated_by":       entitytypes.StringFieldType,
		"created_at":       entitytypes.TimestampFieldType,
		"updated_at":       entitytypes.TimestampFieldType,
	}
}

func (e AgentNode) OrderedFieldIdentifiers() []string {
	res := []string{}
	res = append(res, "uuid")
	res = append(res, "run_uuid")
	res = append(res, "node_key")
	res = append(res, "name")
	res = append(res, "description")
	res = append(res, "node_type")
	res = append(res, "agent_label")
	res = append(res, "tool_name")
	res = append(res, "status")
	res = append(res, "status_message")
	res = append(res, "error_message")
	res = append(res, "progress_percent")
	res = append(res, "plan_order")
	res = append(res, "planned")
	res = append(res, "input_summary")
	res = append(res, "output_summary")
	res = append(res, "started_at")
	res = append(res, "finished_at")
	res = append(res, "created_by")
	res = append(res, "updated_by")
	res = append(res, "created_at")
	res = append(res, "updated_at")

	return res
}

func (e AgentNode) DependantFieldIdentifierToTypeMap() map[string]map[string]entitytypes.FieldType {
	res := make(map[string]map[string]entitytypes.FieldType)

	return res
}

func (e AgentNode) EntityIdentifier() string {
	return "agent_node"
}

func (e AgentNode) PrimaryKeyIdentifiers() []string {
	return []string{
		"uuid",
	}
}

func (e AgentNode) ArrayFieldIdentifierToType() map[string]entitytypes.FieldType {
	res := make(map[string]entitytypes.FieldType)

	return res
}
