// Code generated by nuzur go-code-gen. DO NOT EDIT.

package agent_node

import (
	"github.com/nextwave/donald/entity/validation"
)

// Validate checks this AgentNode against the schema's field type and
// type-config rules, aggregating every problem into a single *validation.Error.
// It mirrors the change-request data validation enforced in
// product/module/datavalidation, so data written through this API is held to
// the same rules. Generated by go-code-gen — do not edit.
func (e AgentNode) Validate() error {
	c := validation.NewCollector()
	if e.UUID.IsNil() {
		c.Require("agent_node.uuid")
	}
	if e.RunUUID.IsNil() {
		c.Require("agent_node.run_uuid")
	}
	if e.NodeKey == "" {
		c.Require("agent_node.node_key")
	} else {
		c.Field("agent_node.node_key", validation.String(e.NodeKey, 0, 255, ""))

	}
	if e.Name == "" {
		c.Require("agent_node.name")
	} else {
		c.Field("agent_node.name", validation.String(e.Name, 0, 255, ""))

	}
	if e.NodeType.ToInt64() != 0 {
		c.Field("agent_node.node_type", validation.EnumMember(e.NodeType.ToInt64(), []int64{0, 1, 2, 3, 4, 5, 6, 7, 8}, "agent_node_type"))

	}
	if e.AgentLabel.Valid && e.AgentLabel.String != "" {
		c.Field("agent_node.agent_label", validation.String(e.AgentLabel.String, 0, 120, ""))

	}
	if e.ToolName.Valid && e.ToolName.String != "" {
		c.Field("agent_node.tool_name", validation.String(e.ToolName.String, 0, 255, ""))

	}
	if e.Status.ToInt64() == 0 {
		c.Require("agent_node.status")
	} else {
		c.Field("agent_node.status", validation.EnumMember(e.Status.ToInt64(), []int64{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, "agent_node_status"))

	}
	if e.ProgressPercent.Valid {
		c.Field("agent_node.progress_percent", validation.Integer(e.ProgressPercent.Int64, false, 0, 0, false, false, false, true, -32768, 32767))

	}
	if e.PlanOrder.Valid {
		c.Field("agent_node.plan_order", validation.Integer(e.PlanOrder.Int64, false, 0, 0, false, false, false, true, -32768, 32767))

	}
	if e.CreatedBy.IsNil() {
		c.Require("agent_node.created_by")
	}
	if e.UpdatedBy.IsNil() {
		c.Require("agent_node.updated_by")
	}

	return c.Result()
}
