// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nextwave/donald/entity/artifact"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchArtifactByRunUUIDRequest struct {
	RunUUID uuid.UUID

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchArtifactByRunUUIDRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("run_uuid", r.RunUUID.String())

	return nil
}

type FetchArtifactByRunUUIDResponse struct {
	Results []main_entity.Artifact
}
