// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nextwave/donald/entity/artifact"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchArtifactByUUIDRequest struct {
	UUID uuid.UUID
}

func (r FetchArtifactByUUIDRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("uuid", r.UUID.String())

	return nil
}

type FetchArtifactByUUIDResponse struct {
	Results []main_entity.Artifact
}
