// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nextwave/donald/entity/artifact"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchArtifactByNodeUUIDRequest struct {
	NodeUUID *uuid.UUID

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchArtifactByNodeUUIDRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	return nil
}

type FetchArtifactByNodeUUIDResponse struct {
	Results []main_entity.Artifact
}
