// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nextwave/donald/entity/artifact"

	"github.com/gofrs/uuid"
)

type UpsertRequest struct {
	Artifact main_entity.Artifact
}

type UpsertResponse struct {
	UUID uuid.UUID
}
