// Code generated by nuzur go-code-gen. DO NOT EDIT.

package agent_event

import (
	"context"
	"fmt"

	"github.com/nextwave/donald/core/module/agent_event/types"

	"errors"
	donalddb "github.com/nextwave/donald/core/repository/gen"

	"github.com/nextwave/donald/entity/mapper"
)

func (m *module) FetchAgentEventByNodeUUIDAndSequence(
	ctx context.Context,
	req types.FetchAgentEventByNodeUUIDAndSequenceRequest,
	opts ...Option,
) (types.FetchAgentEventByNodeUUIDAndSequenceResponse, error) {

	resolvedOpts := applyAllOptions(opts)
	queries := m.repository.Queries
	if resolvedOpts.SQLTx != nil {
		queries = queries.WithTx(resolvedOpts.SQLTx)
	}
	// A read inside a transaction must observe that transaction's own
	// uncommitted writes, so it can neither be served from the shared cache nor
	// be collapsed into another caller's in-flight query.
	skipShared := resolvedOpts.SkipCache || resolvedOpts.SQLTx != nil
	cacheKey := fmt.Sprintf("FetchAgentEventByNodeUUIDAndSequence:%v", req)
	if !skipShared {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.FetchAgentEventByNodeUUIDAndSequenceResponse), nil
		}
	}
	fetch := func() (any, error) {
		if req.OrderBy == "" {
			models, err := queries.FetchAgentEventByNodeUUIDAndSequence(
				ctx,
				donalddb.FetchAgentEventByNodeUUIDAndSequenceParams{
					NodeUUID: mapper.UUIDPtrToNullString(req.NodeUUID),

					Sequence: req.Sequence,

					Offset: req.Offset,
					Limit:  req.Limit,
				},
			)

			if err != nil {

				return types.FetchAgentEventByNodeUUIDAndSequenceResponse{}, err
			}
			return types.FetchAgentEventByNodeUUIDAndSequenceResponse{
				Results: mapModelsToEntities(models),
			}, nil
		}

		err := errors.New("could not process request")

		return types.FetchAgentEventByNodeUUIDAndSequenceResponse{}, err
	} // end fetch
	var v any
	var fetchErr error
	if skipShared {
		v, fetchErr = fetch()
	} else {
		v, fetchErr, _ = m.sg.Do(cacheKey, fetch)
	}
	if fetchErr != nil {
		return types.FetchAgentEventByNodeUUIDAndSequenceResponse{}, fetchErr
	}
	result := v.(types.FetchAgentEventByNodeUUIDAndSequenceResponse)
	if !skipShared {
		m.cache.Set(cacheKey, result, 0)
	}
	return result, nil

}
