// Code generated by nuzur go-code-gen. DO NOT EDIT.

package agent_event

import (
	"context"
	"fmt"

	"github.com/nextwave/donald/core/module/agent_event/types"

	"errors"
	donalddb "github.com/nextwave/donald/core/repository/gen"
)

func (m *module) FetchAgentEventByRunUUIDAndSequence(
	ctx context.Context,
	req types.FetchAgentEventByRunUUIDAndSequenceRequest,
	opts ...Option,
) (types.FetchAgentEventByRunUUIDAndSequenceResponse, error) {

	resolvedOpts := applyAllOptions(opts)
	queries := m.repository.Queries
	if resolvedOpts.SQLTx != nil {
		queries = queries.WithTx(resolvedOpts.SQLTx)
	}
	// A read inside a transaction must observe that transaction's own
	// uncommitted writes, so it can neither be served from the shared cache nor
	// be collapsed into another caller's in-flight query.
	skipShared := resolvedOpts.SkipCache || resolvedOpts.SQLTx != nil
	cacheKey := fmt.Sprintf("FetchAgentEventByRunUUIDAndSequence:%v", req)
	if !skipShared {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.FetchAgentEventByRunUUIDAndSequenceResponse), nil
		}
	}
	fetch := func() (any, error) {
		if req.OrderBy == "" {
			models, err := queries.FetchAgentEventByRunUUIDAndSequence(
				ctx,
				donalddb.FetchAgentEventByRunUUIDAndSequenceParams{
					RunUUID: req.RunUUID.String(),

					Sequence: req.Sequence,

					Offset: req.Offset,
					Limit:  req.Limit,
				},
			)

			if err != nil {

				return types.FetchAgentEventByRunUUIDAndSequenceResponse{}, err
			}
			return types.FetchAgentEventByRunUUIDAndSequenceResponse{
				Results: mapModelsToEntities(models),
			}, nil
		}

		err := errors.New("could not process request")

		return types.FetchAgentEventByRunUUIDAndSequenceResponse{}, err
	} // end fetch
	var v any
	var fetchErr error
	if skipShared {
		v, fetchErr = fetch()
	} else {
		v, fetchErr, _ = m.sg.Do(cacheKey, fetch)
	}
	if fetchErr != nil {
		return types.FetchAgentEventByRunUUIDAndSequenceResponse{}, fetchErr
	}
	result := v.(types.FetchAgentEventByRunUUIDAndSequenceResponse)
	if !skipShared {
		m.cache.Set(cacheKey, result, 0)
	}
	return result, nil

}
