// Code generated by nuzur go-code-gen. DO NOT EDIT.

package agent_event

import (
	donalddb "github.com/nextwave/donald/core/repository/gen"
	main_entity "github.com/nextwave/donald/entity/agent_event"

	"github.com/nextwave/donald/entity/mapper"

	"github.com/guregu/null/v6"
	"github.com/nextwave/donald/entity/agent_event_payload"
	"github.com/nextwave/donald/enums"
)

func mapModelsToEntities(models []donalddb.AgentEvent) []main_entity.AgentEvent {
	result := []main_entity.AgentEvent{}
	for _, p := range models {
		result = append(result, mapModelToEntity(p))
	}
	return result
}

func mapModelToEntity(m donalddb.AgentEvent) main_entity.AgentEvent {
	return main_entity.AgentEvent{
		UUID:           mapper.StringToUUID(m.UUID),
		RunUUID:        mapper.StringToUUID(m.RunUUID),
		Sequence:       int64(m.Sequence),
		EventType:      enums.AgentEventType(m.EventType),
		NodeUUID:       mapper.StringToUUIDPtr(m.NodeUUID),
		AgentLabel:     null.NewString(m.AgentLabel.String, m.AgentLabel.Valid),
		IdempotencyKey: m.IdempotencyKey,
		OccurredAt:     m.OccurredAt,
		Status:         enums.AgentEventStatus(m.Status),
		CreatedBy:      mapper.StringToUUID(m.CreatedBy),
		UpdatedBy:      mapper.StringToUUID(m.UpdatedBy),
		CreatedAt:      m.CreatedAt,
		UpdatedAt:      m.UpdatedAt,
		Payload:        agent_event_payload.AgentEventPayloadFromJSON(m.Payload),
	}
}
