// Code generated by nuzur go-code-gen. DO NOT EDIT.

package agent_event

import (
	"context"
	"errors"

	"github.com/nextwave/donald/core/module/agent_event/types"
	donalddb "github.com/nextwave/donald/core/repository/gen"

	"github.com/nextwave/donald/entity/agent_event_payload"

	"time"

	"github.com/nextwave/donald/entity/mapper"
)

func (m *module) Update(
	ctx context.Context,
	req types.UpsertRequest,
	opts ...Option,
) (types.UpsertResponse, error) {
	optConfig := applyAllOptions(opts)

	tx := optConfig.SQLTx
	createdTx := false
	if tx == nil {
		ntx, err := m.repository.DB.Begin()
		if err != nil {
			return types.UpsertResponse{}, err
		}
		tx = ntx
		defer tx.Rollback()
		createdTx = true
	}

	qtx := m.repository.Queries.WithTx(tx)
	existing, err := qtx.FetchAgentEventByUUIDForUpdate(ctx,
		req.AgentEvent.UUID.String(),
	)
	if err != nil {

		return types.UpsertResponse{}, err
	}

	if len(existing) == 0 {
		err := errors.New("entity not found")

		return types.UpsertResponse{}, err
	}

	// refresh server-managed timestamps that update on every write (updated_at)
	req.AgentEvent.UpdatedAt = time.Now()

	// validate the merged entity against the schema's field type/type-config rules
	if err := req.AgentEvent.Validate(); err != nil {

		return types.UpsertResponse{}, err
	}

	params := mapUpsertRequestToUpdateParams(req)
	err = qtx.UpdateAgentEvent(
		ctx,
		params,
	)
	if err != nil {

		return types.UpsertResponse{}, err
	}

	if createdTx {
		err := tx.Commit()
		if err != nil {

			return types.UpsertResponse{}, err
		}
	}

	// The rows this module caches have changed, so everything it holds is
	// suspect: drop it rather than answer a later read from a snapshot that
	// predates this write. The cache is per entity, so this discards only this
	// entity's reads. (It is a no-op while a caller-supplied transaction is
	// still open — those reads bypass the cache anyway.)
	m.cache.Flush()

	return buildUpdateResponse(req), nil
}

func buildUpdateResponse(req types.UpsertRequest) types.UpsertResponse {
	return types.UpsertResponse{

		UUID: req.AgentEvent.UUID,
	}
}

func mapUpsertRequestToUpdateParams(req types.UpsertRequest) donalddb.UpdateAgentEventParams {
	return donalddb.UpdateAgentEventParams{
		UUID: req.AgentEvent.UUID.String(),

		RunUUID: req.AgentEvent.RunUUID.String(),

		Sequence: req.AgentEvent.Sequence,

		EventType: req.AgentEvent.EventType.ToInt64(),

		NodeUUID: mapper.UUIDPtrToNullString(req.AgentEvent.NodeUUID),

		AgentLabel: req.AgentEvent.AgentLabel,

		IdempotencyKey: req.AgentEvent.IdempotencyKey,

		OccurredAt: req.AgentEvent.OccurredAt,

		Status: req.AgentEvent.Status.ToInt64(),

		CreatedBy: req.AgentEvent.CreatedBy.String(),

		UpdatedBy: req.AgentEvent.UpdatedBy.String(),

		CreatedAt: req.AgentEvent.CreatedAt,

		UpdatedAt: req.AgentEvent.UpdatedAt,

		Payload: mapper.JSON(agent_event_payload.AgentEventPayloadToJSON(req.AgentEvent.Payload)),
	}
}
